module.exports = (sequelize, DataTypes) => sequelize.define('PaymentReceipt', {
  id: { type: DataTypes.BIGINT, autoIncrement: true, primaryKey: true },
  receiptNumber: { type: DataTypes.STRING(40), allowNull: false, unique: true },
  paymentId: { type: DataTypes.BIGINT, allowNull: false },
  studentId: { type: DataTypes.BIGINT, allowNull: false },
  studentFeeId: { type: DataTypes.BIGINT, allowNull: true },
  feeInstallmentId: { type: DataTypes.BIGINT, allowNull: true },
  courseId: { type: DataTypes.BIGINT, allowNull: true },
  batchId: { type: DataTypes.BIGINT, allowNull: true },
  receiptDate: { type: DataTypes.DATE, allowNull: false },
  paidAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false },
  currency: { type: DataTypes.STRING(10), allowNull: false, defaultValue: 'LKR' },
  paymentMethod: { type: DataTypes.STRING(80), allowNull: true },
  transactionReference: { type: DataTypes.STRING(180), allowNull: true },
  totalCourseFee: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
  totalPaidAfterPayment: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
  remainingBalance: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
  studentNameSnapshot: { type: DataTypes.STRING(180), allowNull: false },
  studentNumberSnapshot: { type: DataTypes.STRING(80), allowNull: true },
  studentPhoneSnapshot: { type: DataTypes.STRING(50), allowNull: true },
  courseNameSnapshot: { type: DataTypes.STRING(180), allowNull: true },
  batchNameSnapshot: { type: DataTypes.STRING(180), allowNull: true },
  payerNameSnapshot: { type: DataTypes.STRING(180), allowNull: true },
  verifiedByUserId: { type: DataTypes.BIGINT, allowNull: true },
  generatedByUserId: { type: DataTypes.BIGINT, allowNull: true },
  generationSource: { type: DataTypes.STRING(30), allowNull: false, validate: { isIn: [['PAYMENT_APPROVAL', 'MANUAL_PAYMENT', 'ADMIN_REGENERATE', 'IMPORT']] } },
  verificationTokenHash: { type: DataTypes.STRING(64), allowNull: false, unique: true },
  verificationTokenEncrypted: { type: DataTypes.TEXT, allowNull: false },
  pdfStorageKey: { type: DataTypes.STRING(500), allowNull: true },
  pdfFileHash: { type: DataTypes.STRING(64), allowNull: true },
  status: { type: DataTypes.STRING(20), allowNull: false, defaultValue: 'ACTIVE', validate: { isIn: [['ACTIVE', 'VOID', 'REVERSED']] } },
  voidReason: { type: DataTypes.TEXT, allowNull: true },
  voidedByUserId: { type: DataTypes.BIGINT, allowNull: true },
  voidedAt: { type: DataTypes.DATE, allowNull: true },
  whatsappSentAt: { type: DataTypes.DATE, allowNull: true },
  whatsappMessageId: { type: DataTypes.STRING(255), allowNull: true },
  deletedAt: { type: DataTypes.DATE, allowNull: true }
}, {
  tableName: 'payment_receipts', timestamps: true, paranoid: true, underscored: true,
  defaultScope: { attributes: { exclude: ['verificationTokenHash', 'verificationTokenEncrypted'] } },
  scopes: { withVerificationToken: { attributes: { include: ['verificationTokenHash', 'verificationTokenEncrypted'] } } },
  indexes: [
    { fields: ['payment_id'] }, { fields: ['student_id'] }, { fields: ['receipt_date'] },
    { fields: ['status'] }, { fields: ['fee_installment_id'] }
  ]
});
