import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Autocomplete, Box, Button, Checkbox, CircularProgress, Divider, FormControlLabel, Grid, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { hasPermission } from '../utils/access';
import { getRoles } from '../services/userManagement.service';
import { addRoutingAgent, createWhatsAppRouting, deleteRoutingAgent, getRoutingEligibleAgents, getWhatsAppRouting, testWhatsAppRouting, updateRoutingAgent, updateWhatsAppRouting } from '../services/whatsappAccount.service';

const defaults = { name: 'Default lead routing', isEnabled: true, assignmentStrategy: 'least_open_chats', departmentId: '', fallbackDepartmentId: '', fallbackAgentId: '', managerUserId: '', respectWorkingHours: false, stickyAssignment: true, reassignIfUnavailable: false, reassignAfterMinutes: '', maxOpenChatsPerAgent: '', allowGlobalFallback: false, notifyManagerWhenUnassigned: true };
const strategies = [['least_open_chats','Least open chats'],['round_robin','Round robin'],['least_assigned_leads','Least assigned leads'],['weighted','Weighted'],['specific_agent','Specific agent'],['manual','Manual']];

export default function WhatsAppLeadRoutingPanel({ accountId }) {
  const canView = hasPermission('whatsapp_routing.view'); const canEdit = hasPermission('whatsapp_routing.edit') || hasPermission('whatsapp_routing.create'); const canManage = hasPermission('whatsapp_routing.manage_agents');
  const [rule, setRule] = useState(null); const [form, setForm] = useState(defaults); const [agents, setAgents] = useState([]); const [options, setOptions] = useState([]); const [roles, setRoles] = useState([]); const [search, setSearch] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(null); const [testResult, setTestResult] = useState(null);
  useEffect(() => { if (!canView || !accountId) return; Promise.all([getWhatsAppRouting(accountId), getRoles()]).then(([rulesRes, rolesRes]) => { const found = rulesRes.data.data?.[0] || null; setRule(found); setForm(found ? { ...defaults, ...found } : defaults); setAgents((found?.agents || []).map((member) => ({ ...member.agent, ...member, agentId: member.agentId }))); setRoles(rolesRes.data.data || []); }).catch((error) => setMessage({ severity: 'error', text: error.response?.data?.message || 'Unable to load routing.' })); }, [accountId, canView]);
  useEffect(() => { if (!canView || !accountId) return undefined; const timer = setTimeout(() => getRoutingEligibleAgents(accountId, search).then((response) => setOptions(response.data.data?.rows || [])).catch(() => setOptions([])), 250); return () => clearTimeout(timer); }, [accountId, canView, search]);
  const selectedIds = useMemo(() => new Set(agents.map((agent) => String(agent.agentId || agent.id))), [agents]);
  if (!canView) return <Alert severity="info">You do not have permission to view lead routing.</Alert>;
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { try { setBusy(true); let current = rule; if (current) await updateWhatsAppRouting(accountId, current.id, form); else { const response = await createWhatsAppRouting(accountId, { ...form, agents: [] }); current = response.data.data; } if (canManage) { const existing = new Set((rule?.agents || []).map((item) => String(item.agentId))); for (const agent of agents) { const payload = { agentId: agent.agentId || agent.id, weight: agent.weight || 1, priority: agent.priority || 0, maxOpenChats: agent.maxOpenChats ?? null, isEnabled: agent.isEnabled !== false }; if (existing.has(String(payload.agentId))) await updateRoutingAgent(accountId, current.id, payload.agentId, payload); else await addRoutingAgent(accountId, current.id, payload); } for (const member of rule?.agents || []) if (!selectedIds.has(String(member.agentId))) await deleteRoutingAgent(accountId, current.id, member.agentId); } setRule({ ...current, ...form, agents: agents.map((agent) => ({ ...agent, agentId: agent.agentId || agent.id })) }); setMessage({ severity: 'success', text: 'Number-based routing saved.' }); } catch (error) { setMessage({ severity: 'error', text: error.response?.data?.message || error.message }); } finally { setBusy(false); } };
  const test = async () => { try { setBusy(true); const response = await testWhatsAppRouting(accountId); setTestResult(response.data.data); } catch (error) { setMessage({ severity: 'error', text: error.response?.data?.message || error.message }); } finally { setBusy(false); } };
  return <Stack spacing={2}>
    <Divider /><Typography variant="h6" fontWeight={800}>Lead Routing</Typography>
    {message && <Alert severity={message.severity}>{message.text}</Alert>}
    <FormControlLabel control={<Checkbox checked={Boolean(form.isEnabled)} disabled={!canEdit} onChange={(e) => update('isEnabled', e.target.checked)} />} label="Enable number-based routing" />
    <Grid container spacing={2}>
      <Grid item xs={12} md={6}><TextField fullWidth label="Rule name" value={form.name} disabled={!canEdit} onChange={(e) => update('name', e.target.value)} /></Grid>
      <Grid item xs={12} md={6}><TextField select fullWidth label="Assignment strategy" value={form.assignmentStrategy} disabled={!canEdit} onChange={(e) => update('assignmentStrategy', e.target.value)}>{strategies.map(([value,label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></Grid>
      <Grid item xs={12} md={6}><TextField select fullWidth label="Department" value={form.departmentId || ''} disabled={!canEdit} onChange={(e) => update('departmentId', e.target.value)}><MenuItem value="">Any configured department</MenuItem>{roles.map((role) => <MenuItem key={role.id} value={role.id}>{role.name}</MenuItem>)}</TextField></Grid>
      <Grid item xs={12} md={6}><TextField type="number" fullWidth label="Maximum open chats per agent" value={form.maxOpenChatsPerAgent ?? ''} disabled={!canEdit} onChange={(e) => update('maxOpenChatsPerAgent', e.target.value)} /></Grid>
      <Grid item xs={12} md={6}><TextField select fullWidth label="Fallback department" value={form.fallbackDepartmentId || ''} disabled={!canEdit} onChange={(e) => update('fallbackDepartmentId', e.target.value)}><MenuItem value="">None</MenuItem>{roles.map((role) => <MenuItem key={role.id} value={role.id}>{role.name}</MenuItem>)}</TextField></Grid>
      <Grid item xs={12} md={6}><Autocomplete options={options} getOptionLabel={(a) => `${a.name} — ${a.department || 'No department'}`} value={options.find((a) => String(a.id) === String(form.fallbackAgentId)) || null} onInputChange={(_, value) => setSearch(value)} onChange={(_, value) => update('fallbackAgentId', value?.id || '')} renderInput={(params) => <TextField {...params} label="Fallback / specific agent" />} disabled={!canEdit} /></Grid>
      <Grid item xs={12} md={6}><Autocomplete options={options} getOptionLabel={(a) => `${a.name} — ${a.department || 'No department'}`} value={options.find((a) => String(a.id) === String(form.managerUserId)) || null} onInputChange={(_, value) => setSearch(value)} onChange={(_, value) => update('managerUserId', value?.id || '')} renderInput={(params) => <TextField {...params} label="Manager / team leader to notify" />} disabled={!canEdit} /></Grid>
    </Grid>
    <Stack direction={{ xs:'column', md:'row' }} spacing={1} flexWrap="wrap">
      {[['respectWorkingHours','Respect working hours'],['stickyAssignment','Sticky assignment'],['reassignIfUnavailable','Reassign if unavailable'],['allowGlobalFallback','Allow global auto-assignment fallback'],['notifyManagerWhenUnassigned','Notify manager when unassigned']].map(([key,label]) => <FormControlLabel key={key} control={<Checkbox checked={Boolean(form[key])} disabled={!canEdit} onChange={(e) => update(key,e.target.checked)} />} label={label} />)}
    </Stack>
    {form.reassignIfUnavailable && <TextField type="number" label="Reassign timeout (minutes)" value={form.reassignAfterMinutes ?? ''} disabled={!canEdit} onChange={(e) => update('reassignAfterMinutes', e.target.value)} />}
    <Autocomplete multiple options={options.filter((option) => !selectedIds.has(String(option.id)))} value={[]} inputValue={search} onInputChange={(_, value) => setSearch(value)} onChange={(_, values) => setAgents((current) => [...current, ...values.map((agent) => ({ ...agent, agentId: agent.id, weight: 1, priority: 0, isEnabled: true }))])} getOptionLabel={(a) => `${a.name} — ${a.department || 'No department'} — ${a.openChats} open`} renderInput={(params) => <TextField {...params} label="Search and add agents" />} disabled={!canManage} />
    {agents.map((agent, index) => <Paper variant="outlined" key={agent.agentId || agent.id} sx={{ p: 1.5 }}><Grid container spacing={1} alignItems="center"><Grid item xs={12} md={4}><Typography fontWeight={700}>{agent.name || [agent.firstName,agent.lastName].filter(Boolean).join(' ') || agent.email}</Typography><Typography variant="caption">{agent.department || 'No department'} · {agent.isAvailable === false ? 'Unavailable' : 'Available'} · {agent.openChats || 0} open · {agent.assignedLeads || 0} leads</Typography></Grid>{[['weight','Weight'],['priority','Priority'],['maxOpenChats','Capacity']].map(([key,label]) => <Grid item xs={4} md={2} key={key}><TextField size="small" type="number" label={label} value={agent[key] ?? ''} disabled={!canManage} onChange={(e) => setAgents((current) => current.map((row,i) => i === index ? { ...row, [key]: e.target.value } : row))} /></Grid>)}<Grid item xs={12} md={2}><FormControlLabel control={<Checkbox checked={agent.isEnabled !== false} disabled={!canManage} onChange={(e) => setAgents((current) => current.map((row,i) => i === index ? { ...row, isEnabled: e.target.checked } : row))} />} label="Enabled" /><Button color="error" disabled={!canManage} onClick={() => setAgents((current) => current.filter((_,i) => i !== index))}>Remove</Button></Grid></Grid></Paper>)}
    <Stack direction="row" spacing={1}><Button variant="contained" disabled={busy || !canEdit} onClick={save}>{busy ? <CircularProgress size={20} /> : 'Save routing'}</Button><Button variant="outlined" disabled={busy || !hasPermission('whatsapp_routing.test')} onClick={test}>Test Routing</Button></Stack>
    {testResult && <Alert severity={testResult.selectedAgent ? 'success' : 'warning'}>{testResult.selectedAgent ? `Selected ${testResult.selectedAgent.name || testResult.selectedAgent.agentId} using ${testResult.strategy}.` : `No agent selected. ${testResult.excludedAgents?.length || 0} agent(s) excluded.`}</Alert>}
  </Stack>;
}
