module.exports={async up(q,S){
 const money={type:S.DECIMAL(15,2),allowNull:true}, id={type:S.BIGINT.UNSIGNED,autoIncrement:true,primaryKey:true}, uid={type:S.BIGINT.UNSIGNED,allowNull:true}, dates={created_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')},updated_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')}};
 await q.createTable('commission_rules',{id,name:{type:S.STRING(180),allowNull:false},scope_type:{type:S.STRING(40),allowNull:false},agent_user_id:uid,department_id:{type:S.INTEGER.UNSIGNED,allowNull:true},course_id:uid,commission_type:{type:S.STRING(30),allowNull:false},percentage_rate:{type:S.DECIMAL(8,4)},fixed_amount:money,minimum_payment_amount:money,maximum_commission_amount:money,effective_from:{type:S.DATEONLY,allowNull:false},effective_to:{type:S.DATEONLY},active:{type:S.BOOLEAN,allowNull:false,defaultValue:true},priority:{type:S.INTEGER,allowNull:false,defaultValue:0},created_by_user_id:uid,...dates}).catch(()=>{});
 await q.createTable('commission_tiers',{id,commission_rule_id:{...uid,allowNull:false},minimum_count:{type:S.INTEGER.UNSIGNED,allowNull:false},maximum_count:{type:S.INTEGER.UNSIGNED},percentage_rate:{type:S.DECIMAL(8,4)},fixed_amount:money}).catch(()=>{});
 await q.createTable('agent_commissions',{id,agent_user_id:{...uid,allowNull:false},payment_id:{type:S.BIGINT},installment_id:{type:S.BIGINT.UNSIGNED,unique:true},student_id:uid,enrollment_id:uid,course_id:uid,conversation_id:uid,lead_id:uid,commission_rule_id:uid,gross_payment_amount:{...money,allowNull:false},eligible_amount:{...money,allowNull:false},commission_type:{type:S.STRING(30),allowNull:false},commission_rate:{type:S.DECIMAL(8,4)},commission_amount:{...money,allowNull:false},status:{type:S.STRING(30),allowNull:false,defaultValue:'pending'},attribution_source:{type:S.STRING(40),allowNull:false},calculated_at:{type:S.DATE,allowNull:false},approved_by_user_id:uid,approved_at:{type:S.DATE},paid_by_user_id:uid,paid_at:{type:S.DATE},payment_batch_id:uid,override_reason:{type:S.TEXT},reversed_commission_id:uid,notes:{type:S.TEXT},raw_calculation:{type:S.JSON},...dates}).catch(()=>{});
 await q.createTable('commission_adjustments',{id,agent_commission_id:{...uid,allowNull:false},adjustment_type:{type:S.STRING(30),allowNull:false},amount:{...money,allowNull:false},reason:{type:S.TEXT,allowNull:false},created_by_user_id:{...uid,allowNull:false},approved_by_user_id:uid,created_at:dates.created_at}).catch(()=>{});
 await q.createTable('commission_payout_batches',{id,batch_number:{type:S.STRING(80),allowNull:false,unique:true},period_start:{type:S.DATEONLY,allowNull:false},period_end:{type:S.DATEONLY,allowNull:false},total_amount:{...money,allowNull:false,defaultValue:0},status:{type:S.STRING(30),allowNull:false,defaultValue:'draft'},created_by_user_id:{...uid,allowNull:false},approved_by_user_id:uid,paid_by_user_id:uid,paid_at:{type:S.DATE},payment_reference:{type:S.STRING(180)},notes:{type:S.TEXT},...dates}).catch(()=>{});
 await q.createTable('commission_payout_items',{id,payout_batch_id:{...uid,allowNull:false},agent_commission_id:{...uid,allowNull:false,unique:true},agent_user_id:{...uid,allowNull:false},amount:{...money,allowNull:false},status:{type:S.STRING(30),allowNull:false,defaultValue:'included'},created_at:dates.created_at}).catch(()=>{});
 for(const [t,fs,n] of [['commission_rules',['scope_type','active'],'commission_rules_scope_active_idx'],['agent_commissions',['agent_user_id'],'agent_commissions_agent_idx'],['agent_commissions',['status'],'agent_commissions_status_idx'],['agent_commissions',['course_id'],'agent_commissions_course_idx'],['agent_commissions',['created_at'],'agent_commissions_created_idx']]) await q.addIndex(t,fs,{name:n}).catch(()=>{});
},async down(q){for(const t of ['commission_payout_items','commission_payout_batches','commission_adjustments','agent_commissions','commission_tiers','commission_rules'])await q.dropTable(t).catch(()=>{});}};
