const reasons=['No response','Not interested','Cannot afford','Joined another course','Wrong number','Duplicate lead','Not eligible','Follow-up missed','Other'];
const LOCK=570027;
async function tableExists(q,t,transaction){const[rows]=await q.sequelize.query('SELECT 1 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name=:table',{replacements:{table:t},transaction});return rows.length>0;}
async function add(q,t,c,d,transaction){const[rows]=await q.sequelize.query('SELECT 1 FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=:table AND column_name=:column',{replacements:{table:t,column:c},transaction});if(!rows.length)await q.addColumn(t,c,d,{transaction});}
module.exports={async up(q,S){const transaction=await q.sequelize.transaction();try{await q.sequelize.query("SET LOCAL lock_timeout='10s'",{transaction});await q.sequelize.query("SET LOCAL statement_timeout='120s'",{transaction});await q.sequelize.query('SELECT pg_advisory_xact_lock(:lock)',{replacements:{lock:LOCK},transaction});for(const [c,d] of [['code',{type:S.STRING(80),unique:true}],['display_order',{type:S.INTEGER,allowNull:false,defaultValue:0}],['active',{type:S.BOOLEAN,allowNull:false,defaultValue:true}],['is_closed',{type:S.BOOLEAN,allowNull:false,defaultValue:false}],['is_won',{type:S.BOOLEAN,allowNull:false,defaultValue:false}],['is_lost',{type:S.BOOLEAN,allowNull:false,defaultValue:false}],['color',{type:S.STRING(20)}]])await add(q,'lead_status',c,d,transaction);
 for(const [c,d] of [['last_followup_at',{type:S.DATE}],['followup_status',{type:S.STRING(30)}],['lost_reason_id',{type:S.INTEGER.UNSIGNED}],['lost_reason_text',{type:S.TEXT}],['converted_at',{type:S.DATE}],['converted_by_user_id',{type:S.BIGINT.UNSIGNED}]])await add(q,'leads',c,d,transaction);
 for(const [c,d] of [['conversation_id',{type:S.BIGINT.UNSIGNED}],['created_by_user_id',{type:S.BIGINT.UNSIGNED}],['followup_type',{type:S.STRING(30),allowNull:false,defaultValue:'general'}],['outcome',{type:S.TEXT}],['completed_by_user_id',{type:S.BIGINT.UNSIGNED}],['rescheduled_from_id',{type:S.BIGINT.UNSIGNED}]])await add(q,'followups',c,d,transaction);await q.changeColumn('followups','status',{type:S.STRING(30),allowNull:false,defaultValue:'pending'},{transaction});await q.changeColumn('followups','priority',{type:S.STRING(30),allowNull:false,defaultValue:'normal'},{transaction});
 if(!await tableExists(q,'lost_reasons',transaction))await q.createTable('lost_reasons',{id:{type:S.INTEGER.UNSIGNED,autoIncrement:true,primaryKey:true},name:{type:S.STRING(120),allowNull:false,unique:true},code:{type:S.STRING(80),allowNull:false,unique:true},active:{type:S.BOOLEAN,allowNull:false,defaultValue:true},display_order:{type:S.INTEGER,allowNull:false,defaultValue:0},created_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')},updated_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')}},{transaction});
 if(!await tableExists(q,'lead_activities',transaction))await q.createTable('lead_activities',{id:{type:S.BIGINT.UNSIGNED,autoIncrement:true,primaryKey:true},actor_user_id:{type:S.BIGINT.UNSIGNED},lead_id:{type:S.BIGINT.UNSIGNED,allowNull:false},action:{type:S.STRING(80),allowNull:false},old_value:{type:S.JSON},new_value:{type:S.JSON},note:{type:S.TEXT},created_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')}},{transaction});const[indexRows]=await q.sequelize.query("SELECT 1 FROM pg_indexes WHERE schemaname=current_schema() AND indexname='lead_activities_lead_created_idx'",{transaction});if(!indexRows.length)await q.addIndex('lead_activities',['lead_id','created_at'],{name:'lead_activities_lead_created_idx',transaction});
 // Unified lead statuses are normalized transactionally by migration 028.
 // Do not seed them here: this migration is replayed by the deployment runner and
 // name-based inserts here can race with, or prevent, the canonical normalization.
 let i=0;for(const name of reasons){i++;const code=name.toLowerCase().replace(/[^a-z0-9]+/g,'_');await q.sequelize.query(`INSERT INTO lost_reasons(name,code,active,display_order,created_at,updated_at)
   VALUES(:name,:code,TRUE,:order,NOW(),NOW()) ON CONFLICT DO NOTHING`,{replacements:{name,code,order:i},transaction});}await transaction.commit();
}catch(error){if(!transaction.finished)await transaction.rollback();throw error;}},async down(){},_test:{tableExists}};
