const stages=[['New Lead','new_lead',1,'#2196f3',false,false,false],['Contacted','contacted',2,'#607d8b',false,false,false],['Interested','interested',3,'#00a884',false,false,false],['Seminar Invited','seminar_invited',4,'#7e57c2',false,false,false],['Seminar Joined','seminar_joined',5,'#5e35b1',false,false,false],['Follow-up Required','followup_required',6,'#ff9800',false,false,false],['Payment Pending','payment_pending',7,'#f57c00',false,false,false],['Registered','registered',8,'#43a047',true,true,false],['Converted to Student','converted_to_student',9,'#2e7d32',true,true,false],['Not Interested','not_interested',10,'#9e9e9e',true,false,true],['Lost','lost',11,'#d32f2f',true,false,true]];
const reasons=['No response','Not interested','Cannot afford','Joined another course','Wrong number','Duplicate lead','Not eligible','Follow-up missed','Other'];
async function add(q,t,c,d){const x=await q.describeTable(t);if(!x[c])await q.addColumn(t,c,d);}
module.exports={async up(q,S){for(const [c,d] of [['code',{type:S.STRING(80),unique:true}],['display_order',{type:S.INTEGER,allowNull:false,defaultValue:0}],['active',{type:S.BOOLEAN,allowNull:false,defaultValue:true}],['is_closed',{type:S.BOOLEAN,allowNull:false,defaultValue:false}],['is_won',{type:S.BOOLEAN,allowNull:false,defaultValue:false}],['is_lost',{type:S.BOOLEAN,allowNull:false,defaultValue:false}],['color',{type:S.STRING(20)}]])await add(q,'lead_status',c,d);
 for(const [c,d] of [['last_followup_at',{type:S.DATE}],['followup_status',{type:S.STRING(30)}],['lost_reason_id',{type:S.INTEGER.UNSIGNED}],['lost_reason_text',{type:S.TEXT}],['converted_at',{type:S.DATE}],['converted_by_user_id',{type:S.BIGINT.UNSIGNED}]])await add(q,'leads',c,d);
 for(const [c,d] of [['conversation_id',{type:S.BIGINT.UNSIGNED}],['created_by_user_id',{type:S.BIGINT.UNSIGNED}],['followup_type',{type:S.STRING(30),allowNull:false,defaultValue:'general'}],['outcome',{type:S.TEXT}],['completed_by_user_id',{type:S.BIGINT.UNSIGNED}],['rescheduled_from_id',{type:S.BIGINT.UNSIGNED}]])await add(q,'followups',c,d);await q.changeColumn('followups','status',{type:S.STRING(30),allowNull:false,defaultValue:'pending'});await q.changeColumn('followups','priority',{type:S.STRING(30),allowNull:false,defaultValue:'normal'});
 await q.createTable('lost_reasons',{id:{type:S.INTEGER.UNSIGNED,autoIncrement:true,primaryKey:true},name:{type:S.STRING(120),allowNull:false,unique:true},code:{type:S.STRING(80),allowNull:false,unique:true},active:{type:S.BOOLEAN,allowNull:false,defaultValue:true},display_order:{type:S.INTEGER,allowNull:false,defaultValue:0},created_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')},updated_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')}}).catch(()=>{});
 await q.createTable('lead_activities',{id:{type:S.BIGINT.UNSIGNED,autoIncrement:true,primaryKey:true},actor_user_id:{type:S.BIGINT.UNSIGNED},lead_id:{type:S.BIGINT.UNSIGNED,allowNull:false},action:{type:S.STRING(80),allowNull:false},old_value:{type:S.JSON},new_value:{type:S.JSON},note:{type:S.TEXT},created_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')}}).catch(()=>{});await q.addIndex('lead_activities',['lead_id','created_at'],{name:'lead_activities_lead_created_idx'}).catch(()=>{});
 for(const [name,code,displayOrder,color,isClosed,isWon,isLost]of stages){const [rows]=await q.sequelize.query('SELECT id FROM lead_status WHERE lower(name)=lower(:name) LIMIT 1',{replacements:{name}});if(rows[0])await q.bulkUpdate('lead_status',{code,display_order:displayOrder,color,is_closed:isClosed,is_won:isWon,is_lost:isLost,active:true},{id:rows[0].id});else await q.bulkInsert('lead_status',[{name,description:`${name} pipeline stage`,code,display_order:displayOrder,color,is_closed:isClosed,is_won:isWon,is_lost:isLost,active:true,created_at:new Date(),updated_at:new Date()}]);}
 let i=0;for(const name of reasons){i++;const code=name.toLowerCase().replace(/[^a-z0-9]+/g,'_');await q.bulkInsert('lost_reasons',[{name,code,active:true,display_order:i,created_at:new Date(),updated_at:new Date()}]).catch(()=>{});}
 const [newRows]=await q.sequelize.query("SELECT id FROM lead_status WHERE code='new_lead' LIMIT 1");const [legacyRows]=await q.sequelize.query("SELECT id FROM lead_status WHERE lower(name)='new' LIMIT 1");if(newRows[0]&&legacyRows[0])await q.bulkUpdate('leads',{status_id:newRows[0].id,stage:'new_lead'},{status_id:legacyRows[0].id});
},async down(){}};
