'use strict';
const exists=async(q,t,transaction=null)=>{
  if(q.sequelize.getDialect()==='postgres'){
    const [rows]=await q.sequelize.query('SELECT to_regclass(:table) AS "name"',{replacements:{table:t},transaction});
    return Boolean(rows[0]?.name);
  }
  return (await q.showAllTables({transaction})).map(String).includes(t);
};
const operation=async(name,fn)=>{console.log(`[046_reminder_sequences_ai_providers.js] ${name}`);try{return await fn();}catch(error){error.migrationOperation=name;throw error;}};
const index=async(q,t,fields,name,options={},transaction)=>{
  const indexes=await q.showIndex(t,{transaction});
  if(indexes.some(item=>item.name===name))return;
  await q.addIndex(t,fields,{name,...options,transaction});
};
const requireColumns=async(q,table,names,transaction)=>{
  const columns=await q.describeTable(table,{transaction});
  const missing=names.filter(name=>!columns[name]);
  if(missing.length)throw Object.assign(new Error(`${table} is missing required columns: ${missing.join(', ')}`),{code:'MIGRATION_SCHEMA_INCOMPLETE',table,columns:missing});
};
const ensureColumns=async(q,table,definitions,transaction)=>{
  const columns=await q.describeTable(table,{transaction});
  for(const [name,definition]of Object.entries(definitions)){
    if(!columns[name])await operation(`add column ${table}.${name}`,()=>q.addColumn(table,name,definition,{transaction}));
  }
};
const duplicates=async(q,table,groupColumns,statusFilter,transaction)=>{
  const quoted=groupColumns.map(column=>`"${column}"`).join(', ');
  const [rows]=await q.sequelize.query(`SELECT ${quoted}, COUNT(*)::integer AS "count" FROM "${table}" ${statusFilter||''} GROUP BY ${quoted} HAVING COUNT(*) > 1 ORDER BY ${quoted}`,{transaction});
  return rows;
};
const assertNoDuplicates=(name,rows)=>{if(rows.length)throw Object.assign(new Error(`${name} cannot be created because duplicate rows exist. No data was changed. Review affected IDs in migrationDuplicates.`),{code:'MIGRATION_DUPLICATES_FOUND',migrationDuplicates:rows});};
const ensureForeignKey=async(q,{table,column,referencedTable,name,onDelete='NO ACTION'},transaction)=>{
  const references=await q.getForeignKeyReferencesForTable(table,{transaction});
  if(references.some(item=>(item.constraintName||item.constraint_name)===name||((item.columnName||item.column_name)===column&&(item.referencedTableName||item.referenced_table_name)===referencedTable)))return;
  const [orphans]=await q.sequelize.query(`SELECT child."id", child."${column}" FROM "${table}" child LEFT JOIN "${referencedTable}" parent ON parent."id"=child."${column}" WHERE child."${column}" IS NOT NULL AND parent."id" IS NULL ORDER BY child."id" LIMIT 100`,{transaction});
  if(orphans.length)throw Object.assign(new Error(`${name} cannot be created because orphan rows exist. No data was changed.`),{code:'MIGRATION_ORPHANS_FOUND',migrationOrphans:orphans});
  await q.addConstraint(table,{fields:[column],type:'foreign key',name,references:{table:referencedTable,field:'id'},onDelete,transaction});
};
async function ensureStatusEnumValues(q){
  if(q.sequelize.getDialect()!=='postgres')return;
  const [rows]=await q.sequelize.query(`SELECT t.typname AS "typeName", e.enumlabel AS "value" FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_type t ON t.oid=a.atttypid LEFT JOIN pg_enum e ON e.enumtypid=t.oid WHERE c.relname='reminder_subscriptions' AND a.attname='status' AND a.attnum>0`);
  if(!rows.length||!rows[0].value)return;
  const values=new Set(rows.map(row=>row.value));
  const typeName=rows[0].typeName;
  const quoted=q.queryGenerator.quoteIdentifier(typeName);
  for(const value of ['active','paused'])if(!values.has(value))await operation(`add enum value ${typeName}.${value}`,()=>q.sequelize.query(`ALTER TYPE ${quoted} ADD VALUE IF NOT EXISTS '${value}'`));
}
module.exports={async up(q,S){const D=S.DataTypes||S;await ensureStatusEnumValues(q);await q.sequelize.transaction(async transaction=>{
  if(!await exists(q,'reminder_sequences'))await q.createTable('reminder_sequences',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},name:{type:D.STRING(180),allowNull:false},description:D.TEXT,whatsapp_account_id:D.BIGINT,status:{type:D.STRING(20),allowNull:false,defaultValue:'draft'},stop_on_customer_reply:{type:D.BOOLEAN,allowNull:false,defaultValue:true},stop_on_lead_converted:{type:D.BOOLEAN,allowNull:false,defaultValue:false},stop_on_payment_confirmed:{type:D.BOOLEAN,allowNull:false,defaultValue:false},stop_on_label_added:D.BIGINT,timezone:{type:D.STRING(80),allowNull:false,defaultValue:'Asia/Colombo'},created_by:D.BIGINT,updated_by:D.BIGINT,created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false},deleted_at:D.DATE},{transaction});
  if(!await exists(q,'reminder_sequence_steps'))await q.createTable('reminder_sequence_steps',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},sequence_id:{type:D.BIGINT,allowNull:false,references:{model:'reminder_sequences',key:'id'},onDelete:'CASCADE'},step_number:{type:D.INTEGER,allowNull:false},delay_value:{type:D.INTEGER,allowNull:false,defaultValue:0},delay_unit:{type:D.STRING(15),allowNull:false},message_mode:{type:D.STRING(30),allowNull:false,defaultValue:'automatic'},session_message_type:{type:D.STRING(30),allowNull:false,defaultValue:'text'},body:D.TEXT,media_id:D.BIGINT,flow_id:D.BIGINT,template_id:D.BIGINT,template_language:D.STRING(20),template_parameter_mappings:{type:D.JSONB,allowNull:false,defaultValue:{}},button_configuration:{type:D.JSONB,allowNull:false,defaultValue:{}},continue_on_failure:{type:D.BOOLEAN,allowNull:false,defaultValue:false},enabled:{type:D.BOOLEAN,allowNull:false,defaultValue:true},created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false}},{transaction});
  if(!await exists(q,'reminder_subscriptions'))await q.createTable('reminder_subscriptions',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},sequence_id:{type:D.BIGINT,allowNull:false,references:{model:'reminder_sequences',key:'id'}},contact_id:{type:D.BIGINT,allowNull:false},conversation_id:{type:D.BIGINT,allowNull:false},whatsapp_account_id:{type:D.BIGINT,allowNull:false},phone:{type:D.STRING(50),allowNull:false},lead_id:D.BIGINT,student_id:D.BIGINT,status:{type:D.STRING(30),allowNull:false,defaultValue:'active'},current_step:{type:D.INTEGER,allowNull:false,defaultValue:0},subscribed_at:{type:D.DATE,allowNull:false},next_run_at:D.DATE,completed_at:D.DATE,cancelled_at:D.DATE,subscribed_by:D.BIGINT,subscription_source:{type:D.STRING(30),allowNull:false},source_reference_id:D.STRING(160),metadata:{type:D.JSONB,allowNull:false,defaultValue:{}},created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false}},{transaction});
  if(!await exists(q,'reminder_executions'))await q.createTable('reminder_executions',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},subscription_id:{type:D.BIGINT,allowNull:false,references:{model:'reminder_subscriptions',key:'id'}},sequence_step_id:{type:D.BIGINT,allowNull:false,references:{model:'reminder_sequence_steps',key:'id'}},conversation_id:{type:D.BIGINT,allowNull:false},whatsapp_account_id:{type:D.BIGINT,allowNull:false},scheduled_at:{type:D.DATE,allowNull:false},started_at:D.DATE,sent_at:D.DATE,status:{type:D.STRING(20),allowNull:false,defaultValue:'scheduled'},message_id:D.BIGINT,queue_id:D.BIGINT,whatsapp_message_id:D.STRING(255),error_code:D.STRING(80),error_message:D.TEXT,attempt_count:{type:D.INTEGER,allowNull:false,defaultValue:0},next_retry_at:D.DATE,metadata:{type:D.JSONB,allowNull:false,defaultValue:{}},created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false}},{transaction});
  await ensureColumns(q,'reminder_sequences',{name:{type:D.STRING(180),allowNull:false,defaultValue:'Untitled sequence'},description:{type:D.TEXT},whatsapp_account_id:{type:D.BIGINT},status:{type:D.STRING(20),allowNull:false,defaultValue:'draft'},stop_on_customer_reply:{type:D.BOOLEAN,allowNull:false,defaultValue:true},stop_on_lead_converted:{type:D.BOOLEAN,allowNull:false,defaultValue:false},stop_on_payment_confirmed:{type:D.BOOLEAN,allowNull:false,defaultValue:false},stop_on_label_added:{type:D.BIGINT},timezone:{type:D.STRING(80),allowNull:false,defaultValue:'Asia/Colombo'},created_by:{type:D.BIGINT},updated_by:{type:D.BIGINT},created_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')},updated_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')},deleted_at:{type:D.DATE}},transaction);
  await ensureColumns(q,'reminder_sequence_steps',{sequence_id:{type:D.BIGINT},step_number:{type:D.INTEGER},delay_value:{type:D.INTEGER,allowNull:false,defaultValue:0},delay_unit:{type:D.STRING(15),allowNull:false,defaultValue:'minutes'},message_mode:{type:D.STRING(30),allowNull:false,defaultValue:'automatic'},session_message_type:{type:D.STRING(30),allowNull:false,defaultValue:'text'},body:{type:D.TEXT},media_id:{type:D.BIGINT},flow_id:{type:D.BIGINT},template_id:{type:D.BIGINT},template_language:{type:D.STRING(20)},template_parameter_mappings:{type:D.JSONB,allowNull:false,defaultValue:{}},button_configuration:{type:D.JSONB,allowNull:false,defaultValue:{}},continue_on_failure:{type:D.BOOLEAN,allowNull:false,defaultValue:false},enabled:{type:D.BOOLEAN,allowNull:false,defaultValue:true},created_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')},updated_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')}},transaction);
  await ensureColumns(q,'reminder_subscriptions',{sequence_id:{type:D.BIGINT},contact_id:{type:D.BIGINT},conversation_id:{type:D.BIGINT},whatsapp_account_id:{type:D.BIGINT},phone:{type:D.STRING(50)},lead_id:{type:D.BIGINT},student_id:{type:D.BIGINT},status:{type:D.STRING(30),allowNull:false,defaultValue:'active'},current_step:{type:D.INTEGER,allowNull:false,defaultValue:0},subscribed_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')},next_run_at:{type:D.DATE},completed_at:{type:D.DATE},cancelled_at:{type:D.DATE},subscribed_by:{type:D.BIGINT},subscription_source:{type:D.STRING(30),allowNull:false,defaultValue:'api'},source_reference_id:{type:D.STRING(160)},metadata:{type:D.JSONB,allowNull:false,defaultValue:{}},created_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')},updated_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')}},transaction);
  await ensureColumns(q,'reminder_executions',{subscription_id:{type:D.BIGINT},sequence_step_id:{type:D.BIGINT},conversation_id:{type:D.BIGINT},whatsapp_account_id:{type:D.BIGINT},scheduled_at:{type:D.DATE},started_at:{type:D.DATE},sent_at:{type:D.DATE},status:{type:D.STRING(20),allowNull:false,defaultValue:'scheduled'},message_id:{type:D.BIGINT},queue_id:{type:D.BIGINT},whatsapp_message_id:{type:D.STRING(255)},error_code:{type:D.STRING(80)},error_message:{type:D.TEXT},attempt_count:{type:D.INTEGER,allowNull:false,defaultValue:0},next_retry_at:{type:D.DATE},metadata:{type:D.JSONB,allowNull:false,defaultValue:{}},created_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')},updated_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')}},transaction);
  if(!await exists(q,'ai_providers'))await q.createTable('ai_providers',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},name:{type:D.STRING(120),allowNull:false},provider_type:{type:D.STRING(40),allowNull:false},enabled:{type:D.BOOLEAN,allowNull:false,defaultValue:true},api_base_url:D.STRING(500),model:{type:D.STRING(120),allowNull:false},encrypted_api_key:D.TEXT,key_iv:D.STRING(64),key_tag:D.STRING(64),organization_id:D.STRING(180),project_id:D.STRING(180),default_temperature:{type:D.DECIMAL(4,2),allowNull:false,defaultValue:.3},max_output_tokens:{type:D.INTEGER,allowNull:false,defaultValue:1024},request_timeout:{type:D.INTEGER,allowNull:false,defaultValue:30000},retry_count:{type:D.INTEGER,allowNull:false,defaultValue:2},daily_budget:D.DECIMAL(12,2),is_default:{type:D.BOOLEAN,allowNull:false,defaultValue:false},last_test_status:D.STRING(30),last_test_at:D.DATE,created_by:D.BIGINT,updated_by:D.BIGINT,created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false}},{transaction});
  if(await exists(q,'ai_providers')){const columns=await q.describeTable('ai_providers');for(const [name,definition]of Object.entries({name:{type:D.STRING(120),allowNull:false,defaultValue:'AI Provider'},provider_type:{type:D.STRING(40),allowNull:false,defaultValue:'openai'},enabled:{type:D.BOOLEAN,allowNull:false,defaultValue:true},api_base_url:{type:D.STRING(500)},model:{type:D.STRING(120),allowNull:false,defaultValue:'gpt-4.1-mini'},encrypted_api_key:{type:D.TEXT},key_iv:{type:D.STRING(64)},key_tag:{type:D.STRING(64)},organization_id:{type:D.STRING(180)},project_id:{type:D.STRING(180)},default_temperature:{type:D.DECIMAL(4,2),allowNull:false,defaultValue:.3},max_output_tokens:{type:D.INTEGER,allowNull:false,defaultValue:1024},request_timeout:{type:D.INTEGER,allowNull:false,defaultValue:30000},retry_count:{type:D.INTEGER,allowNull:false,defaultValue:2},daily_budget:{type:D.DECIMAL(12,2)},is_default:{type:D.BOOLEAN,allowNull:false,defaultValue:false},last_test_status:{type:D.STRING(30)},last_test_at:{type:D.DATE},created_by:{type:D.BIGINT},updated_by:{type:D.BIGINT},created_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')},updated_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')}}))if(!columns[name])await q.addColumn('ai_providers',name,definition,{transaction});}
  if(await exists(q,'ai_agents')){const columns=await q.describeTable('ai_agents');for(const [name,definition]of Object.entries({provider_id:{type:D.BIGINT},confidence_threshold:{type:D.DECIMAL(4,3),allowNull:false,defaultValue:.65},stop_on_human_reply:{type:D.BOOLEAN,allowNull:false,defaultValue:true},context_message_limit:{type:D.INTEGER,allowNull:false,defaultValue:20},outcome_sequence_id:{type:D.BIGINT}}))if(!columns[name])await q.addColumn('ai_agents',name,definition,{transaction});}
  await requireColumns(q,'reminder_sequence_steps',['sequence_id','step_number'],transaction);
  await requireColumns(q,'reminder_subscriptions',['sequence_id','conversation_id','status'],transaction);
  await requireColumns(q,'reminder_executions',['status','scheduled_at','subscription_id','sequence_step_id'],transaction);
  await operation('ensure reminder step sequence foreign key',()=>ensureForeignKey(q,{table:'reminder_sequence_steps',column:'sequence_id',referencedTable:'reminder_sequences',name:'reminder_sequence_steps_sequence_id_fk',onDelete:'CASCADE'},transaction));
  await operation('ensure reminder subscription sequence foreign key',()=>ensureForeignKey(q,{table:'reminder_subscriptions',column:'sequence_id',referencedTable:'reminder_sequences',name:'reminder_subscriptions_sequence_id_fk'},transaction));
  await operation('ensure reminder execution subscription foreign key',()=>ensureForeignKey(q,{table:'reminder_executions',column:'subscription_id',referencedTable:'reminder_subscriptions',name:'reminder_executions_subscription_id_fk'},transaction));
  await operation('ensure reminder execution step foreign key',()=>ensureForeignKey(q,{table:'reminder_executions',column:'sequence_step_id',referencedTable:'reminder_sequence_steps',name:'reminder_executions_sequence_step_id_fk'},transaction));
  const stepDuplicates=await operation('check duplicate reminder steps',()=>duplicates(q,'reminder_sequence_steps',['sequence_id','step_number'],'',transaction));
  assertNoDuplicates('reminder_steps_order_uq',stepDuplicates);
  const executionDuplicates=await operation('check duplicate reminder executions',()=>duplicates(q,'reminder_executions',['subscription_id','sequence_step_id'],'',transaction));
  assertNoDuplicates('reminder_execution_step_uq',executionDuplicates);
  const activeDuplicates=await operation('check duplicate active reminder subscriptions',()=>duplicates(q,'reminder_subscriptions',['sequence_id','conversation_id'],"WHERE status IN ('active','paused')",transaction));
  assertNoDuplicates('reminder_active_subscription_uq',activeDuplicates);
  const providerDuplicates=await operation('check duplicate default AI providers',()=>duplicates(q,'ai_providers',['is_default'],'WHERE is_default = TRUE',transaction));
  assertNoDuplicates('ai_provider_default_uq',providerDuplicates);
  await operation('create reminder_steps_order_uq',()=>index(q,'reminder_sequence_steps',['sequence_id','step_number'],'reminder_steps_order_uq',{unique:true},transaction));
  await operation('create reminder_executions_due_idx',()=>index(q,'reminder_executions',['status','scheduled_at'],'reminder_executions_due_idx',{},transaction));
  await operation('create reminder_execution_step_uq',()=>index(q,'reminder_executions',['subscription_id','sequence_step_id'],'reminder_execution_step_uq',{unique:true},transaction));
  await operation('create reminder_active_subscription_uq',()=>index(q,'reminder_subscriptions',['sequence_id','conversation_id'],'reminder_active_subscription_uq',{unique:true,where:{status:['active','paused']}},transaction));
  await operation('create ai_provider_default_uq',()=>index(q,'ai_providers',['is_default'],'ai_provider_default_uq',{unique:true,where:{is_default:true}},transaction));
  if(await exists(q,'permissions'))for(const code of ['reminder_sequences.view','reminder_sequences.create','reminder_sequences.edit','reminder_sequences.delete','reminder_sequences.activate','reminder_sequences.subscribe','reminder_sequences.unsubscribe','reminder_sequences.retry','reminder_sequences.export','reminder_sequences.manage_settings','ai_providers.view','ai_providers.manage','ai_providers.test'])await q.sequelize.query(`INSERT INTO permissions (code, name, description, created_at, updated_at) SELECT :code,:name,:name,NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code=:code)`,{replacements:{code,name:code.replace(/[._]/g,' ')},transaction});
});},async down(){/* Data-retaining production migration. */}};
