'use strict';
const exists=async(q,t)=>Boolean(await q.describeTable(t).catch(()=>null));
const index=async(q,t,fields,name,options={},transaction)=>q.addIndex(t,fields,{name,...options,transaction}).catch(()=>null);
module.exports={async up(q,S){const D=S.DataTypes||S;await q.sequelize.transaction(async transaction=>{
  if(!await exists(q,'reminder_sequences'))await q.createTable('reminder_sequences',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},name:{type:D.STRING(180),allowNull:false},description:D.TEXT,whatsapp_account_id:D.BIGINT,status:{type:D.STRING(20),allowNull:false,defaultValue:'draft'},stop_on_customer_reply:{type:D.BOOLEAN,allowNull:false,defaultValue:true},stop_on_lead_converted:{type:D.BOOLEAN,allowNull:false,defaultValue:false},stop_on_payment_confirmed:{type:D.BOOLEAN,allowNull:false,defaultValue:false},stop_on_label_added:D.BIGINT,timezone:{type:D.STRING(80),allowNull:false,defaultValue:'Asia/Colombo'},created_by:D.BIGINT,updated_by:D.BIGINT,created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false},deleted_at:D.DATE},{transaction});
  if(!await exists(q,'reminder_sequence_steps'))await q.createTable('reminder_sequence_steps',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},sequence_id:{type:D.BIGINT,allowNull:false,references:{model:'reminder_sequences',key:'id'},onDelete:'CASCADE'},step_number:{type:D.INTEGER,allowNull:false},delay_value:{type:D.INTEGER,allowNull:false,defaultValue:0},delay_unit:{type:D.STRING(15),allowNull:false},message_mode:{type:D.STRING(30),allowNull:false,defaultValue:'automatic'},session_message_type:{type:D.STRING(30),allowNull:false,defaultValue:'text'},body:D.TEXT,media_id:D.BIGINT,flow_id:D.BIGINT,template_id:D.BIGINT,template_language:D.STRING(20),template_parameter_mappings:{type:D.JSONB,allowNull:false,defaultValue:{}},button_configuration:{type:D.JSONB,allowNull:false,defaultValue:{}},continue_on_failure:{type:D.BOOLEAN,allowNull:false,defaultValue:false},enabled:{type:D.BOOLEAN,allowNull:false,defaultValue:true},created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false}},{transaction});
  if(!await exists(q,'reminder_subscriptions'))await q.createTable('reminder_subscriptions',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},sequence_id:{type:D.BIGINT,allowNull:false,references:{model:'reminder_sequences',key:'id'}},contact_id:{type:D.BIGINT,allowNull:false},conversation_id:{type:D.BIGINT,allowNull:false},whatsapp_account_id:{type:D.BIGINT,allowNull:false},phone:{type:D.STRING(50),allowNull:false},lead_id:D.BIGINT,student_id:D.BIGINT,status:{type:D.STRING(30),allowNull:false,defaultValue:'active'},current_step:{type:D.INTEGER,allowNull:false,defaultValue:0},subscribed_at:{type:D.DATE,allowNull:false},next_run_at:D.DATE,completed_at:D.DATE,cancelled_at:D.DATE,subscribed_by:D.BIGINT,subscription_source:{type:D.STRING(30),allowNull:false},source_reference_id:D.STRING(160),metadata:{type:D.JSONB,allowNull:false,defaultValue:{}},created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false}},{transaction});
  if(!await exists(q,'reminder_executions'))await q.createTable('reminder_executions',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},subscription_id:{type:D.BIGINT,allowNull:false,references:{model:'reminder_subscriptions',key:'id'}},sequence_step_id:{type:D.BIGINT,allowNull:false,references:{model:'reminder_sequence_steps',key:'id'}},conversation_id:{type:D.BIGINT,allowNull:false},whatsapp_account_id:{type:D.BIGINT,allowNull:false},scheduled_at:{type:D.DATE,allowNull:false},started_at:D.DATE,sent_at:D.DATE,status:{type:D.STRING(20),allowNull:false,defaultValue:'scheduled'},message_id:D.BIGINT,queue_id:D.BIGINT,whatsapp_message_id:D.STRING(255),error_code:D.STRING(80),error_message:D.TEXT,attempt_count:{type:D.INTEGER,allowNull:false,defaultValue:0},next_retry_at:D.DATE,metadata:{type:D.JSONB,allowNull:false,defaultValue:{}},created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false}},{transaction});
  if(!await exists(q,'ai_providers'))await q.createTable('ai_providers',{id:{type:D.BIGINT,autoIncrement:true,primaryKey:true},name:{type:D.STRING(120),allowNull:false},provider_type:{type:D.STRING(40),allowNull:false},enabled:{type:D.BOOLEAN,allowNull:false,defaultValue:true},api_base_url:D.STRING(500),model:{type:D.STRING(120),allowNull:false},encrypted_api_key:D.TEXT,key_iv:D.STRING(64),key_tag:D.STRING(64),organization_id:D.STRING(180),project_id:D.STRING(180),default_temperature:{type:D.DECIMAL(4,2),allowNull:false,defaultValue:.3},max_output_tokens:{type:D.INTEGER,allowNull:false,defaultValue:1024},request_timeout:{type:D.INTEGER,allowNull:false,defaultValue:30000},retry_count:{type:D.INTEGER,allowNull:false,defaultValue:2},daily_budget:D.DECIMAL(12,2),is_default:{type:D.BOOLEAN,allowNull:false,defaultValue:false},last_test_status:D.STRING(30),last_test_at:D.DATE,created_by:D.BIGINT,updated_by:D.BIGINT,created_at:{type:D.DATE,allowNull:false},updated_at:{type:D.DATE,allowNull:false}},{transaction});
  if(await exists(q,'ai_providers')){const columns=await q.describeTable('ai_providers');for(const [name,definition]of Object.entries({name:{type:D.STRING(120),allowNull:false,defaultValue:'AI Provider'},provider_type:{type:D.STRING(40),allowNull:false,defaultValue:'openai'},enabled:{type:D.BOOLEAN,allowNull:false,defaultValue:true},api_base_url:{type:D.STRING(500)},model:{type:D.STRING(120),allowNull:false,defaultValue:'gpt-4.1-mini'},encrypted_api_key:{type:D.TEXT},key_iv:{type:D.STRING(64)},key_tag:{type:D.STRING(64)},organization_id:{type:D.STRING(180)},project_id:{type:D.STRING(180)},default_temperature:{type:D.DECIMAL(4,2),allowNull:false,defaultValue:.3},max_output_tokens:{type:D.INTEGER,allowNull:false,defaultValue:1024},request_timeout:{type:D.INTEGER,allowNull:false,defaultValue:30000},retry_count:{type:D.INTEGER,allowNull:false,defaultValue:2},daily_budget:{type:D.DECIMAL(12,2)},is_default:{type:D.BOOLEAN,allowNull:false,defaultValue:false},last_test_status:{type:D.STRING(30)},last_test_at:{type:D.DATE},created_by:{type:D.BIGINT},updated_by:{type:D.BIGINT},created_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')},updated_at:{type:D.DATE,allowNull:false,defaultValue:S.literal('NOW()')}}))if(!columns[name])await q.addColumn('ai_providers',name,definition,{transaction});}
  if(await exists(q,'ai_agents')){const columns=await q.describeTable('ai_agents');for(const [name,definition]of Object.entries({provider_id:{type:D.BIGINT},confidence_threshold:{type:D.DECIMAL(4,3),allowNull:false,defaultValue:.65},stop_on_human_reply:{type:D.BOOLEAN,allowNull:false,defaultValue:true},context_message_limit:{type:D.INTEGER,allowNull:false,defaultValue:20},outcome_sequence_id:{type:D.BIGINT}}))if(!columns[name])await q.addColumn('ai_agents',name,definition,{transaction});}
  await index(q,'reminder_sequence_steps',['sequence_id','step_number'],'reminder_steps_order_uq',{unique:true},transaction);
  await index(q,'reminder_executions',['status','scheduled_at'],'reminder_executions_due_idx',{},transaction);
  await index(q,'reminder_executions',['subscription_id','sequence_step_id'],'reminder_execution_step_uq',{unique:true},transaction);
  await q.sequelize.query("CREATE UNIQUE INDEX IF NOT EXISTS reminder_active_subscription_uq ON reminder_subscriptions(sequence_id, conversation_id) WHERE status IN ('active','paused')",{transaction});
  await q.sequelize.query("CREATE UNIQUE INDEX IF NOT EXISTS ai_provider_default_uq ON ai_providers(is_default) WHERE is_default = TRUE",{transaction});
  if(await exists(q,'permissions'))for(const code of ['reminder_sequences.view','reminder_sequences.create','reminder_sequences.edit','reminder_sequences.delete','reminder_sequences.activate','reminder_sequences.subscribe','reminder_sequences.unsubscribe','reminder_sequences.retry','reminder_sequences.export','reminder_sequences.manage_settings','ai_providers.view','ai_providers.manage','ai_providers.test'])await q.sequelize.query(`INSERT INTO permissions (code, name, description, created_at, updated_at) SELECT :code,:name,:name,NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code=:code)`,{replacements:{code,name:code.replace(/[._]/g,' ')},transaction});
});},async down(){/* Data-retaining production migration. */}};
