const permissions=['view_own','manage_own','view_team','manage_team','bulk_add','configure'].map(action=>[`call_queue.${action}`,`Call queue: ${action}`]).concat([['leads.call_unassigned','Call unassigned leads'],['leads.call_others','Call leads assigned to others']]);
async function exists(q,table){return(await q.showAllTables()).map(String).some(name=>name.toLowerCase()===table.toLowerCase());}
module.exports={async up(q,S){return q.sequelize.transaction(async transaction=>{
 if(q.sequelize.getDialect()==='postgres')await q.sequelize.query("SELECT pg_advisory_xact_lock(hashtext('migration:052_call_queue_phase1'))",{transaction});
 if(!await exists(q,'call_queues'))await q.createTable('call_queues',{id:{type:S.BIGINT,autoIncrement:true,primaryKey:true},agent_user_id:{type:S.BIGINT,allowNull:false},name:{type:S.STRING(120),allowNull:false,defaultValue:'My Queue'},status:{type:S.STRING(20),allowNull:false,defaultValue:'active'},is_default:{type:S.BOOLEAN,allowNull:false,defaultValue:true},created_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')},updated_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')}},{transaction});
 if(!await exists(q,'call_queue_entries'))await q.createTable('call_queue_entries',{id:{type:S.BIGINT,autoIncrement:true,primaryKey:true},queue_id:{type:S.BIGINT,allowNull:false},lead_id:{type:S.BIGINT,allowNull:false},position:{type:S.INTEGER,allowNull:false},priority:{type:S.INTEGER,allowNull:false,defaultValue:0},status:{type:S.STRING(20),allowNull:false,defaultValue:'pending'},source:{type:S.STRING(40),allowNull:false,defaultValue:'manual'},source_filter:{type:S.JSON},added_by_user_id:{type:S.BIGINT,allowNull:false},added_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')},claimed_at:S.DATE,completed_at:S.DATE,snoozed_until:S.DATE,skip_reason:S.TEXT,last_call_activity_id:S.BIGINT,version:{type:S.INTEGER,allowNull:false,defaultValue:0},created_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')},updated_at:{type:S.DATE,allowNull:false,defaultValue:S.fn('NOW')}},{transaction});
 const indexes=await q.showIndex('call_queues',{transaction});if(!indexes.some(i=>i.name==='call_queues_agent_default_uq'))await q.addIndex('call_queues',['agent_user_id'],{name:'call_queues_agent_default_uq',unique:true,where:{is_default:true},transaction});
 const entryIndexes=await q.showIndex('call_queue_entries',{transaction});if(!entryIndexes.some(i=>i.name==='call_queue_entries_active_lead_uq'))await q.sequelize.query("CREATE UNIQUE INDEX call_queue_entries_active_lead_uq ON call_queue_entries(queue_id,lead_id) WHERE status IN ('pending','calling','snoozed')",{transaction});if(!entryIndexes.some(i=>i.name==='call_queue_entries_next_idx'))await q.addIndex('call_queue_entries',['queue_id','status','priority','position'],{name:'call_queue_entries_next_idx',transaction});
 for(const[code,name]of permissions){const[rows]=await q.sequelize.query('SELECT id FROM permissions WHERE code=:code',{replacements:{code},transaction});if(!rows[0])await q.bulkInsert('permissions',[{code,name,description:name,created_at:new Date(),updated_at:new Date()}],{transaction});}
 const[agentRoles]=await q.sequelize.query("SELECT id FROM roles WHERE lower(name)='agent' AND deleted_at IS NULL",{transaction});if(agentRoles[0])for(const code of ['call_queue.view_own','call_queue.manage_own'])await q.sequelize.query('INSERT INTO role_permissions(role_id,permission_id,created_at,updated_at) SELECT :roleId,p.id,NOW(),NOW() FROM permissions p WHERE p.code=:code AND NOT EXISTS(SELECT 1 FROM role_permissions rp WHERE rp.role_id=:roleId AND rp.permission_id=p.id)',{replacements:{roleId:agentRoles[0].id,code},transaction});
});},async down(){}};
