const LOCK = 570062;
const PERMISSIONS = ['view_own','view_department','view_all','create','reply','add_internal_note','assign','reassign','change_priority','resolve','close','reopen','merge','manage_categories','view_reports','export'].map((name) => `support_tickets.${name}`);
module.exports.up = async (q) => {
  const t = await q.sequelize.transaction();
  try {
    await q.sequelize.query("SET LOCAL lock_timeout = '10s'", { transaction: t });
    await q.sequelize.query("SET LOCAL statement_timeout = '120s'", { transaction: t });
    await q.sequelize.query('SELECT pg_advisory_xact_lock(:lock)', { replacements: { lock: LOCK }, transaction: t });
    const sql = [
      `CREATE SEQUENCE IF NOT EXISTS support_ticket_number_seq START 1`,
      `CREATE TABLE IF NOT EXISTS support_ticket_categories (id BIGSERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE, default_department_id BIGINT NULL, default_priority VARCHAR(20) NOT NULL DEFAULT 'normal', sla_response_minutes INTEGER NULL, sla_resolution_minutes INTEGER NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
      `CREATE TABLE IF NOT EXISTS support_tickets (id BIGSERIAL PRIMARY KEY, ticket_number VARCHAR(32) NOT NULL UNIQUE, student_id BIGINT NOT NULL REFERENCES students(id), enrollment_id BIGINT NULL REFERENCES student_enrollments(id), course_id BIGINT NULL REFERENCES courses(id), conversation_id BIGINT NULL REFERENCES conversations(id), category_id BIGINT NOT NULL REFERENCES support_ticket_categories(id), subject VARCHAR(240) NOT NULL, description TEXT NOT NULL, priority VARCHAR(20) NOT NULL DEFAULT 'normal', status VARCHAR(40) NOT NULL DEFAULT 'new', department_id BIGINT NULL, assigned_user_id BIGINT NULL REFERENCES users(id), created_by_type VARCHAR(20) NOT NULL, created_by_user_id BIGINT NULL REFERENCES users(id), first_response_at TIMESTAMPTZ NULL, resolved_at TIMESTAMPTZ NULL, resolved_by_user_id BIGINT NULL REFERENCES users(id), resolution_summary TEXT NULL, closed_at TIMESTAMPTZ NULL, closed_by_user_id BIGINT NULL REFERENCES users(id), last_student_reply_at TIMESTAMPTZ NULL, last_staff_reply_at TIMESTAMPTZ NULL, sla_response_due_at TIMESTAMPTZ NULL, sla_resolution_due_at TIMESTAMPTZ NULL, merged_into_ticket_id BIGINT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
      `CREATE TABLE IF NOT EXISTS support_ticket_messages (id BIGSERIAL PRIMARY KEY, ticket_id BIGINT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, author_type VARCHAR(20) NOT NULL, author_user_id BIGINT NULL REFERENCES users(id), student_id BIGINT NULL REFERENCES students(id), body TEXT NOT NULL, is_internal BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
      `CREATE TABLE IF NOT EXISTS support_ticket_attachments (id BIGSERIAL PRIMARY KEY, ticket_id BIGINT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, message_id BIGINT NULL REFERENCES support_ticket_messages(id) ON DELETE CASCADE, media_id BIGINT NULL REFERENCES media(id), original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL, size_bytes BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
      `CREATE TABLE IF NOT EXISTS support_ticket_assignment_history (id BIGSERIAL PRIMARY KEY, ticket_id BIGINT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, previous_department_id BIGINT NULL, previous_user_id BIGINT NULL, new_department_id BIGINT NULL, new_user_id BIGINT NULL, changed_by_user_id BIGINT NULL REFERENCES users(id), reason TEXT NULL, source VARCHAR(60) NOT NULL DEFAULT 'manual', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
      `CREATE TABLE IF NOT EXISTS support_ticket_status_history (id BIGSERIAL PRIMARY KEY, ticket_id BIGINT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, previous_status VARCHAR(40) NULL, new_status VARCHAR(40) NOT NULL, changed_by_type VARCHAR(20) NOT NULL, changed_by_user_id BIGINT NULL REFERENCES users(id), student_id BIGINT NULL REFERENCES students(id), reason TEXT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
      `CREATE TABLE IF NOT EXISTS support_ticket_read_state (id BIGSERIAL PRIMARY KEY, ticket_id BIGINT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, reader_type VARCHAR(20) NOT NULL, user_id BIGINT NULL REFERENCES users(id), student_id BIGINT NULL REFERENCES students(id), last_read_message_id BIGINT NULL, read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(ticket_id, reader_type, user_id, student_id))`,
      `CREATE TABLE IF NOT EXISTS support_ticket_audit_events (id BIGSERIAL PRIMARY KEY, ticket_id BIGINT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE, action VARCHAR(80) NOT NULL, actor_type VARCHAR(20) NOT NULL, actor_user_id BIGINT NULL REFERENCES users(id), student_id BIGINT NULL REFERENCES students(id), data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
      `CREATE INDEX IF NOT EXISTS support_tickets_scope_idx ON support_tickets(status, department_id, assigned_user_id, updated_at DESC, id DESC)`,
      `CREATE INDEX IF NOT EXISTS support_tickets_student_idx ON support_tickets(student_id, updated_at DESC, id DESC)`,
      `CREATE INDEX IF NOT EXISTS support_tickets_category_idx ON support_tickets(category_id, priority, created_at DESC)`,
      `CREATE INDEX IF NOT EXISTS support_tickets_sla_idx ON support_tickets(sla_response_due_at, sla_resolution_due_at) WHERE status NOT IN ('closed','cancelled')`,
      `CREATE INDEX IF NOT EXISTS support_ticket_messages_cursor_idx ON support_ticket_messages(ticket_id, created_at, id)`,
      `CREATE INDEX IF NOT EXISTS support_ticket_read_state_reader_idx ON support_ticket_read_state(reader_type, user_id, student_id, ticket_id)`
    ];
    for (const statement of sql) await q.sequelize.query(statement, { transaction: t });
    const categories = ['LMS login / OTP','Course content / lessons','Enrollment','Fees / installments','Payment verification / OCR','Receipt problem','WhatsApp messages','Live class / Zoom','Attendance','Certificate','Technical problem','Other'];
    for (const name of categories) await q.sequelize.query(`INSERT INTO support_ticket_categories(name) VALUES (:name) ON CONFLICT(name) DO NOTHING`, { replacements: { name }, transaction: t });
    for (const code of PERMISSIONS) await q.sequelize.query(`INSERT INTO permissions(code,name,description,created_at,updated_at) VALUES (:code,:code,'Student support ticket permission',NOW(),NOW()) ON CONFLICT(code) DO NOTHING`, { replacements: { code }, transaction: t });
    await t.commit();
  } catch (error) { await t.rollback(); error.migrationOperation = '062_student_support_tickets.js'; throw error; }
};
module.exports.down = async () => {};
