import api from './api';
export const listSequences=params=>api.get('/reminder-sequences',{params});
export const getReminderDashboard=()=>api.get('/reminder-sequences/dashboard');
export const saveSequence=(id,payload)=>id?api.patch(`/reminder-sequences/${id}`,payload):api.post('/reminder-sequences',payload);
export const changeSequenceStatus=(id,status)=>api.patch(`/reminder-sequences/${id}/status`,{status});
export const duplicateSequence=id=>api.post(`/reminder-sequences/${id}/duplicate`);
export const deleteSequence=id=>api.delete(`/reminder-sequences/${id}`);
export const listSubscriptions=params=>api.get('/reminder-sequences/subscriptions',{params});
export const listExecutions=params=>api.get('/reminder-sequences/executions',{params});
export const changeSubscription=(id,action)=>api.post(`/reminder-sequences/subscriptions/${id}/${action}`);
export const retryExecution=id=>api.post(`/reminder-sequences/executions/${id}/retry`);
export const uploadReminderMedia=(file,whatsappAccountId,sequenceId)=>{const form=new FormData();form.append('file',file);form.append('whatsappAccountId',String(whatsappAccountId));if(sequenceId)form.append('sequenceId',String(sequenceId));return api.post('/reminder-sequences/media',form,{timeout:120000})};
