import api from './api';

export const getWhatsAppAccounts = (includeInactive = false) => api.get('/whatsapp-accounts', { params: includeInactive ? { includeInactive: true } : {} });
export const getWhatsAppAccount = (id) => api.get(`/whatsapp-accounts/${id}`);
export const createWhatsAppAccount = (payload) => api.post('/whatsapp-accounts', payload);
export const updateWhatsAppAccount = (id, payload) => api.patch(`/whatsapp-accounts/${id}`, payload);
export const deactivateWhatsAppAccount = (id) => api.delete(`/whatsapp-accounts/${id}`);
export const reactivateWhatsAppAccount = (id, payload = {}) => api.post(`/whatsapp-accounts/${id}/reactivate`, payload);
export const setDefaultWhatsAppAccount = (id) => api.post(`/whatsapp-accounts/${id}/set-default`);
export const testWhatsAppAccount = (id) => api.post(`/whatsapp-accounts/${id}/test-connection`);
export const checkWhatsAppWebhook = (id) => api.get(`/whatsapp-accounts/${id}/webhook-subscription`);
export const subscribeWhatsAppWebhook = (id) => api.post(`/whatsapp-accounts/${id}/webhook-subscription`);
export const overrideWhatsAppWebhook = (id) => api.post(`/whatsapp-accounts/${id}/webhook-callback-override`);
export const getWhatsAppRouting = (id) => api.get(`/whatsapp-accounts/${id}/routing`);
export const createWhatsAppRouting = (id, payload) => api.post(`/whatsapp-accounts/${id}/routing`, payload);
export const updateWhatsAppRouting = (id, ruleId, payload) => api.patch(`/whatsapp-accounts/${id}/routing/${ruleId}`, payload);
export const deleteWhatsAppRouting = (id, ruleId) => api.delete(`/whatsapp-accounts/${id}/routing/${ruleId}`);
export const getRoutingEligibleAgents = (id, search = '') => api.get(`/whatsapp-accounts/${id}/routing/eligible-agents`, { params: { search, limit: 100 } });
export const addRoutingAgent = (id, ruleId, payload) => api.post(`/whatsapp-accounts/${id}/routing/${ruleId}/agents`, payload);
export const updateRoutingAgent = (id, ruleId, agentId, payload) => api.patch(`/whatsapp-accounts/${id}/routing/${ruleId}/agents/${agentId}`, payload);
export const deleteRoutingAgent = (id, ruleId, agentId) => api.delete(`/whatsapp-accounts/${id}/routing/${ruleId}/agents/${agentId}`);
export const testWhatsAppRouting = (id, payload = {}) => api.post(`/whatsapp-accounts/${id}/routing/test`, { simulate: true, ...payload });
export const getWhatsAppRoutingAnalytics = (id) => api.get(`/whatsapp-accounts/${id}/routing/analytics`);
