const {Op}=require('sequelize');
const {AiAgent,AiConversationState,AiKnowledgeSource,AiDecisionLog,AuditLog,Conversation,Contact,Lead,Message,Course,Batch,Label,ConversationLabel,sequelize}=require('../models');
const aiService=require('./ai.service');

const fail=(message,status=422,code='AI_AGENT_INVALID')=>Object.assign(new Error(message),{status,code});
const ids=value=>[...new Set((Array.isArray(value)?value:[]).map(Number).filter(Number.isFinite))];
const states=new Set(['new_lead','greeted','asking_knowledge_level','beginner','intermediate','experienced','seminar_invited','group_link_sent','registration_interest','payment_details_sent','waiting_for_payment_slip','payment_under_review','payment_confirmed','registered_student','human_handover','closed']);
const priorities=new Set(['flow_only','ai_only','flow_first_then_ai','ai_first_then_flow','human_only']);

class AiAgentService{
 normalize(payload={}){return{...payload,name:String(payload.name||'').trim(),whatsappAccountIds:ids(payload.whatsappAccountIds),courseIds:ids(payload.courseIds),supportedLanguages:Array.isArray(payload.supportedLanguages)?payload.supportedLanguages.filter(Boolean):[],qualificationQuestions:Array.isArray(payload.qualificationQuestions)?payload.qualificationQuestions:[],prohibitedStatements:Array.isArray(payload.prohibitedStatements)?payload.prohibitedStatements:[],allowedActions:Array.isArray(payload.allowedActions)?payload.allowedActions:[]};}
 validate(values){if(!values.name)throw fail('Agent Name is required.');if(!values.whatsappAccountIds.length)throw fail('Assign at least one WhatsApp Number.');if(!priorities.has(values.automationPriority||'flow_first_then_ai'))throw fail('Choose a valid automation priority.');if(Number(values.temperature)<0||Number(values.temperature)>2)throw fail('Response creativity must be between 0 and 2.');if(Number(values.maxAiReplies)<1)throw fail('Maximum AI replies must be at least 1.');}
 async assertUniqueAccounts(values,id=null){if(values.status!=='active')return;const active=await AiAgent.findAll({where:{status:'active',...(id?{id:{[Op.ne]:id}}:{})}});const overlap=active.find(agent=>(agent.whatsappAccountIds||[]).some(accountId=>values.whatsappAccountIds.includes(Number(accountId))));if(overlap)throw fail(`WhatsApp Number is already assigned to active AI Agent “${overlap.name}”.`,409,'AI_ACCOUNT_ALREADY_ASSIGNED');}
 async list(){return AiAgent.findAll({order:[['name','ASC']]});}
 async get(id){const row=await AiAgent.findByPk(id,{include:[{model:AiKnowledgeSource,as:'knowledgeSources',required:false}]});if(!row)throw fail('AI Agent not found.',404,'NOT_FOUND');return row;}
 async save(id,payload,actor){const values=this.normalize(payload);this.validate(values);await this.assertUniqueAccounts(values,id);if(id){const row=await this.get(id);await row.update({...values,updatedBy:actor?.id});return this.get(id);}return this.get((await AiAgent.create({...values,createdBy:actor?.id,updatedBy:actor?.id})).id);}
 async remove(id){const row=await this.get(id);await row.update({status:'paused'});return{paused:true};}
 async resolve(whatsappAccountId){const rows=await AiAgent.findAll({where:{status:'active'},order:[['id','ASC']]});return rows.find(row=>(row.whatsappAccountIds||[]).map(String).includes(String(whatsappAccountId)))||null;}
 async state(conversationId,agent=null){let row=await AiConversationState.findOne({where:{conversationId},include:[{model:AiAgent,as:'agent',required:false}]});if(!row&&agent)row=await AiConversationState.create({conversationId,aiAgentId:agent.id});return row;}
 async control(conversationId,action,payload={},actor=null){const conversation=await Conversation.findByPk(conversationId);if(!conversation)throw fail('Conversation not found.',404,'NOT_FOUND');const agent=payload.aiAgentId?await this.get(payload.aiAgentId):await this.resolve(conversation.whatsappAccountId);const row=await this.state(conversationId,agent);if(!row)throw fail('No AI Agent is assigned to this WhatsApp Number.',404,'AI_AGENT_NOT_ASSIGNED');if(action==='handover'){await this.handover(row,agent||await AiAgent.findByPk(row.aiAgentId),payload.reason||'Manual handover',null);return this.state(conversationId);}const changes={};if(action==='pause')Object.assign(changes,{status:'paused',pausedUntil:payload.pausedUntil||null,pauseReason:payload.reason||'Paused by administrator'});else if(action==='resume')Object.assign(changes,{status:'active',pausedUntil:null,pauseReason:null});else if(action==='restart')Object.assign(changes,{status:'active',state:'new_lead',replyCount:0,extractedData:{},pausedUntil:null,pauseReason:null});else if(action==='change_agent')Object.assign(changes,{aiAgentId:agent.id,status:'active'});else throw fail('Unsupported AI control action.',400);const stateBefore=row.state;await row.update(changes);await this.audit({agentId:row.aiAgentId,conversationId,action:`manual_${action}`,stateBefore,stateAfter:changes.state||stateBefore,reason:changes.pauseReason,details:{actorId:actor?.id}});return this.state(conversationId);}
 async pauseForHumanReply(conversationId,userId){const row=await this.state(conversationId);if(!row)return null;const agent=row.agent||await AiAgent.findByPk(row.aiAgentId);const until=new Date(Date.now()+Number(agent?.humanPauseMinutes||60)*60000);await row.update({status:'paused',pausedUntil:until,pauseReason:'Human agent replied'});await this.audit({agentId:row.aiAgentId,conversationId,action:'human_reply_pause',stateBefore:row.state,stateAfter:row.state,details:{userId,pausedUntil:until}});return row;}
 async knowledge(agentId,query={}){const now=new Date();return AiKnowledgeSource.findAll({where:{...(agentId?{aiAgentId:agentId}:{}),...(query.status?{status:query.status}:{}),...(query.current==='true'?{status:'approved',[Op.and]:[{[Op.or]:[{validFrom:null},{validFrom:{[Op.lte]:now}}]},{[Op.or]:[{validUntil:null},{validUntil:{[Op.gte]:now}}]}]}:{})},order:[['title','ASC'],['version','DESC']]});}
 async saveKnowledge(id,payload,actor){if(!payload.title||!payload.content)throw fail('Knowledge title and content are required.');const values={...payload,createdBy:actor?.id};if(id){const row=await AiKnowledgeSource.findByPk(id);if(!row)throw fail('Knowledge source not found.',404);return sequelize.transaction(async transaction=>{await row.update({status:'archived'},{transaction});return AiKnowledgeSource.create({...row.toJSON(),...values,id:undefined,version:Number(row.version||1)+1},{transaction});});}return AiKnowledgeSource.create(values);}
 handoverReason(text,agent,state){const value=String(text||'').toLowerCase();if(/\b(human|person|agent|manager|someone real)\b/.test(value))return'Customer requested a human';if(/\b(refund|lawyer|legal|complaint|guarantee|guaranteed profit|medical)\b/.test(value))return'Sensitive or prohibited request';if(/\b(angry|furious|scam|terrible|useless)\b/.test(value))return'Customer dissatisfaction';if(Number(state.replyCount)>=Number(agent.maxAiReplies))return'Maximum automated replies reached';return null;}
 sanitize(text,agent){let value=String(text||'').replace(/```[\s\S]*?```/g,'').replace(/\b(?:sk-|Bearer\s+)[A-Za-z0-9._-]+/g,'[redacted]').trim();const prohibited=[...(agent.prohibitedStatements||[]),'guaranteed income','guaranteed profit'];for(const phrase of prohibited.filter(Boolean))value=value.replace(new RegExp(String(phrase).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'ig'),'[statement removed]');return value.slice(0,4000);}
 async grounding(agent){const now=new Date();const [knowledge,courses,batches]=await Promise.all([this.knowledge(agent.id,{current:'true'}),agent.courseIds?.length?Course.findAll({where:{id:{[Op.in]:agent.courseIds}},attributes:['id','name','code','description','feeAmount','whatsappGroupLink']}):[],agent.courseIds?.length?Batch.findAll({where:{courseId:{[Op.in]:agent.courseIds},status:'active'},attributes:['id','courseId','name','code','startDate','endDate']}):[]]);return{knowledge:knowledge.map(row=>({title:row.title,content:row.content,version:row.version})),courses,batches};}
 async persistExtracted(contact,lead,data={}){if(contact?.update){const name=String(data.customerName||data.name||'').trim().split(/\s+/);await contact.update({...(name[0]&&!contact.firstName?{firstName:name.shift(),lastName:name.join(' ')||contact.lastName}:{}),customFields:{...(contact.customFields||{}),...(data.location?{location:data.location}:{}),...(data.language?{language:data.language}:{})}});}if(lead?.update){const score=Number(data.qualificationScore);await lead.update({...(data.interestedCourse?{courseInterested:String(data.interestedCourse).slice(0,100)}:{}),...(data.preferredBatch?{batchInterested:String(data.preferredBatch).slice(0,100)}:{}),...(Number.isFinite(score)?{aiScore:Math.max(0,Math.min(100,Math.round(score)))}:{}),...(data.leadStatus?{stage:String(data.leadStatus).slice(0,100)}:{}),customFields:{...(lead.customFields||{}),...Object.fromEntries(['knowledgeLevel','previousExperience','profitLossStatus','location','language','registrationInterest','paymentReadiness','leadSource'].filter(key=>data[key]!=null).map(key=>[key,data[key]]))}});}}
 async audit({agentId,conversationId,inboundMessageId=null,action,stateBefore,stateAfter,reason=null,confidence=null,details={},durationMs=null,status='completed'}){let decision=inboundMessageId?await AiDecisionLog.findOne({where:{inboundMessageId}}):null;const values={aiAgentId:agentId,conversationId,inboundMessageId,action,stateBefore,stateAfter,reason,confidence,details,durationMs,status};decision=decision?await decision.update(values):await AiDecisionLog.create(values);await AuditLog.create({action:`ai_agent.${action}`,entityType:'conversation',entityId:String(conversationId),changes:{aiAgentId:agentId,inboundMessageId,stateBefore,stateAfter,reason,...details}}).catch(()=>null);return decision;}
 async handover(state,agent,reason,inboundMessageId){const stateBefore=state.state,[label]=await Label.findOrCreate({where:{name:'Human Handover'},defaults:{name:'Human Handover',color:'#f59e0b'}});await ConversationLabel.findOrCreate({where:{conversationId:state.conversationId,labelId:label.id}});let summary=state.summary;try{const conversation=await Conversation.findByPk(state.conversationId,{include:[{model:Contact,as:'contact',required:false},{model:Lead,as:'lead',required:false}]});const messages=await Message.findAll({where:{conversationId:state.conversationId},order:[['created_at','DESC']],limit:30});summary=await aiService.summarizeConversation({messages:messages.reverse(),contact:conversation?.contact||{},lead:conversation?.lead||{}});}catch(error){summary=summary||`Handover requested: ${reason}`;}await state.update({status:'human_handover',state:'human_handover',handoverAt:new Date(),pauseReason:reason,summary});return this.audit({agentId:agent.id,conversationId:state.conversationId,inboundMessageId,action:'human_handover',stateBefore,stateAfter:'human_handover',reason,details:{labelId:label.id}});}
 async handleInbound({conversation,contact,lead,messageRecord,text,messageType,whatsappAccountId,flowHandled=false}){if(!conversation?.id||!messageRecord?.id)return null;const started=Date.now(),agent=await this.resolve(whatsappAccountId);if(!agent)return null;const existing=await AiDecisionLog.findOne({where:{inboundMessageId:messageRecord.id}});if(existing)return existing;try{await AiDecisionLog.create({aiAgentId:agent.id,conversationId:conversation.id,inboundMessageId:messageRecord.id,action:'processing',stateBefore:null,stateAfter:null,status:'processing'});}catch(error){if(error.name==='SequelizeUniqueConstraintError'||error.parent?.code==='23505')return AiDecisionLog.findOne({where:{inboundMessageId:messageRecord.id}});throw error;}const state=await this.state(conversation.id,agent);if(state.aiAgentId!==agent.id)await state.update({aiAgentId:agent.id});if(['paused','human_handover'].includes(state.status)&&(state.status==='human_handover'||!state.pausedUntil||new Date(state.pausedUntil)>new Date()))return this.audit({agentId:agent.id,conversationId:conversation.id,inboundMessageId:messageRecord.id,action:'skipped_paused',stateBefore:state.state,stateAfter:state.state,reason:state.pauseReason});if(state.pausedUntil&&new Date(state.pausedUntil)<=new Date())await state.update({status:'active',pausedUntil:null,pauseReason:null});if(agent.automationPriority==='human_only'||agent.automationPriority==='flow_only'||(flowHandled&&agent.automationPriority==='flow_first_then_ai'))return this.audit({agentId:agent.id,conversationId:conversation.id,inboundMessageId:messageRecord.id,action:'skipped_priority',stateBefore:state.state,stateAfter:state.state,reason:agent.automationPriority});const reason=this.handoverReason(text,agent,state);if(reason)return this.handover(state,agent,reason,messageRecord.id);if(['image','document'].includes(messageType)){await state.update({state:'payment_under_review',lastInboundMessageId:messageRecord.id});return this.sendDecision({agent,state,conversation,contact,messageRecord,text:'Thanks. Your payment document is being checked by our verification team. We will update you after it is reviewed.',nextState:'payment_under_review',action:'payment_review_acknowledgement',started});}if(!agent.allowedActions.includes('send_text'))return this.audit({agentId:agent.id,conversationId:conversation.id,inboundMessageId:messageRecord.id,action:'blocked_action',stateBefore:state.state,stateAfter:state.state,reason:'send_text is not enabled'});
  const grounded=await this.grounding(agent),history=await Message.findAll({where:{conversationId:conversation.id},order:[['created_at','DESC']],limit:20,attributes:['direction','text','createdAt']});const prompt=`You are ${agent.name}, an approved WhatsApp sales/support AI. Continue state ${state.state}; never restart unless state is new_lead. Follow system instructions and scripts. Never invent fees, dates, batches, bank details, discounts, refunds, lecturers, guarantees or links. Use only GROUNDING. If unknown or sensitive, set handover=true. Return JSON only: {"reply":"...","nextState":"one allowed state","confidence":0.0,"handover":false,"handoverReason":null,"extractedData":{}}.\nSYSTEM:${agent.systemInstructions||''}\nSALES SCRIPT:${agent.salesScript||''}\nSUPPORT SCRIPT:${agent.supportScript||''}\nQUALIFICATION:${JSON.stringify(agent.qualificationQuestions||[])}\nGROUNDING:${JSON.stringify(grounded)}\nKNOWN LEAD:${JSON.stringify(state.extractedData||{})}\nHISTORY:${JSON.stringify(history.reverse())}\nCUSTOMER:${text}`;
  const raw=await aiService.createResponse(prompt,{model:agent.model,temperature:Number(agent.temperature),maxTokens:500}),decision=aiService.parseJson(raw);if(!decision?.reply||decision.handover||Number(decision.confidence||0)<.45)return this.handover(state,agent,decision?.handoverReason||'AI confidence is low or answer is not grounded',messageRecord.id);const nextState=states.has(decision.nextState)?decision.nextState:state.state;await this.persistExtracted(contact,lead,decision.extractedData||{});await state.update({extractedData:{...(state.extractedData||{}),...(decision.extractedData||{})}});return this.sendDecision({agent,state,conversation,contact,messageRecord,text:this.sanitize(decision.reply,agent),nextState,action:'send_text',confidence:Number(decision.confidence||0),started});}
 async sendDecision({agent,state,conversation,contact,messageRecord,text,nextState,action,confidence=null,started}){if(agent.responseDelaySeconds>0)await new Promise(resolve=>setTimeout(resolve,Math.min(agent.responseDelaySeconds,30)*1000));const to=contact?.whatsappId||contact?.phone;if(!to)return this.handover(state,agent,'Contact has no valid WhatsApp number',messageRecord.id);const whatsapp=require('./whatsapp.service');const response=await whatsapp.sendTextMessage({to,text,whatsappAccountId:conversation.whatsappAccountId,log:false});await Message.create({whatsappMessageId:response?.id||null,conversationId:conversation.id,contactId:conversation.contactId,whatsappAccountId:conversation.whatsappAccountId,direction:'outbound',type:'text',messageType:'ai_reply',text,toNumber:to,status:'sent',statusUpdatedAt:new Date(),rawPayload:{aiAgentId:agent.id,inReplyToMessageId:messageRecord.id}});await state.update({state:nextState,status:'active',replyCount:Number(state.replyCount||0)+1,lastInboundMessageId:messageRecord.id,lastAiReplyAt:new Date()});await conversation.update({lastMessage:text,lastMessageAt:new Date()});return this.audit({agentId:agent.id,conversationId:conversation.id,inboundMessageId:messageRecord.id,action,stateBefore:state.state,stateAfter:nextState,confidence,details:{outboundWhatsappMessageId:response?.id||null},durationMs:Date.now()-started});}
 async analytics(){const rows=await AiDecisionLog.findAll({attributes:['action','aiAgentId','conversationId','durationMs']});const conversations=new Set(rows.map(row=>String(row.conversationId))).size,handovers=rows.filter(row=>row.action==='human_handover').length,failed=rows.filter(row=>row.status==='failed').length,replies=rows.filter(row=>row.action==='send_text');return{conversationsHandled:conversations,humanHandovers:handovers,failedReplies:failed,averageResponseTimeMs:replies.length?Math.round(replies.reduce((sum,row)=>sum+Number(row.durationMs||0),0)/replies.length):0,aiResolutionRate:conversations?Math.round((conversations-handovers)/conversations*100):0};}
}
module.exports=new AiAgentService();module.exports.AiAgentService=AiAgentService;
