const {Op}=require('sequelize'),db=require('../models'),definitions=require('../constants/callCenterMetricDefinitions');
const has=(a,p)=>a?.isSystemAdmin||a?.permissions?.includes(p);
const deny=()=>{throw Object.assign(new Error('Supervisor dashboard permission is required.'),{status:403,code:'CALL_CENTER_SUPERVISOR_FORBIDDEN'});};
const answered=new Set(['answered','interested','call_back_later','follow_up_required','registered']);
const converted=new Set(['registered']);
const list=v=>Array.isArray(v)?v:String(v||'').split(',').filter(Boolean);
const person=u=>[u?.firstName,u?.lastName].filter(Boolean).join(' ')||u?.email||`Agent ${u?.id}`;
const thresholds=()=>({idleSeconds:+process.env.CALL_CENTER_IDLE_SECONDS||300,awaySeconds:+process.env.CALL_CENTER_AWAY_SECONDS||600,offlineSeconds:+process.env.CALL_CENTER_OFFLINE_SECONDS||900,staleCallSeconds:+process.env.CALL_CENTER_STALE_CALL_SECONDS||120});
function range(q={}){
 const offset=19800000,local=new Date(Date.now()+offset),y=local.getUTCFullYear(),m=local.getUTCMonth(),d=local.getUTCDate();
 let start=new Date(Date.UTC(y,m,d)-offset),end=new Date(start.getTime()+86400000);
 if(q.from||q.to)return{start:q.from?new Date(q.from):new Date(0),end:q.to?new Date(q.to):new Date(),timezone:'Asia/Colombo'};
 if(q.period==='yesterday'){end=start;start=new Date(start-86400000);}
 if(q.period==='week')start=new Date(start-((local.getUTCDay()+6)%7)*86400000);
 if(q.period==='month')start=new Date(Date.UTC(y,m,1)-offset);
 return{start,end,timezone:'Asia/Colombo'};
}
function where(q,r,active=false){const w=active?{endedAt:null}:{endedAt:{[Op.ne]:null},startedAt:{[Op.gte]:r.start,[Op.lt]:r.end}},ids=list(q.agentIds||q.agentId);if(ids.length)w.agentUserId={[Op.in]:ids};if(q.whatsappAccountId)w.whatsappAccountId=q.whatsappAccountId;return w;}
class Supervisor{
 auth(a){if(!has(a,'call_center.supervisor_dashboard'))deny();}
 async heartbeat(p,a){const now=new Date(),sessionIdentifier=String(p.sessionIdentifier||'').slice(0,180);if(!sessionIdentifier)throw Object.assign(new Error('Session identifier is required.'),{status:422});const[row]=await db.CallCenterPresenceSession.findOrCreate({where:{userId:a.id,sessionIdentifier},defaults:{currentPage:p.currentPage,lastActivityAt:now,lastHeartbeatAt:now}});await row.update({currentPage:String(p.currentPage||'').slice(0,255),lastHeartbeatAt:now,...(p.activity?{lastActivityAt:now}:{})});return{serverTime:now,thresholds:thresholds()};}
 async calls(q,a,active=false){this.auth(a);const r=range(q);return{r,calls:await db.CallActivity.findAll({where:where(q,r,active),include:[{model:db.User,as:'agent',attributes:['id','firstName','lastName','email']},...(active?[{model:db.Lead,as:'lead',include:[{model:db.Contact,as:'contact'},{model:db.LeadStatus,as:'status'}]}]:[])],order:[['startedAt','DESC']]})};}
 async liveCalls(q,a){if(!has(a,'call_center.view_live_calls'))deny();const{calls}=await this.calls(q,a,true),now=new Date(),t=thresholds(),sessions=await db.CallCenterPresenceSession.findAll({order:[['lastHeartbeatAt','DESC']]});const latest=new Map();sessions.forEach(s=>{if(!latest.has(String(s.userId)))latest.set(String(s.userId),s);});return{serverTime:now,calls:calls.map(c=>{const s=latest.get(String(c.agentUserId)),age=s?(now-s.lastHeartbeatAt)/1000:Infinity,state=age>t.staleCallSeconds?'Possibly disconnected':'In Call',phone=c.lead?.contact?.phone;return{id:c.id,agentId:c.agentUserId,agentName:person(c.agent),agentOnlineState:state,leadId:c.leadId,leadName:person(c.lead?.contact),leadPhone:has(a,'contacts.view_phone')?phone:phone?`${phone.slice(0,3)}••••${phone.slice(-2)}`:null,course:c.lead?.courseInterested,startedAt:c.startedAt,currentState:state,previousLeadStatus:c.lead?.status?.name,whatsappAccountId:c.whatsappAccountId};})};}
 async agents(q,a){if(!has(a,'call_center.view_all_agents'))deny();this.auth(a);const r=range(q),now=new Date(),t=thresholds(),[users,sessions,calls,active,queues]=await Promise.all([db.User.findAll({where:{status:'active'},attributes:['id','firstName','lastName','email']}),db.CallCenterPresenceSession.findAll({order:[['lastHeartbeatAt','DESC']]}),db.CallActivity.findAll({where:where(q,r)}),db.CallActivity.findAll({where:{endedAt:null}}),db.CallQueue.findAll({include:[{model:db.CallQueueEntry,as:'entries',where:{status:{[Op.in]:['pending','calling']}},required:false}]})]);const latest=new Map();sessions.forEach(s=>{if(!latest.has(String(s.userId)))latest.set(String(s.userId),s);});return{serverTime:now,agents:users.map(u=>{const own=calls.filter(c=>String(c.agentUserId)===String(u.id)),s=latest.get(String(u.id)),live=active.find(c=>String(c.agentUserId)===String(u.id)),hb=s?(now-s.lastHeartbeatAt)/1000:Infinity,act=s?(now-s.lastActivityAt)/1000:Infinity;let presence='Offline';if(live)presence='In Call';else if(hb<=t.awaySeconds)presence=act>t.idleSeconds?'Idle':'Available';else if(hb<=t.offlineSeconds)presence='Away';return{id:u.id,name:person(u),presence,lastActivityAt:s?.lastActivityAt,lastHeartbeatAt:s?.lastHeartbeatAt,currentCallStartedAt:live?.startedAt,callAttempts:own.length,uniqueLeadsContacted:new Set(own.map(c=>String(c.leadId))).size,answered:own.filter(c=>answered.has(c.disposition)).length,conversions:own.filter(c=>converted.has(c.disposition)).length,totalTalkTime:own.reduce((x,c)=>x+(+c.talkTimeSeconds||0),0),idleTime:s?Math.max(0,Math.floor((now-s.lastActivityAt)/1000)):0,currentQueueSize:queues.find(x=>String(x.agentUserId)===String(u.id))?.entries?.length||0};})};}
 async summary(q,a){const{r,calls}=await this.calls(q,a),agents=await this.agents(q,a),now=new Date(),leadIds=[...new Set(calls.map(c=>String(c.leadId)))],ok=calls.filter(c=>answered.has(c.disposition)),conv=leadIds.length?await db.ConversionAttribution.count({where:{leadId:{[Op.in]:leadIds},convertedAt:{[Op.gte]:r.start,[Op.lt]:r.end}},distinct:true,col:'leadId'}):0,talk=calls.reduce((x,c)=>x+(+c.talkTimeSeconds||0),0);return{serverTime:now,timezone:r.timezone,range:{from:r.start,to:r.end},metrics:{agentsOnlineNow:agents.agents.filter(x=>x.presence!=='Offline').length,agentsCurrentlyInCalls:agents.agents.filter(x=>x.presence==='In Call').length,agentsAvailable:agents.agents.filter(x=>x.presence==='Available').length,agentsIdle:agents.agents.filter(x=>x.presence==='Idle').length,totalCallAttempts:calls.length,uniqueLeadsContacted:leadIds.length,answeredCalls:ok.length,unansweredCalls:calls.length-ok.length,contactRate:calls.length?ok.length/calls.length*100:0,conversions:conv,conversionRate:leadIds.length?conv/leadIds.length*100:0,totalTalkTime:talk,averageTalkTime:ok.length?talk/ok.length:0,callsPerAgent:agents.agents.length?calls.length/agents.agents.length:0,averageIdleTime:agents.agents.length?agents.agents.reduce((x,y)=>x+y.idleTime,0)/agents.agents.length:0},definitions};}
 async outcomes(q,a){const{calls}=await this.calls(q,a),groups={};for(const c of calls){const code=converted.has(c.disposition)?'converted':answered.has(c.disposition)?'answered':c.disposition||'other',g=groups[code]||(groups[code]={code,count:0,leads:new Set(),conversions:0});g.count++;g.leads.add(String(c.leadId));if(code==='converted')g.conversions++;}return{total:calls.length,outcomes:Object.values(groups).map(g=>({code:g.code,count:g.count,percentage:calls.length?g.count/calls.length*100:0,uniqueLeads:g.leads.size,conversionContribution:g.conversions}))};}
 async history(q,a){if(!has(a,'call_center.view_all_history'))deny();const{calls}=await this.calls(q,a),page=Math.max(1,+q.page||1),limit=Math.min(100,Math.max(1,+q.limit||25));return{rows:calls.slice((page-1)*limit,page*limit),pagination:{page,limit,total:calls.length}};}
 async agent(id,q,a){if(!has(a,'call_center.view_performance'))deny();const scoped={...q,agentId:id};return{summary:await this.summary(scoped,a),history:await this.history(scoped,a),outcomes:await this.outcomes(scoped,a),activeCall:(await this.liveCalls(scoped,a)).calls[0]||null};}
}
module.exports=new Supervisor();module.exports.range=range;
