const {Op,fn,col}=require('sequelize');
const db=require('../models');
const leadService=require('./lead.service');
const callCenter=require('./callCenter.service');
const conversationAccess=require('./conversationAccess.service');
const audit=require('./audit.service');
const fail=(code,message,status=400,errors)=>Object.assign(new Error(message),{code,status,errors,exposeMessage:true});
const activeStatuses=['pending','calling','snoozed'];
const can=(actor,permission)=>actor?.isSystemAdmin||actor?.permissions?.includes(permission);
class CallQueueService{
 async queue(actor,transaction=null){const[row]=await db.CallQueue.findOrCreate({where:{agentUserId:actor.id,isDefault:true},defaults:{agentUserId:actor.id,name:'My Queue',status:'active',isDefault:true},transaction});return row;}
 async search(query,actor){
  const result=await leadService.listLeads(query,actor),ids=result.leads.map(row=>row.id);
  const calls=ids.length?await db.CallActivity.findAll({where:{leadId:{[Op.in]:ids},endedAt:{[Op.ne]:null}},order:[['started_at','DESC']],attributes:['leadId','disposition','endedAt']}):[];
  const queue=await this.queue(actor),queued=ids.length?await db.CallQueueEntry.findAll({where:{queueId:queue.id,leadId:{[Op.in]:ids},status:{[Op.in]:activeStatuses}},attributes:['leadId','status']}):[];
  const byLead=new Map(),queuedByLead=new Map(queued.map(row=>[String(row.leadId),row.status]));
  for(const call of calls){const key=String(call.leadId),value=byLead.get(key)||{attempts:0,lastResult:null,lastContactedAt:null};value.attempts++;if(!value.lastResult){value.lastResult=call.disposition;value.lastContactedAt=call.endedAt;}byLead.set(key,value);}
  const leads=await Promise.all(result.leads.map(async row=>({...row,...(byLead.get(String(row.id))||{attempts:0,lastResult:null,lastContactedAt:null}),queueState:queuedByLead.get(String(row.id))||null,conversations:await this.conversations({id:row.id,contactId:row.contact?.id},actor)})));
  return{...result,leads};
 }
 async assertEligible(leadId,actor,transaction=null,lock=false){if(lock){const locked=await db.Lead.findByPk(leadId,{attributes:['id'],transaction,lock:transaction.LOCK.UPDATE});if(!locked)throw fail('LEAD_NOT_FOUND','Lead not found.',404);}const lead=await db.Lead.findByPk(leadId,{include:[{model:db.LeadStatus,as:'status'},{model:db.Contact,as:'contact'}],transaction});if(!lead)throw fail('LEAD_NOT_FOUND','Lead not found.',404);if(lead.status?.terminal||lead.status?.countsAsConversion)throw fail('CALL_QUEUE_LEAD_INELIGIBLE','Converted or terminal leads cannot be queued.',422);if(lead.ownerId==null&&!can(actor,'leads.call_unassigned'))throw fail('CALL_QUEUE_LEAD_FORBIDDEN','Permission to call unassigned leads is required.',403);if(lead.ownerId!=null&&String(lead.ownerId)!==String(actor.id)&&!can(actor,'leads.call_others')&&!can(actor,'lead.view_all')&&!can(actor,'lead.view_team'))throw fail('CALL_QUEUE_LEAD_FORBIDDEN','You cannot queue another agent’s lead.',403);return lead;}
 async add(leadIds,actor,{source='manual',sourceFilter=null}={}){if(!can(actor,'call_queue.manage_own'))throw fail('CALL_QUEUE_FORBIDDEN','Queue management permission is required.',403);const ids=[...new Set((leadIds||[]).map(Number).filter(Number.isInteger))];if(!ids.length)throw fail('VALIDATION_FAILED','Select at least one lead.',422,{leadIds:'Select at least one lead.'});if(ids.length>100)throw fail('CALL_QUEUE_BULK_LIMIT','A maximum of 100 leads can be added at once.',422);return db.sequelize.transaction(async transaction=>{const queue=await this.queue(actor,transaction),max=await db.CallQueueEntry.max('position',{where:{queueId:queue.id},transaction})||0;let added=0,alreadyInQueue=0,rejected=0;const rejectedLeadIds=[];for(let index=0;index<ids.length;index++){try{await this.assertEligible(ids[index],actor,transaction);const[,created]=await db.CallQueueEntry.findOrCreate({where:{queueId:queue.id,leadId:ids[index],status:{[Op.in]:activeStatuses}},defaults:{queueId:queue.id,leadId:ids[index],position:Number(max)+index+1,priority:0,status:'pending',source,sourceFilter,addedByUserId:actor.id,addedAt:new Date()},transaction});if(created)added++;else alreadyInQueue++;}catch(error){if(error.status>=400&&error.status<500){rejected++;rejectedLeadIds.push(ids[index]);continue;}throw error;}}return{added,alreadyInQueue,rejected,rejectedLeadIds,queueId:queue.id};});}
 async addMatching(filters,actor){if(!can(actor,'call_queue.bulk_add'))throw fail('CALL_QUEUE_FORBIDDEN','Bulk queue permission is required.',403);const result=await leadService.listLeads({...filters,page:1,limit:100},actor);if(result.pagination.total>100)throw fail('CALL_QUEUE_BULK_LIMIT','Refine the filters to 100 matching leads or fewer.',422);return this.add(result.leads.map(row=>row.id),actor,{source:'filtered_bulk',sourceFilter:filters});}
 async list(actor){if(!can(actor,'call_queue.view_own'))throw fail('CALL_QUEUE_FORBIDDEN','Queue view permission is required.',403);const queue=await this.queue(actor),entries=await db.CallQueueEntry.findAll({where:{queueId:queue.id,status:{[Op.in]:activeStatuses}},include:[{model:db.Lead,as:'lead',include:[{model:db.Contact,as:'contact'},{model:db.LeadStatus,as:'status'},{model:db.LeadSource,as:'source'},{model:db.User,as:'owner',attributes:['id','firstName','lastName']}]}],order:[['priority','DESC'],['position','ASC']]});return{queue,entries:await Promise.all(entries.map(row=>this.publicEntry(row,actor)))};}
 async conversations(lead,actor){const rows=await db.Conversation.findAll({where:{[Op.or]:[{leadId:lead.id},{leadId:null,contactId:lead.contactId}]},include:[{model:db.WhatsAppAccount,as:'whatsappAccount',attributes:['id','name','phoneNumber']},{model:db.User,as:'assignedUser',attributes:['id','firstName','lastName']}],order:[['last_message_at','DESC']]});const allowed=[];for(const row of rows){try{await conversationAccess.assertConversationAccess(row.id,actor.id);allowed.push(row);}catch(error){if(error.status!==403)throw error;}}return allowed.map(row=>({id:row.id,status:row.status,whatsappAccountId:row.whatsappAccountId,whatsappAccount:row.whatsappAccount?{id:row.whatsappAccount.id,name:row.whatsappAccount.name,phoneNumber:row.whatsappAccount.phoneNumber}:null,assignedAgent:row.assignedUser?{id:row.assignedUser.id,name:[row.assignedUser.firstName,row.assignedUser.lastName].filter(Boolean).join(' ')}:null,lastMessageAt:row.lastMessageAt,lastMessagePreview:String(row.lastMessage||'').slice(0,120)}));}
 async publicEntry(row,actor){const value=row.toJSON(),lead=row.lead,calls=await db.CallActivity.findAll({where:{leadId:row.leadId,endedAt:{[Op.ne]:null}},order:[['started_at','DESC']],attributes:['disposition','endedAt'],limit:50}),conversations=lead?await this.conversations(lead,actor):[];value.metrics={attempts:calls.length,lastResult:calls[0]?.disposition||null,lastContactedAt:calls[0]?.endedAt||null};value.conversations=conversations;return value;}
 async update(id,input,actor){const queue=await this.queue(actor),row=await db.CallQueueEntry.findOne({where:{id,queueId:queue.id,status:{[Op.in]:activeStatuses}}});if(!row)throw fail('CALL_QUEUE_ENTRY_NOT_FOUND','Queue entry not found.',404);const allowed={};if(['pending','skipped','snoozed','removed'].includes(input.status))allowed.status=input.status;if(input.priority!==undefined)allowed.priority=Math.max(-100,Math.min(100,Number(input.priority)||0));if(input.skipReason!==undefined)allowed.skipReason=String(input.skipReason||'').trim().slice(0,1000)||null;if(input.snoozedUntil!==undefined)allowed.snoozedUntil=input.snoozedUntil?new Date(input.snoozedUntil):null;if(allowed.status==='removed')allowed.completedAt=new Date();await row.update(allowed);await audit.record({userId:actor.id,action:'CALL_QUEUE_ENTRY_UPDATED',entityType:'call_queue_entry',entityId:id,changes:{fields:Object.keys(allowed)},required:true});return row;}
 async claimNext(actor,requestContext={},entryId=null){if(!can(actor,'call_queue.manage_own'))throw fail('CALL_QUEUE_FORBIDDEN','Queue management permission is required.',403);return db.sequelize.transaction(async transaction=>{const queue=await this.queue(actor,transaction),entry=await db.CallQueueEntry.findOne({where:{queueId:queue.id,...(entryId?{id:entryId}:{}),[Op.or]:[{status:'pending'},{status:'snoozed',snoozedUntil:{[Op.lte]:new Date()}}]},order:[['priority','DESC'],['position','ASC']],transaction,lock:transaction.LOCK.UPDATE,skipLocked:true});if(!entry)throw fail(entryId?'CALL_QUEUE_ENTRY_NOT_FOUND':'CALL_QUEUE_EMPTY',entryId?'Queue entry is no longer eligible.':'No eligible queue leads are ready.',entryId?404:409);await this.assertEligible(entry.leadId,actor,transaction,true);const call=await callCenter.start({leadId:entry.leadId,method:'manual',idempotencyKey:`queue-entry:${entry.id}:v${entry.version}`},actor,requestContext,transaction);await entry.update({status:'calling',claimedAt:new Date(),lastCallActivityId:call.id},{transaction});return{entry,call};});}
}
module.exports=new CallQueueService();
