const { Op }=require('sequelize');
const { sequelize,CommissionLedger,CommissionPayout,CommissionPayoutLedgerItem,CommissionApproval }=require('../models');
const decimal=require('../utils/decimal');const colombo=require('../utils/colomboTime');const accounting=require('./commissionAccountingSync.service');
const can=(actor,p)=>actor?.isSystemAdmin||actor?.permissions?.includes(p)||({ 'commission.payout_create':'commission.create_payout','commission.payout_approve':'commission.approve_payout','commission.payout_mark_paid':'commission.mark_paid'}[p]&&actor?.permissions?.includes({'commission.payout_create':'commission.create_payout','commission.payout_approve':'commission.approve_payout','commission.payout_mark_paid':'commission.mark_paid'}[p]));
const fail=(m,s=422,c='PAYOUT_ERROR')=>Object.assign(new Error(m),{status:s,code:c});
class CommissionPayoutService{
 async number(type,transaction){await sequelize.query("SELECT pg_advisory_xact_lock(hashtext('commission-payout-number'))",{transaction});const year=colombo.year();const prefix=type==='lecturer'?'LCP':'AGP';const [rows]=await sequelize.query(`SELECT payout_number FROM commission_payouts WHERE payout_number LIKE :prefix ORDER BY payout_number DESC LIMIT 1`,{replacements:{prefix:`${prefix}-${year}-%`},transaction});const last=Number(rows[0]?.payout_number?.split('-').pop()||0)+1;return`${prefix}-${year}-${String(last).padStart(6,'0')}`;}
 async create(payload,actor){if(!can(actor,'commission.payout_create'))throw fail('Payout creation permission required.',403);if(!payload.beneficiaryType||!payload.beneficiaryId)throw fail('Beneficiary is required.');return sequelize.transaction(async transaction=>{
  const where={beneficiaryType:payload.beneficiaryType,beneficiaryId:payload.beneficiaryId,status:'payable',payoutId:null,...(payload.ledgerIds?.length?{id:{[Op.in]:payload.ledgerIds}}:{})};
  const rows=await CommissionLedger.findAll({where,transaction,lock:transaction.LOCK.UPDATE});if(!rows.length)throw fail('No payable ledger entries were found.',409,'NO_PAYABLE_ENTRIES');
  const gross=decimal.add(...rows.map(r=>r.amount));const adjustments=decimal.format(decimal.parse(payload.adjustments||0));const deductions=decimal.format(decimal.parse(payload.deductions||0));const net=decimal.subtract(decimal.add(gross,adjustments),deductions);if(decimal.compare(net,0)<0)throw fail('Net payable cannot be negative.');
  const payout=await CommissionPayout.create({payoutNumber:await this.number(payload.beneficiaryType,transaction),beneficiaryType:payload.beneficiaryType,beneficiaryId:payload.beneficiaryId,periodStart:payload.periodStart||null,periodEnd:payload.periodEnd||null,grossEarnings:gross,adjustments,deductions,netPayable:net,notes:payload.notes,createdByUserId:actor.id},{transaction});
  for(const row of rows){await CommissionPayoutLedgerItem.create({payoutId:payout.id,ledgerId:row.id,allocatedAmount:row.amount},{transaction});await row.update({payoutId:payout.id},{transaction});}return payout;});}
 async approve(id,actor){if(!can(actor,'commission.payout_approve'))throw fail('Payout approval permission required.',403);return sequelize.transaction(async transaction=>{const p=await CommissionPayout.findByPk(id,{transaction,lock:transaction.LOCK.UPDATE});if(!p||p.status!=='draft')throw fail('Only a draft payout can be approved.',409);if(String(p.createdByUserId)===String(actor.id)&&!actor.isSystemAdmin)throw fail('Users cannot approve their own payout.',403);await p.update({status:'approved',approvedByUserId:actor.id},{transaction});await CommissionApproval.create({payoutId:p.id,approverUserId:actor.id,approverRole:actor.role||null,action:'approve',beforeStatus:'draft',afterStatus:'approved'},{transaction});return p;});}
 async pay(id,payload,actor){if(!can(actor,'commission.payout_mark_paid'))throw fail('Mark-paid permission required.',403);return sequelize.transaction(async transaction=>{const p=await CommissionPayout.findByPk(id,{transaction,lock:transaction.LOCK.UPDATE});if(!p||!['approved','processing','partially_paid'].includes(p.status))throw fail('Payout is not payable.',409);
  const amount=decimal.format(decimal.parse(payload.amount||decimal.subtract(p.netPayable,p.actualPaid)));const next=decimal.add(p.actualPaid,amount);if(decimal.compare(amount,0)<=0||decimal.compare(next,p.netPayable)>0)throw fail('Payment amount exceeds the remaining payable balance.');const status=decimal.compare(next,p.netPayable)===0?'paid':'partially_paid';await p.update({actualPaid:next,status,paymentMethod:payload.paymentMethod||p.paymentMethod||'other',bankReference:payload.bankReference||p.bankReference,paidDate:payload.paidDate||colombo.date()},{transaction});
  await CommissionLedger.update({status:status==='paid'?'paid':'partially_paid'},{where:{payoutId:p.id},transaction});
  const items=await CommissionPayoutLedgerItem.findAll({where:{payoutId:p.id},transaction});for(const item of items)await sequelize.query(`UPDATE commission_payables SET outstanding_amount=CASE WHEN :status='paid' THEN 0 ELSE ROUND(GREATEST(original_amount-(CAST(:paid AS NUMERIC)/CAST(:net AS NUMERIC)*original_amount),0),2) END,status=:status,updated_at=NOW() WHERE ledger_id=:ledgerId`,{replacements:{status,ledgerId:item.ledgerId,paid:next,net:p.netPayable},transaction});
  await accounting.recordPayout(p,actor,transaction);await CommissionApproval.create({payoutId:p.id,approverUserId:actor.id,approverRole:actor.role||null,action:'mark_paid',beforeStatus:p._previousDataValues.status,afterStatus:status,comment:payload.bankReference||null},{transaction});return p;});}
 async cancel(id,actor){if(!can(actor,'commission.payout_approve'))throw fail('Payout approval permission required.',403);return sequelize.transaction(async transaction=>{const p=await CommissionPayout.findByPk(id,{transaction,lock:transaction.LOCK.UPDATE});if(!p||!['draft','submitted','approved'].includes(p.status)||decimal.compare(p.actualPaid,0)>0)throw fail('Paid payouts cannot be cancelled.',409);await CommissionLedger.update({payoutId:null},{where:{payoutId:p.id},transaction});await CommissionPayoutLedgerItem.update({active:false},{where:{payoutId:p.id},transaction});await p.update({status:'cancelled'},{transaction});return p;});}
 async list(query={}){const page=Math.max(Number(query.page)||1,1),limit=Math.min(Number(query.limit)||25,100);const result=await CommissionPayout.findAndCountAll({where:{...(query.status?{status:query.status}:{}),...(query.beneficiaryType?{beneficiaryType:query.beneficiaryType}:{})},include:[{model:CommissionPayoutLedgerItem,as:'items',include:[{model:CommissionLedger,as:'ledger'}]}],order:[['created_at','DESC']],limit,offset:(page-1)*limit,distinct:true});return{rows:result.rows,total:result.count,page,limit};}
}
module.exports=new CommissionPayoutService();
