const { Op } = require('sequelize');
const { sequelize, CommissionRule, CommissionTier, AgentCommission, CommissionAdjustment, CommissionPayoutBatch, CommissionPayoutItem, FeeInstallment, StudentFee, Student, Conversation, User, Role } = require('../models');
const audit = require('./audit.service');
const money = (v) => Math.round(Number(v || 0) * 100) / 100;
const err = (code,message,status=400)=>Object.assign(new Error(message),{code,status});
const can=(actor,p)=>actor?.isSystemAdmin||actor?.permissions?.includes(p);
class CommissionService {
 async resolveRule({agentUserId,courseId,date=new Date(),transaction}) {
  const user=await User.findByPk(agentUserId,{include:[{model:Role,as:'roles',attributes:['id']}],transaction}); const departments=(user?.roles||[]).map(r=>r.id);
  const rules=await CommissionRule.findAll({where:{active:true,effectiveFrom:{[Op.lte]:date},[Op.or]:[{effectiveTo:null},{effectiveTo:{[Op.gte]:date}}]},include:[{model:CommissionTier,as:'tiers',required:false}],order:[['priority','DESC'],['id','DESC']],transaction});
  const match=(scope)=>rules.find(r=>r.scopeType===scope&&(!r.agentUserId||String(r.agentUserId)===String(agentUserId))&&(!r.courseId||String(r.courseId)===String(courseId))&&(!r.departmentId||departments.map(String).includes(String(r.departmentId))));
  return match('agent_course')||match('agent')||match('department_course')||match('department')||match('course')||match('global')||null;
 }
 async generateForInstallment(installmentId,{transaction:outer}={}) { const run=async(transaction)=>{
  const row=await FeeInstallment.findByPk(installmentId,{include:[{model:StudentFee,as:'fee'}],transaction,lock:transaction.LOCK.UPDATE});
  if(!row||!['confirmed','paid'].includes(row.status)||money(row.paidAmount)<=0) throw err('PAYMENT_NOT_CONFIRMED','Payment is not confirmed.',409);
  const existing=await AgentCommission.findOne({where:{installmentId},transaction,lock:transaction.LOCK.UPDATE}); if(existing)return existing;
  const agentId=row.creditedToUserId; if(!agentId) throw err('COMMISSION_NOT_ELIGIBLE','Payment has no credited agent.',422);
  const fee=row.fee, student=await Student.findByPk(fee.studentId,{transaction}); const conversation=student?await Conversation.findOne({where:{contactId:student.contactId},order:[['updated_at','DESC']],transaction}):null;
  const rule=await this.resolveRule({agentUserId:agentId,courseId:fee.courseId,date:row.confirmedAt||new Date(),transaction}); const eligible=money(row.paidAmount);
  let type='none',rate=null,amount=0,tier=null,status='held';
  if(rule&&eligible>=money(rule.minimumPaymentAmount)){type=rule.commissionType;status='pending'; if(type==='percentage'){rate=Number(rule.percentageRate);amount=money(eligible*rate/100);} else if(type==='fixed'){amount=money(rule.fixedAmount);} else {const count=await AgentCommission.count({where:{agentUserId:agentId,createdAt:{[Op.gte]:new Date(new Date().getFullYear(),new Date().getMonth(),1)}},transaction});tier=(rule.tiers||[]).find(t=>count+1>=t.minimumCount&&(!t.maximumCount||count+1<=t.maximumCount));if(tier){rate=tier.percentageRate==null?null:Number(tier.percentageRate);amount=rate==null?money(tier.fixedAmount):money(eligible*rate/100);}else status='held';}
   const prior=money(await AgentCommission.sum('commissionAmount',{where:{agentUserId:agentId,enrollmentId:fee.enrollmentId,commissionRuleId:rule.id,reversedCommissionId:null},transaction}));
   let courseCap=(type==='fixed'||(type==='tiered'&&rate==null))?money(rule.fixedAmount||tier?.fixedAmount):money(Number(fee.totalAmount||0)*Number(rate||0)/100);
   if(rule.maximumCommissionAmount!=null)courseCap=Math.min(courseCap,money(rule.maximumCommissionAmount));amount=Math.max(0,Math.min(amount,money(courseCap-prior)));}
  const created=await AgentCommission.create({agentUserId:agentId,paymentId:row.accountingTransactionId,installmentId:row.id,studentId:fee.studentId,enrollmentId:fee.enrollmentId,courseId:fee.courseId,conversationId:conversation?.id||null,leadId:student?.leadId||null,commissionRuleId:rule?.id||null,grossPaymentAmount:eligible,eligibleAmount:eligible,commissionType:type,commissionRate:rate,commissionAmount:amount,status,attributionSource:row.attributionSource==='manual_override'?'manual_override':'payment_credit_owner',calculatedAt:new Date(),notes:rule?null:'NO_COMMISSION_RULE',rawCalculation:{rule:rule?.toJSON()||null,tier:tier?.toJSON?.()||null,eligibleAmount:eligible,paymentStatus:row.status,creditedToUserId:agentId,calculatedAt:new Date().toISOString()}},{transaction});
  await audit.record({action:'COMMISSION_GENERATED',entityType:'agent_commission',entityId:created.id,changes:{agentUserId:agentId,paymentId:row.accountingTransactionId,installmentId:row.id,amount,status,ruleId:rule?.id||null}}); return created;
 }; return outer?run(outer):sequelize.transaction(run); }
 async reverseForInstallment(installmentId,reason='Payment reversed'){return sequelize.transaction(async transaction=>{const original=await AgentCommission.findOne({where:{installmentId,reversedCommissionId:null},transaction,lock:transaction.LOCK.UPDATE});if(!original||original.status==='reversed')return null;const reversal=await AgentCommission.create({agentUserId:original.agentUserId,paymentId:original.paymentId,installmentId:null,studentId:original.studentId,enrollmentId:original.enrollmentId,courseId:original.courseId,conversationId:original.conversationId,leadId:original.leadId,commissionRuleId:original.commissionRuleId,grossPaymentAmount:-Math.abs(Number(original.grossPaymentAmount)),eligibleAmount:-Math.abs(Number(original.eligibleAmount)),commissionType:original.commissionType,commissionRate:original.commissionRate,commissionAmount:-Math.abs(Number(original.commissionAmount)),status:'reversed',attributionSource:original.attributionSource,calculatedAt:new Date(),overrideReason:reason,reversedCommissionId:original.id,rawCalculation:{reversalOf:original.id,reason}},{transaction});await original.update({status:'reversed'},{transaction});await audit.record({action:'COMMISSION_REVERSED',entityType:'agent_commission',entityId:reversal.id,changes:{originalCommissionId:original.id,amount:reversal.commissionAmount,reason}});return reversal;});}
 scope(actor,where={}){if(can(actor,'commission.view_all'))return where;if(can(actor,'commission.view_team'))return where;return{...where,agentUserId:actor.id};}
 async dashboard(actor,q={}){const where=this.scope(actor,{});const rows=await AgentCommission.findAll({where});const sum=s=>money(rows.filter(r=>s.includes(r.status)).reduce((a,r)=>a+Number(r.commissionAmount),0));return{pending:sum(['pending']),approved:sum(['approved']),payable:sum(['payable']),paid:sum(['paid']),heldCancelled:sum(['held','cancelled']),totalEarned:sum(['pending','approved','payable','paid']),registrations:new Set(rows.map(r=>r.studentId).filter(Boolean)).size,payments:new Set(rows.map(r=>r.installmentId).filter(Boolean)).size,average:rows.length?money(rows.reduce((a,r)=>a+Number(r.commissionAmount),0)/rows.length):0};}
 async list(actor,q={}){const where={};if(q.status)where.status=q.status;if(q.agentUserId)where.agentUserId=q.agentUserId;return AgentCommission.findAll({where:this.scope(actor,where),include:[{model:User,as:'agent',attributes:['id','firstName','lastName','email']},{model:Student,as:'student',attributes:['id','name','studentNo']},{model:CommissionRule,as:'rule'},{model:require('../models').Course,as:'course'}],order:[['created_at','DESC']]});}
 async listRules(){return CommissionRule.findAll({include:[{model:CommissionTier,as:'tiers'}],order:[['priority','DESC']]});}
 async saveRule(id,p,actor){if(!can(actor,'commission.manage_rules'))throw err('COMMISSION_OVERRIDE_FORBIDDEN','Rule management permission required.',403);if(!p.name||!p.scopeType||!p.commissionType)throw err('INVALID_COMMISSION_RULE','Name, scope and type are required.',422);const row=id?await CommissionRule.findByPk(id):null;const saved=row?await row.update({...p,createdByUserId:row.createdByUserId}):await CommissionRule.create({...p,createdByUserId:actor.id});if(Array.isArray(p.tiers)){await CommissionTier.destroy({where:{commissionRuleId:saved.id}});await CommissionTier.bulkCreate(p.tiers.map(t=>({...t,commissionRuleId:saved.id})));}await audit.record({userId:actor.id,action:id?'COMMISSION_RULE_UPDATED':'COMMISSION_RULE_CREATED',entityType:'commission_rule',entityId:saved.id,changes:p});return saved;}
 async action(id,action,p,actor){const row=await AgentCommission.findByPk(id);if(!row)throw err('COMMISSION_NOT_ELIGIBLE','Commission not found.',404);if(row.status==='paid')throw err('COMMISSION_ALREADY_PAID','Paid commission is immutable.',409);const reason=String(p.reason||'').trim();if(['hold','cancel','reverse','override'].includes(action)&&!reason)throw err('COMMISSION_REASON_REQUIRED','Reason is required.',422);if(action==='approve'&&!can(actor,'commission.approve'))throw err('COMMISSION_OVERRIDE_FORBIDDEN','Approval permission required.',403);if(action!=='approve'&&!can(actor,action==='reverse'?'commission.reverse':'commission.override'))throw err('COMMISSION_OVERRIDE_FORBIDDEN','Commission override permission required.',403);const old=row.toJSON();if(action==='approve')await row.update({status:'payable',approvedByUserId:actor.id,approvedAt:new Date()});if(action==='hold')await row.update({status:'held',overrideReason:reason});if(action==='cancel')await row.update({status:'cancelled',overrideReason:reason});if(action==='override')await row.update({agentUserId:p.agentUserId||row.agentUserId,commissionRate:p.commissionRate??row.commissionRate,commissionAmount:p.commissionAmount??row.commissionAmount,overrideReason:reason});if(action==='reverse'){const reversal=await AgentCommission.create({...old,id:undefined,installmentId:null,commissionAmount:-Math.abs(Number(row.commissionAmount)),status:'reversed',reversedCommissionId:row.id,overrideReason:reason,calculatedAt:new Date(),createdAt:undefined,updatedAt:undefined});await row.update({status:'reversed'});return reversal;}await audit.record({userId:actor.id,action:`COMMISSION_${action.toUpperCase()}${action==='approve'?'D':''}`,entityType:'agent_commission',entityId:id,changes:{old,new:row.toJSON(),reason}});return row;}
 async createPayout(p,actor){if(!can(actor,'commission.create_payout'))throw err('COMMISSION_OVERRIDE_FORBIDDEN','Payout permission required.',403);return sequelize.transaction(async t=>{const rows=await AgentCommission.findAll({where:{status:'payable',createdAt:{[Op.between]:[new Date(p.periodStart),new Date(`${p.periodEnd}T23:59:59`)]},paymentBatchId:null},transaction:t,lock:t.LOCK.UPDATE});const batch=await CommissionPayoutBatch.create({batchNumber:`COM-${Date.now()}`,periodStart:p.periodStart,periodEnd:p.periodEnd,totalAmount:money(rows.reduce((a,r)=>a+Number(r.commissionAmount),0)),createdByUserId:actor.id,notes:p.notes},{transaction:t});for(const r of rows){await CommissionPayoutItem.create({payoutBatchId:batch.id,agentCommissionId:r.id,agentUserId:r.agentUserId,amount:r.commissionAmount,status:'included'},{transaction:t});await r.update({paymentBatchId:batch.id},{transaction:t});}await audit.record({userId:actor.id,action:'COMMISSION_PAYOUT_CREATED',entityType:'commission_payout_batch',entityId:batch.id,changes:{count:rows.length,total:batch.totalAmount}});return batch;});}
 async payoutAction(id,action,p,actor){const b=await CommissionPayoutBatch.findByPk(id);if(!b)throw err('PAYOUT_ALREADY_PROCESSED','Payout not found.',404);if(action==='approve'){if(!can(actor,'commission.approve_payout'))throw err('COMMISSION_OVERRIDE_FORBIDDEN','Permission required.',403);if(b.status!=='draft')throw err('PAYOUT_ALREADY_PROCESSED','Payout already processed.',409);await b.update({status:'approved',approvedByUserId:actor.id});}else{if(!can(actor,'commission.mark_paid'))throw err('COMMISSION_OVERRIDE_FORBIDDEN','Permission required.',403);if(b.status!=='approved')throw err('PAYOUT_ALREADY_PROCESSED','Payout is not approved.',409);await sequelize.transaction(async t=>{await b.update({status:'paid',paidByUserId:actor.id,paidAt:new Date(),paymentReference:p.paymentReference},{transaction:t});await AgentCommission.update({status:'paid',paidByUserId:actor.id,paidAt:new Date()},{where:{paymentBatchId:b.id},transaction:t});});}await audit.record({userId:actor.id,action:action==='approve'?'COMMISSION_PAYOUT_APPROVED':'COMMISSION_PAID',entityType:'commission_payout_batch',entityId:id,changes:p});return b;}
 async listPayouts(){return CommissionPayoutBatch.findAll({include:[{model:CommissionPayoutItem,as:'items'}],order:[['created_at','DESC']]});}
}
module.exports=new CommissionService();
