const router=require('express').Router();
const auth=require('../middleware/auth.middleware');
const controller=require('../controllers/commission.controller');
router.use(auth.authenticate);
router.get('/dashboard',controller.dashboard);
router.get('/transactions',controller.list);
router.get('/ledger',controller.list);
router.get('/rules',controller.rules);
router.get('/options/:type',controller.options);
router.post('/rules/test',controller.preview);
router.post('/preview',controller.preview);
router.post('/rules',controller.createRule);
router.patch('/rules/:id',controller.updateRule);
router.get('/lecturer-agreements',controller.agreements);
router.post('/lecturer-agreements',controller.createAgreement);
router.patch('/lecturer-agreements/:id',controller.updateAgreement);
router.post('/transactions/bulk-approval',controller.bulkApproval);
router.post('/adjustments',controller.adjustment);
router.post('/transactions/:id/:action',controller.action);
router.get('/payouts',controller.payouts);
router.post('/payouts',controller.createPayout);
router.post('/payouts/:id/:action',controller.payoutAction);
router.get('/profitability',controller.profitability);
router.get('/reports/:name/export',controller.export);
router.get('/reports/:name',controller.report);
router.get('/reconciliation',controller.reconciliation);
module.exports=router;
