const express = require('express');
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const roleRoutes = require('./role.routes');
const permissionRoutes = require('./permission.routes');
const webhookRoutes = require('./webhook.routes');
const autoReplyRoutes = require('./autoReply.routes');
const chatRoutes = require('./chat.routes');
const aiRoutes = require('./ai.routes');
const dashboardRoutes = require('./dashboard.routes');
const contactRoutes = require('./contact.routes');
const leadRoutes = require('./lead.routes');
const agentRoutes = require('./agent.routes');
const conversationRoutes = require('./conversation.routes');
const mediaRoutes = require('./media.routes');
const noteRoutes = require('./note.routes');
const labelRoutes = require('./label.routes');
const templateRoutes = require('./template.routes');
const campaignRoutes = require('./campaign.routes');
const workflowRoutes = require('./workflow.routes');
const flowRoutes = require('./flow.routes');
const googleSheetsRoutes = require('./googleSheets.routes');
const appointmentRoutes = require('./appointment.routes');
const educationRoutes = require('./education.routes');
const productionRoutes = require('./production.routes');
const whatsappRoutes = require('./whatsapp.routes');
const feeReminderRoutes = require('./feeReminder.routes');
const classReminderRoutes = require('./classReminder.routes');
const whatsappTemplateRoutes = require('./whatsappTemplate.routes');
const complianceRoutes = require('./compliance.routes');
const automationRoutes = require('./automation.routes');
const attendanceAlertRoutes = require('./attendanceAlert.routes');
const birthdayWishRoutes = require('./birthdayWish.routes');
const messageRoutes = require('./message.routes');
const whatsappAccountRoutes = require('./whatsappAccount.routes');
const accountingRoutes = require('./accounting.routes');
const notificationTemplateRoutes = require('./notificationTemplate.routes');
const lmsRoutes = require('./lms.routes');
const studentPortalRoutes = require('./studentPortal.routes');
const studentMessageTemplateRoutes = require('./studentMessageTemplate.routes');
const courseSchedulerRoutes = require('./courseScheduler.routes');
const commissionRoutes = require('./commission.routes');
const paymentSlipRoutes = require('./paymentSlip.routes');
const paymentReceiptRoutes = require('./paymentReceipt.routes');
const pipelineRoutes=require('./pipeline.routes'),followupRoutes=require('./followup.routes'),lostReasonRoutes=require('./lostReason.routes');

const router = express.Router();

router.get('/health', (req, res) => {
  return res.status(200).json({ success: true, message: 'API is healthy' });
});

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/auto-replies', autoReplyRoutes);
router.use('/chat', chatRoutes);
router.use('/ai', aiRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/contacts', contactRoutes);
router.use('/leads', leadRoutes);
router.use('/agents', agentRoutes);
router.use('/conversations', conversationRoutes);
router.use('/media', mediaRoutes);
router.use('/notes', noteRoutes);
router.use('/labels', labelRoutes);
router.use('/templates', templateRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/workflows', workflowRoutes);
router.use('/flows', flowRoutes);
router.use('/google-sheets', googleSheetsRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/whatsapp-accounts', whatsappAccountRoutes);
router.use('/accounting', accountingRoutes);
router.use('/commissions', commissionRoutes);
router.use('/payment-slips', paymentSlipRoutes);
router.use('/receipts', paymentReceiptRoutes);
router.use('/pipeline',pipelineRoutes);router.use('/followups',followupRoutes);router.use('/lost-reasons',lostReasonRoutes);
router.use('/notification-templates', notificationTemplateRoutes);
router.use('/lms/student', studentPortalRoutes);
router.use('/lms', lmsRoutes);
router.use('/student-portal', studentPortalRoutes);
router.use('/student-message-templates', studentMessageTemplateRoutes);
router.use('/', courseSchedulerRoutes);
router.use('/fee-reminders', feeReminderRoutes);
router.use('/class-reminders', classReminderRoutes);
router.use('/whatsapp-templates', whatsappTemplateRoutes);
router.use('/compliance', complianceRoutes);
router.use('/automations', automationRoutes);
router.use('/attendance-alerts', attendanceAlertRoutes);
router.use('/birthday-wishes', birthdayWishRoutes);
router.use('/messages', messageRoutes);
router.use('/', productionRoutes);
router.use('/', educationRoutes);

module.exports = router;
