const express = require('express');
const controller = require('../controllers/lms.controller');
const auth = require('../middleware/auth.middleware');
const permit = require('../middleware/permission.middleware');

const router = express.Router();
router.use(auth.authenticate);
router.get('/courses', permit('lms.course.view'), controller.listCourses);
router.post('/courses', permit('lms.course.create'), controller.createCourse);
router.get('/courses/:courseId', permit('lms.course.view'), controller.getCourse);
router.patch('/courses/:courseId', permit('lms.course.update'), controller.updateCourse);
router.delete('/courses/:courseId', permit('lms.course.archive'), controller.archiveCourse);
router.post('/courses/:courseId/duplicate', permit('lms.course.create'), controller.duplicateCourse);
router.get('/courses/:courseId/curriculum', permit('lms.course.view'), controller.curriculum);
router.post('/courses/:courseId/topics', permit('lms.topic.manage'), controller.createTopic);
router.patch('/topics/:topicId', permit('lms.topic.manage'), controller.updateTopic);
router.delete('/topics/:topicId', permit('lms.topic.manage'), controller.deleteTopic);
router.post('/topics/:topicId/duplicate', permit('lms.topic.manage'), controller.duplicateTopic);
router.post('/topics/reorder', permit('lms.curriculum.manage'), controller.reorderTopics);
router.post('/topics/:topicId/lessons', permit('lms.lesson.create'), controller.createTopicLesson);
router.get('/builder-lessons/:lessonId', permit('lms.lesson.view'), controller.getBuilderLesson);
router.patch('/builder-lessons/:lessonId', permit('lms.lesson.update'), controller.updateBuilderLesson);
router.delete('/builder-lessons/:lessonId', permit('lms.lesson.archive'), controller.deleteBuilderLesson);
router.post('/builder-lessons/:lessonId/duplicate', permit('lms.lesson.create'), controller.duplicateLesson);
router.post('/builder-lessons/:lessonId/move', permit('lms.curriculum.manage'), controller.moveLesson);
router.post('/builder-lessons/reorder', permit('lms.curriculum.manage'), controller.reorderLessons);
router.post('/lessons/reorder', permit('lms.curriculum.manage'), controller.reorderLessons);
router.post('/lessons/:lessonId/move', permit('lms.curriculum.manage'), controller.moveLesson);
router.post('/lessons/:lessonId/duplicate', permit('lms.lesson.create'), controller.duplicateLesson);
router.get('/lessons', permit('courses.view'), controller.list);
router.post('/lessons', permit('courses.edit'), controller.create);
router.get('/lessons/:lessonId', permit('lms.lesson.view'), controller.getCurriculumLesson);
router.patch('/lessons/:lessonId', permit('lms.lesson.update'), controller.updateBuilderLesson);
router.delete('/lessons/:lessonId', permit('lms.lesson.archive'), controller.deleteBuilderLesson);
router.post('/lessons/:id/publish', permit('courses.edit'), controller.publish);
router.post('/lessons/:id/unpublish', permit('courses.edit'), controller.unpublish);
router.post('/lessons/:id/materials', permit('courses.edit'), controller.addMaterial);
router.post('/materials/upload', permit('courses.edit'), express.raw({ type: 'application/octet-stream', limit: '25mb' }), controller.uploadMaterial);
router.delete('/materials/:id', permit('courses.edit'), controller.deleteMaterial);
module.exports = router;
