import React from'react';
import{Alert,Box,Button,Chip,Grid,MenuItem,Pagination,Paper,Skeleton,Stack,Tab,Tabs,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography}from'@mui/material';
import{useSearchParams}from'react-router-dom';
import{getSupervisorAgents,getSupervisorFollowups,getSupervisorHistory,getSupervisorLiveCalls,getSupervisorOutcomes,getSupervisorSummary,sendCallCenterHeartbeat}from'../services/callCenter.service';
const labels={agentsOnlineNow:'Agents online now',agentsCurrentlyInCalls:'Agents in calls',agentsAvailable:'Agents available',agentsIdle:'Agents idle',totalCallAttempts:'Call attempts',uniqueLeadsContacted:'Unique leads',answeredCalls:'Answered',unansweredCalls:'Unanswered',contactRate:'Contact rate',conversions:'Conversions',conversionRate:'Conversion rate',totalTalkTime:'Talk time',averageTalkTime:'Average talk time',callsPerAgent:'Calls per agent',averageIdleTime:'Average idle time'};
const clock=n=>{n=Math.max(0,Math.floor(n||0));return`${String(Math.floor(n/3600)).padStart(2,'0')}:${String(Math.floor(n%3600/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
export default function Supervisor({showAgentWorkspace,onAgentWorkspace}){
 const[p,setP]=useSearchParams(),[tab,setTab]=React.useState(p.get('view')||'overview'),[state,setState]=React.useState({}),[records,setRecords]=React.useState({loading:false,items:[],pagination:{page:1,total:0,totalPages:0}}),[error,setError]=React.useState(''),[now,setNow]=React.useState(Date.now());
 const filters={period:p.get('period')||'today',from:p.get('from')||'',to:p.get('to')||'',agentIds:p.get('agentIds')||''};
 const set=(k,v)=>{const n=new URLSearchParams(p);v?n.set(k,v):n.delete(k);setP(n,{replace:true})};
 const load=React.useCallback(async()=>{try{const q=Object.fromEntries(Object.entries(filters).filter(([,v])=>v)),[summary,live,agents,outcomes]=await Promise.all([getSupervisorSummary(q),getSupervisorLiveCalls(q),getSupervisorAgents(q),getSupervisorOutcomes(q)]);setState({summary:summary.data.data,live:live.data.data,agents:agents.data.data,outcomes:outcomes.data.data});setError('')}catch(e){setError(e.response?.data?.message||'Unable to load supervisor dashboard.')}},[p.toString()]);
 React.useEffect(()=>{load();const x=setInterval(load,20000);return()=>clearInterval(x)},[load]);
 React.useEffect(()=>{if(!['history','followups'].includes(tab))return;setRecords(s=>({...s,loading:true,error:''}));const fn=tab==='history'?getSupervisorHistory:getSupervisorFollowups;fn({...filters,page:Number(p.get('page')||1),pageSize:20}).then(r=>setRecords({loading:false,...r.data.data})).catch(e=>setRecords(s=>({...s,loading:false,error:e.response?.data?.message||e.message})))},[tab,p.toString()]);
 React.useEffect(()=>{const x=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(x)},[]);
 React.useEffect(()=>{let id=sessionStorage.getItem('callCenterPresenceSession');if(!id){id=crypto.randomUUID();sessionStorage.setItem('callCenterPresenceSession',id)}const beat=activity=>sendCallCenterHeartbeat({sessionIdentifier:id,currentPage:location.pathname,activity}).catch(()=>{});beat(true);const x=setInterval(()=>beat(false),30000),active=()=>beat(true);window.addEventListener('click',active);window.addEventListener('keydown',active);return()=>{clearInterval(x);window.removeEventListener('click',active);window.removeEventListener('keydown',active)}},[]);
 const change=(_,v)=>{if(v==='workspace')return onAgentWorkspace();setTab(v);set('view',v)};
 return <Stack spacing={2}><Box><Typography variant="h3" fontWeight={900}>Supervisor Dashboard</Typography><Typography color="text.secondary">Live operations and historical reporting · {state.summary?.timezone||'Asia/Colombo'}</Typography></Box>{error&&<Alert severity="error">{error}</Alert>}
 <Paper sx={{p:2}}><Grid container spacing={1}><Grid item xs={12} md={3}><TextField select fullWidth size="small" label="Period" value={filters.period} onChange={e=>set('period',e.target.value)}>{[['today','Today'],['yesterday','Yesterday'],['week','This week'],['month','This month'],['custom','Custom']].map(x=><MenuItem key={x[0]} value={x[0]}>{x[1]}</MenuItem>)}</TextField></Grid><Grid item xs={6} md={3}><TextField fullWidth size="small" type="datetime-local" label="From" InputLabelProps={{shrink:true}} value={filters.from} onChange={e=>set('from',e.target.value)}/></Grid><Grid item xs={6} md={3}><TextField fullWidth size="small" type="datetime-local" label="To" InputLabelProps={{shrink:true}} value={filters.to} onChange={e=>set('to',e.target.value)}/></Grid><Grid item xs={12} md={3}><TextField fullWidth size="small" label="Agent IDs" value={filters.agentIds} onChange={e=>set('agentIds',e.target.value)}/></Grid></Grid></Paper>
 <Paper><Tabs value={tab} onChange={change} variant="scrollable"><Tab value="overview" label="Overview"/><Tab value="live" label="Live Calls"/><Tab value="agents" label="Agent Performance"/><Tab value="outcomes" label="Outcomes"/><Tab value="history" label="Call History"/><Tab value="followups" label="Follow-ups"/>{showAgentWorkspace&&<Tab value="workspace" label="Agent Workspace"/>}</Tabs></Paper>
 {tab==='overview'&&<Grid container spacing={2}>{Object.entries(labels).map(([k,label])=><Grid item xs={6} md={3} key={k}><Paper variant="outlined" sx={{p:2,height:'100%'}}><Typography color="text.secondary">{label}</Typography><Typography variant="h4" fontWeight={900}>{k.includes('Time')?clock(state.summary?.metrics?.[k]):k.includes('Rate')?`${Number(state.summary?.metrics?.[k]||0).toFixed(1)}%`:Number(state.summary?.metrics?.[k]||0).toFixed(k==='callsPerAgent'?1:0)}</Typography><Typography variant="caption">{state.summary?.definitions?.[k]}</Typography></Paper></Grid>)}</Grid>}
 {tab==='live'&&<Paper sx={{overflowX:'auto'}}><Table><TableHead><TableRow>{['Agent','State','Lead','Phone','Course','Started','Duration','Previous status'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{(state.live?.calls||[]).map(c=><TableRow key={c.id}><TableCell>{c.agentName}</TableCell><TableCell><Chip size="small" color={c.currentState==='In Call'?'success':'warning'} label={c.currentState}/></TableCell><TableCell>{c.leadName}</TableCell><TableCell>{c.leadPhone}</TableCell><TableCell>{c.course||'—'}</TableCell><TableCell>{new Date(c.startedAt).toLocaleString()}</TableCell><TableCell>{clock((now-new Date(c.startedAt))/1000)}</TableCell><TableCell>{c.previousLeadStatus||'—'}</TableCell></TableRow>)}</TableBody></Table></Paper>}
 {tab==='agents'&&<Paper sx={{overflowX:'auto'}}><Table><TableHead><TableRow>{['Agent','Presence','Calls','Unique leads','Answered','Conversions','Talk time','Idle','Queue'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{(state.agents?.agents||[]).map(a=><TableRow key={a.id}><TableCell>{a.name}</TableCell><TableCell><Chip size="small" label={a.presence}/></TableCell><TableCell>{a.callAttempts}</TableCell><TableCell>{a.uniqueLeadsContacted}</TableCell><TableCell>{a.answered}</TableCell><TableCell>{a.conversions}</TableCell><TableCell>{clock(a.totalTalkTime)}</TableCell><TableCell>{clock(a.idleTime)}</TableCell><TableCell>{a.currentQueueSize}</TableCell></TableRow>)}</TableBody></Table></Paper>}
 {tab==='outcomes'&&<Paper><Table><TableHead><TableRow><TableCell>Canonical outcome</TableCell><TableCell>Count</TableCell><TableCell>Percentage</TableCell><TableCell>Unique leads</TableCell></TableRow></TableHead><TableBody>{(state.outcomes?.outcomes||[]).map(o=><TableRow key={o.code}><TableCell>{o.code.replaceAll('_',' ')}</TableCell><TableCell>{o.count}</TableCell><TableCell>{o.percentage.toFixed(1)}%</TableCell><TableCell>{o.uniqueLeads}</TableCell></TableRow>)}</TableBody></Table></Paper>}
 {['history','followups'].includes(tab)&&(records.loading?<Stack>{[1,2,3,4].map(x=><Skeleton key={x} height={50}/>)}</Stack>:records.error?<Alert severity="error">{records.error}</Alert>:!records.pagination.total?<Paper sx={{p:6,textAlign:'center'}}><Typography fontWeight={800}>No {tab} match these filters.</Typography></Paper>:<Stack><Paper sx={{overflowX:'auto'}}><Table size="small"><TableHead><TableRow>{(tab==='history'?['Agent','Lead','Phone','Started','Duration','Result','Status','Follow-up','Notes']:['Due','Agent','Lead','Phone','Status','Reason']).map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{records.items.map(row=>tab==='history'?<TableRow key={row.id}><TableCell>{[row.agent?.firstName,row.agent?.lastName].filter(Boolean).join(' ')||row.agent?.email}</TableCell><TableCell>{[row.lead?.contact?.firstName,row.lead?.contact?.lastName].filter(Boolean).join(' ')}</TableCell><TableCell>{row.lead?.contact?.phone||'—'}</TableCell><TableCell>{new Date(row.startedAt).toLocaleString('en-LK',{timeZone:'Asia/Colombo'})}</TableCell><TableCell>{clock(row.durationSeconds)}</TableCell><TableCell>{row.disposition||'—'}</TableCell><TableCell>{row.lead?.status?.name||'—'}</TableCell><TableCell>{row.nextFollowupAt?new Date(row.nextFollowupAt).toLocaleString():'—'}</TableCell><TableCell>{row.notes||'—'}</TableCell></TableRow>:<TableRow key={row.id}><TableCell>{new Date(row.dueDate).toLocaleString('en-LK',{timeZone:'Asia/Colombo'})}</TableCell><TableCell>{[row.assignee?.firstName,row.assignee?.lastName].filter(Boolean).join(' ')||row.assignee?.email}</TableCell><TableCell>{[row.lead?.contact?.firstName,row.lead?.contact?.lastName].filter(Boolean).join(' ')}</TableCell><TableCell>{row.lead?.contact?.phone||'—'}</TableCell><TableCell><Chip size="small" label={row.status}/></TableCell><TableCell>{row.note||'—'}</TableCell></TableRow>)}</TableBody></Table></Paper><Pagination page={records.pagination.page} count={Math.max(1,records.pagination.totalPages)} onChange={(_,v)=>set('page',v)}/></Stack>)}</Stack>
}
