import React,{useEffect,useState}from'react';
import{Alert,Box,Button,Card,CardContent,CircularProgress,Grid,Paper,Stack,TextField,Typography}from'@mui/material';
import{getCallCenterDashboard,logCall}from'../services/callCenter.service';
const cards=[['Call attempts','callAttempts'],['Unique leads contacted','uniqueLeadsContacted'],['Answered calls','answeredCalls'],['Conversions','conversions'],['Contact rate','contactRate'],['Average talk time','averageTalkTime']];
export default function CallCenterPage(){
 const[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[filters,setFilters]=useState({from:'',to:''}),[call,setCall]=useState({leadId:'',newStatusId:'',disposition:'',notes:'',nextFollowUpAt:''});
 const load=()=>{setLoading(true);setError('');getCallCenterDashboard(filters).then(r=>setData(r.data.data)).catch(e=>setError(e.response?.data?.message||'Unable to load call-center metrics.')).finally(()=>setLoading(false));};
 useEffect(load,[]);// eslint-disable-line react-hooks/exhaustive-deps
 const save=()=>{if(!call.leadId||!call.newStatusId||!call.disposition){setError('Lead, result, and new status are required.');return;}setSaving(true);logCall({...call,reason:call.notes,idempotencyKey:crypto.randomUUID()}).then(()=>{setCall({leadId:'',newStatusId:'',disposition:'',notes:'',nextFollowUpAt:''});load();}).catch(e=>setError(e.response?.data?.message||'Unable to save the call.')).finally(()=>setSaving(false));};
 return <Stack spacing={3}><Box><Typography variant="h3" fontWeight={900}>Call Center</Typography><Typography color="text.secondary">Agent-reported call activity and lead outcomes · Asia/Colombo</Typography></Box>
 <Paper variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} spacing={2}><TextField type="date" label="From" InputLabelProps={{shrink:true}} value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><TextField type="date" label="To" InputLabelProps={{shrink:true}} value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/><Button variant="contained" onClick={load} disabled={loading}>Refresh</Button></Stack></Paper>
 <Paper variant="outlined" sx={{p:2}}><Typography variant="h6" fontWeight={800} sx={{mb:2}}>Log completed manual call</Typography><Grid container spacing={2}><Grid item xs={12} md={3}><TextField required fullWidth label="Lead ID" value={call.leadId} onChange={e=>setCall({...call,leadId:e.target.value})}/></Grid><Grid item xs={12} md={3}><TextField required fullWidth label="New status ID" value={call.newStatusId} onChange={e=>setCall({...call,newStatusId:e.target.value})}/></Grid><Grid item xs={12} md={3}><TextField required fullWidth label="Result / disposition" value={call.disposition} onChange={e=>setCall({...call,disposition:e.target.value})}/></Grid><Grid item xs={12} md={3}><TextField fullWidth type="datetime-local" label="Next follow-up" InputLabelProps={{shrink:true}} value={call.nextFollowUpAt} onChange={e=>setCall({...call,nextFollowUpAt:e.target.value})}/></Grid><Grid item xs={12}><TextField fullWidth multiline minRows={2} label="Notes / required reason" value={call.notes} onChange={e=>setCall({...call,notes:e.target.value})}/></Grid><Grid item xs={12}><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving…':'Save reported call'}</Button></Grid></Grid></Paper>
 {error&&<Alert severity="error">{error}</Alert>}{loading?<CircularProgress/>:<><Grid container spacing={2}>{cards.map(([label,key])=><Grid item xs={12} sm={6} md={4} key={key}><Card variant="outlined"><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4" fontWeight={900}>{data?.totals?.[key]??0}{key==='contactRate'?'%':key==='averageTalkTime'?' sec':''}</Typography></CardContent></Card></Grid>)}</Grid>
 <Paper variant="outlined" sx={{p:2}}><Typography variant="h6" fontWeight={800}>Metric definitions</Typography>{Object.entries(data?.definitions||{}).map(([k,v])=><Typography key={k} variant="body2"><b>{k}:</b> {v}</Typography>)}</Paper></>}</Stack>;
}
