import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Alert,Box,Button,Checkbox,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,Grid,InputLabel,MenuItem,Paper,Select,Stack,Tab,Tabs,TextField,Typography}from'@mui/material';
import{useLocation,useNavigate,useSearchParams}from'react-router-dom';
import{addCallQueueEntries,bulkAddCallQueueEntries,claimCallQueueEntry,claimNextCall,completeCall,getActiveCall,getCallCenterDashboard,getCallCenterOptions,getCallQueue,searchCallCenterLeads,startCall,updateCallQueueEntry}from'../services/callCenter.service';
import{getAgents}from'../services/agent.service';
import{getLabels}from'../services/chat.service';
import LabelMultiSelect from'../components/LabelMultiSelect';
import WhatsAppAccountSelect from'../components/WhatsAppAccountSelect';
import{LEAD_COURSES,LEAD_DATE_TYPES,LEAD_SOURCES}from'../constants/leadFilterOptions';
import SupervisorDashboard from'./CallCenterSupervisorDashboard';
import{getAccessPayload}from'../utils/access';

const dispositions=['Answered','No Answer','Busy','Switched Off','Call Rejected','Wrong Number','Call Back Later','Interested','Not Interested','Agreed','Registered','Lost','Technical Failure'];
const statusMap={'Answered':'contacted','No Answer':'no_answer','Busy':'busy','Switched Off':'switched_off','Call Rejected':'call_rejected','Wrong Number':'wrong_number','Call Back Later':'follow_up_required','Interested':'interested','Not Interested':'not_interested','Agreed':'agreed','Registered':'registered','Lost':'lost','Technical Failure':'call_pending'};
const blankOutcome={disposition:'',newStatusId:'',notes:'',nextFollowUpAt:''};
const defaultFilters={search:'',phone:'',email:'',status:'',source:'',assignedAgentId:'',courseInterested:'',whatsappAccountId:'',labelIds:[],labelMode:'any',dateType:'createdAt',dateFrom:'',dateTo:'',sortBy:'createdAt',sortDirection:'DESC',page:1,limit:20};
const seconds=value=>`${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;
const message=error=>{const text=Object.values(error.response?.data?.errors||{})[0]||error.response?.data?.message||error.message||'Request failed.',requestId=error.response?.data?.requestId;return requestId?`${text} (Request ${requestId})`:text;};
const agentName=agent=>agent?.name||[agent?.firstName,agent?.lastName].filter(Boolean).join(' ')||agent?.email||'Unknown agent';
export const normalizeAgentTab=tab=>['queue','find','followups','history','performance'].includes(tab)?tab:'queue';
export const resolveCallCenterMode=access=>(access.isSystemAdmin||access.permissions?.includes('call_center.supervisor_dashboard'))?'supervisor':'agent';

function AgentWorkspace(){
 const navigate=useNavigate(),location=useLocation(),[params,setParams]=useSearchParams();
 const agentTabs=['queue','find','followups','history','performance'],requestedTab=params.get('tab'),initialTab=normalizeAgentTab(requestedTab),stored=(()=>{try{return JSON.parse(sessionStorage.getItem('callCenterFilters')||'null')}catch{return null}})(),urlFilters=Object.fromEntries([...params].filter(([key])=>key.startsWith('f_')).map(([key,value])=>[key.slice(2),value]));
 const initialFilters={...defaultFilters,...stored,...urlFilters,labelIds:String(urlFilters.labelIds??stored?.labelIds??'').split(',').filter(Boolean).map(Number)};
 const[tab,setTab]=useState(initialTab),[filters,setFilters]=useState(initialFilters);
 const[options,setOptions]=useState({leads:[],statuses:[]}),[agents,setAgents]=useState([]),[labels,setLabels]=useState([]),[queue,setQueue]=useState({queue:null,entries:[]}),[results,setResults]=useState({leads:[],pagination:{page:1,pages:0,total:0}}),[selected,setSelected]=useState([]),[active,setActive]=useState(null),[data,setData]=useState(null),[outcome,setOutcome]=useState(blankOutcome),[outcomeErrors,setOutcomeErrors]=useState({}),[outcomeOpen,setOutcomeOpen]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tick,setTick]=useState(Date.now()),[chatChoices,setChatChoices]=useState(null);
 useEffect(()=>{if(requestedTab&&!agentTabs.includes(requestedTab)){const next=new URLSearchParams(params);next.set('tab','queue');setParams(next,{replace:true});setNotice('You do not have permission to view that Call Center dashboard.');}},[]);
 const loadQueue=useCallback(()=>getCallQueue().then(({data})=>setQueue(data.data)),[]);
 const loadBase=useCallback(()=>Promise.all([getCallCenterOptions(),getActiveCall(),getCallCenterDashboard()]).then(([optionsResponse,activeResponse,dashboardResponse])=>{setOptions(optionsResponse.data.data);setActive(activeResponse.data.data);setData(dashboardResponse.data.data);}),[]);
 useEffect(()=>{loadBase().catch(requestError=>setError(message(requestError)));loadQueue().catch(requestError=>setError(message(requestError)));},[loadBase,loadQueue]);
 useEffect(()=>{getAgents().then(response=>setAgents(response.data.data||[])).catch(requestError=>setError(message(requestError)));getLabels().then(response=>setLabels(response.data.data||[])).catch(requestError=>setError(message(requestError)));},[]);
 useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const syncState=useCallback((nextTab=tab,nextFilters=filters)=>{const query=new URLSearchParams();query.set('tab',nextTab);Object.entries(nextFilters).forEach(([key,value])=>{const serialized=Array.isArray(value)?value.join(','):value;if(serialized!==''&&serialized!=null&&key!=='limit')query.set(`f_${key}`,serialized);});setParams(query,{replace:true});sessionStorage.setItem('callCenterFilters',JSON.stringify(nextFilters));},[filters,setParams,tab]);
 const changeTab=(_,value)=>{setTab(value);syncState(value,filters);};
 const search=useCallback(async(next=filters)=>{setBusy(true);setError('');try{const{data}=await searchCallCenterLeads(next);setResults(data.data);syncState('find',next);}catch(requestError){setError(message(requestError));}finally{setBusy(false);}},[filters,syncState]);
 useEffect(()=>{if(tab==='find'&&!results.leads.length)search(filters);},[tab]);
 const setFilter=(key,value)=>setFilters(current=>({...current,[key]:value,page:1}));
 const quick=(values)=>{const next={...defaultFilters,...values,page:1};setFilters(next);search(next);};
 const start=async lead=>{setBusy(true);setError('');try{const{data:response}=await startCall({leadId:lead.id,method:'manual',idempotencyKey:crypto.randomUUID()});setActive({...response.data,lead});window.location.href=`tel:${String(lead.phone||lead.contact?.phone||'').replace(/[^\d+]/g,'')}`;await loadQueue();}catch(requestError){setError(message(requestError));}finally{setBusy(false);}};
 const callNext=async()=>{setBusy(true);setError('');try{const before=new Map(queue.entries.map(entry=>[String(entry.leadId),entry.lead]));const{data:response}=await claimNextCall();const lead=before.get(String(response.data.entry.leadId));setActive({...response.data.call,lead});window.location.href=`tel:${String(lead?.contact?.phone||'').replace(/[^\d+]/g,'')}`;await loadQueue();}catch(requestError){setError(message(requestError));}finally{setBusy(false);}};
 const callEntry=async entry=>{setBusy(true);setError('');try{const{data:response}=await claimCallQueueEntry(entry.id);setActive({...response.data.call,lead:entry.lead});window.location.href=`tel:${String(entry.lead?.contact?.phone||'').replace(/[^\d+]/g,'')}`;await loadQueue();}catch(requestError){setError(message(requestError));}finally{setBusy(false);}};
 const addSelected=async()=>{if(!selected.length)return;setBusy(true);try{const{data}=await addCallQueueEntries({leadIds:selected,source:'call_center_search',sourceFilter:filters});setNotice(`${data.data.added} added, ${data.data.alreadyInQueue} already queued, ${data.data.rejected} rejected.`);setSelected([]);await Promise.all([loadQueue(),search(filters)]);}catch(requestError){setError(message(requestError));}finally{setBusy(false);}};
 const addAllMatching=async()=>{if(!window.confirm(`Add all ${results.pagination.total} matching permitted leads? Maximum 100.`))return;setBusy(true);try{const{data}=await bulkAddCallQueueEntries({filters});setNotice(`${data.data.added} added, ${data.data.alreadyInQueue} already queued, ${data.data.rejected} rejected.`);await Promise.all([loadQueue(),search(filters)]);}catch(requestError){setError(message(requestError));}finally{setBusy(false);}};
 const queueAction=async(entry,payload)=>{setBusy(true);try{await updateCallQueueEntry(entry.id,payload);await loadQueue();}catch(requestError){setError(message(requestError));}finally{setBusy(false);}};
 const chooseResult=value=>{const mapped=options.statuses.find(status=>status.code===statusMap[value]);setOutcomeErrors({});setOutcome(current=>({...current,disposition:value,newStatusId:mapped?.id||''}));};
 const mappedStatus=options.statuses.find(status=>status.code===statusMap[outcome.disposition]),mappedMissing=!!outcome.disposition&&!mappedStatus;
 const saveOutcome=async()=>{const status=options.statuses.find(item=>String(item.id)===String(outcome.newStatusId)),needsFollow=outcome.disposition==='Call Back Later'||status?.followupRequired,needsReason=['Not Interested','Wrong Number','Call Rejected','Lost'].includes(outcome.disposition)||status?.reasonRequired,invalid={};if(!outcome.disposition)invalid.disposition='Call result is required.';if(!outcome.newStatusId)invalid.newStatusId='New status is required.';if(needsFollow&&!outcome.nextFollowUpAt)invalid.nextFollowUpAt='Next follow-up is required.';if(needsReason&&!outcome.notes.trim())invalid.notes='Reason is required.';setOutcomeErrors(invalid);if(Object.keys(invalid).length)return;setBusy(true);try{await completeCall(active.id,{...outcome,reason:outcome.notes});setOutcomeOpen(false);setOutcome(blankOutcome);setActive(null);setNotice('Outcome saved. The next queue lead is ready.');await Promise.all([loadQueue(),loadBase()]);}catch(requestError){setOutcomeErrors(requestError.response?.data?.errors||{});setError(message(requestError));}finally{setBusy(false);}};
 const openChat=lead=>{const conversations=lead.conversations||[];if(!conversations.length){setNotice('No WhatsApp conversation exists for this lead.');return;}if(conversations.length>1){setChatChoices({lead,conversations});return;}goChat(conversations[0]);};
 const goChat=conversation=>{const returnTo=encodeURIComponent(`${location.pathname}${location.search}`);navigate(`/chat?conversationId=${conversation.id}&returnTo=${returnTo}`);};
 const elapsed=active?Math.max(0,Math.floor((tick-new Date(active.startedAt).getTime())/1000)):0;
 const allPageSelected=results.leads.length>0&&results.leads.every(lead=>selected.includes(lead.id));
 return <Stack spacing={2}>
  <Box><Typography variant="h3" fontWeight={900}>Call Center</Typography><Typography color="text.secondary">Build a persistent queue, call, message and follow up without leaving your workflow.</Typography></Box>
  {error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}{notice&&<Alert severity="success" onClose={()=>setNotice('')}>{notice}</Alert>}
  {active&&<Paper sx={{p:2,border:2,borderColor:'primary.main',position:'sticky',top:8,zIndex:5}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems="center"><Box><Chip color="warning" label="Agent reported · In Call"/><Typography variant="h5" fontWeight={900}>{active.lead?.name||active.lead?.contact?.firstName||`Lead ${active.leadId}`}</Typography><Typography>{seconds(elapsed)}</Typography></Box><Stack direction="row"><Button onClick={()=>openChat(active.lead||{})}>OPEN CHAT</Button><Button color="error" variant="contained" onClick={()=>setOutcomeOpen(true)}>END CALL</Button></Stack></Stack></Paper>}
  <Paper><Tabs value={tab} onChange={changeTab} variant="scrollable"><Tab value="queue" label={`My Queue (${queue.entries.length})`}/><Tab value="find" label="Find Leads"/><Tab value="followups" label="Follow-ups"/><Tab value="history" label="Call History"/><Tab value="performance" label="My Performance"/></Tabs></Paper>
  {tab==='queue'&&<Stack spacing={2}><Button size="large" variant="contained" disabled={busy||!!active||!queue.entries.length} onClick={callNext}>{busy?<CircularProgress size={22}/>:'CALL NEXT'}</Button>{!queue.entries.length&&<Alert severity="info">Your queue is empty. Use Find Leads to add permitted leads.</Alert>}{queue.entries.map((entry,index)=><Paper key={entry.id} variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={900}>#{index+1} · {entry.lead?.contact?.firstName} {entry.lead?.contact?.lastName}</Typography><Typography variant="body2">{entry.lead?.courseInterested||'No course'} · {entry.lead?.status?.name||'No status'} · attempts {entry.metrics?.attempts||0}</Typography><Typography variant="caption">Last: {entry.metrics?.lastResult||'Never'} · Added {new Date(entry.addedAt).toLocaleString()}</Typography></Box><Stack direction="row" flexWrap="wrap"><Button disabled={busy||!!active} onClick={()=>callEntry(entry)}>Start Call</Button><Button onClick={()=>openChat({...entry.lead,conversations:entry.conversations})}>{entry.conversations?.length>1?'SELECT CHAT':entry.conversations?.length?'OPEN CHAT':'CHAT UNAVAILABLE'}</Button><Button onClick={()=>queueAction(entry,{status:'skipped',skipReason:'Skipped by agent'})}>Skip</Button><Button color="error" onClick={()=>queueAction(entry,{status:'removed'})}>Remove</Button></Stack></Stack></Paper>)}</Stack>}
  {tab==='find'&&<Stack spacing={2}><Paper variant="outlined" sx={{p:2}}><Stack direction="row" flexWrap="wrap" gap={1} sx={{mb:2}}><Button onClick={()=>quick({assignedAgentId:'me'})}>My Assigned Leads</Button><Button onClick={()=>quick({status:'new'})}>New Leads</Button><Button onClick={()=>quick({neverContacted:'true'})}>Never Contacted</Button><Button onClick={()=>quick({overdueFollowup:'true'})}>Overdue Follow-ups</Button><Button onClick={()=>quick({noAnswerPreviously:'true'})}>No Answer — Retry</Button><Button onClick={()=>quick({status:'interested'})}>Interested</Button><Button onClick={()=>quick({unassigned:'true'})}>Unassigned</Button></Stack><Grid container spacing={1}>
   {[['search','Search name, phone or email'],['phone','Phone'],['email','Email']].map(([key,label])=><Grid item xs={12} sm={6} md={3} key={key}><TextField fullWidth size="small" label={label} value={filters[key]||''} onChange={event=>setFilter(key,event.target.value)}/></Grid>)}
   <Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" label="Source" value={filters.source||''} onChange={event=>setFilter('source',event.target.value)}><MenuItem value="">All sources</MenuItem>{LEAD_SOURCES.map(source=><MenuItem key={source} value={source}>{source}</MenuItem>)}</TextField></Grid>
   <Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" label="Course" value={filters.courseInterested||''} onChange={event=>setFilter('courseInterested',event.target.value)}><MenuItem value="">All courses</MenuItem>{LEAD_COURSES.map(course=><MenuItem key={course} value={course}>{course}</MenuItem>)}</TextField></Grid>
   <Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" label="Assigned agent" value={filters.assignedAgentId||''} onChange={event=>setFilter('assignedAgentId',event.target.value)}><MenuItem value="">All agents</MenuItem><MenuItem value="me">Me</MenuItem>{agents.map(agent=><MenuItem key={agent.id} value={agent.id}>{agentName(agent)}</MenuItem>)}</TextField></Grid>
   <Grid item xs={12} sm={6} md={3}><WhatsAppAccountSelect value={filters.whatsappAccountId} onChange={value=>setFilter('whatsappAccountId',value)} allowAll fullWidth onError={setError}/></Grid>
   <Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" label="Lead status" value={filters.status||''} onChange={event=>setFilter('status',event.target.value)}><MenuItem value="">All statuses</MenuItem>{options.statuses.map(status=><MenuItem key={status.id} value={status.code}>{status.name}</MenuItem>)}</TextField></Grid>
   <Grid item xs={12} md={6}><LabelMultiSelect options={labels} value={filters.labelIds} onChange={value=>setFilter('labelIds',value)} onOptionsChange={setLabels}/></Grid>
   <Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" label="Label match" value={filters.labelMode||'any'} onChange={event=>setFilter('labelMode',event.target.value)}><MenuItem value="any">Has any selected</MenuItem><MenuItem value="all">Has all selected</MenuItem></TextField></Grid>
   <Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" label="Date type" value={filters.dateType||'createdAt'} onChange={event=>setFilter('dateType',event.target.value)}>{LEAD_DATE_TYPES.map(item=><MenuItem key={item.value} value={item.value}>{item.label}</MenuItem>)}</TextField></Grid>
   {[['dateFrom','From'],['dateTo','To']].map(([key,label])=><Grid item xs={12} sm={6} md={3} key={key}><TextField fullWidth size="small" type="date" InputLabelProps={{shrink:true}} label={label} value={filters[key]||''} onChange={event=>setFilter(key,event.target.value)}/></Grid>)}
   <Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" label="Sort" value={filters.sortBy||'createdAt'} onChange={event=>setFilter('sortBy',event.target.value)}><MenuItem value="createdAt">Created</MenuItem><MenuItem value="updatedAt">Updated</MenuItem><MenuItem value="nextFollowupAt">Next follow-up</MenuItem></TextField></Grid>
   <Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" label="Direction" value={filters.sortDirection||'DESC'} onChange={event=>setFilter('sortDirection',event.target.value)}><MenuItem value="DESC">Newest first</MenuItem><MenuItem value="ASC">Oldest first</MenuItem></TextField></Grid>
   <Grid item xs={12}><Button variant="contained" disabled={busy} onClick={()=>search(filters)}>Search</Button></Grid>
  </Grid></Paper>
   <Stack direction="row" spacing={1}><Checkbox checked={allPageSelected} onChange={event=>setSelected(event.target.checked?results.leads.map(lead=>lead.id):[])}/><Button disabled={!selected.length||busy} variant="contained" onClick={addSelected}>Add Selected to My Queue ({selected.length})</Button><Button disabled={!results.pagination.total||results.pagination.total>100||busy} onClick={addAllMatching}>Add All Matching</Button><Button disabled={!selected.length} onClick={()=>setSelected([])}>Clear Selection</Button><Typography sx={{ml:'auto'}}>{results.pagination.total} matching</Typography></Stack>
   {results.leads.map(lead=><Paper key={lead.id} variant="outlined" sx={{p:1.5}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between"><Stack direction="row" alignItems="center"><Checkbox checked={selected.includes(lead.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,lead.id]:current.filter(id=>id!==lead.id))}/><Box><Typography fontWeight={850}>{lead.name||`Lead ${lead.id}`}</Typography><Typography variant="body2">{lead.courseInterested||'No course'} · <Chip size="small" label={lead.status||lead.statusCode} /> · {lead.source||'No source'} · attempts {lead.attempts||0}</Typography><Typography variant="caption">Last: {lead.lastResult||'Never'} · Follow-up: {lead.followUpDate?new Date(lead.followUpDate).toLocaleString():'None'} {lead.queueState&&` · ${lead.queueState}`}</Typography></Box></Stack><Stack direction="row"><Button disabled={busy||!!active} onClick={()=>start(lead)}>Start Call Now</Button><Button disabled={!!lead.queueState} onClick={async()=>{setSelected([lead.id]);await addCallQueueEntries({leadIds:[lead.id],source:'call_center_search',sourceFilter:filters});await Promise.all([loadQueue(),search(filters)]);}}>Add to Queue</Button><Button onClick={()=>openChat(lead)}>{lead.conversations?.length>1?'SELECT CHAT':lead.conversations?.length?'OPEN CHAT':'CHAT UNAVAILABLE'}</Button></Stack></Stack></Paper>)}
   <Stack direction="row" justifyContent="center"><Button disabled={Number(filters.page)<=1} onClick={()=>{const next={...filters,page:Number(filters.page)-1};setFilters(next);search(next);}}>Previous</Button><Typography sx={{p:1}}>Page {results.pagination.page} / {results.pagination.pages||1}</Typography><Button disabled={results.pagination.page>=results.pagination.pages} onClick={()=>{const next={...filters,page:Number(filters.page)+1};setFilters(next);search(next);}}>Next</Button></Stack>
  </Stack>}
  {tab==='followups'&&<Alert severity="info">Due and overdue follow-ups remain available through the shared lead filters. Use Find Leads quick filters to add them to your queue.</Alert>}
  {tab==='history'&&<Stack>{(data?.recentCalls||[]).map(call=><Paper key={call.id} sx={{p:1,mb:1}}>Lead {call.leadId} · {call.disposition||'Unknown'} · {call.durationSeconds||0}s</Paper>)}</Stack>}
  {tab==='performance'&&<Grid container spacing={2}>{Object.entries(data?.totals||{}).slice(0,6).map(([key,value])=><Grid item xs={6} md={3} key={key}><Paper sx={{p:2}}><Typography color="text.secondary">{key.replace(/([A-Z])/g,' $1')}</Typography><Typography variant="h4">{value}</Typography></Paper></Grid>)}</Grid>}
  <Dialog open={outcomeOpen} onClose={()=>!busy&&setOutcomeOpen(false)} fullWidth><DialogTitle>After-call outcome</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>{mappedMissing&&<Alert severity="error">The {outcome.disposition} lead status is not configured. Ask an administrator to enable it.</Alert>}<FormControl required error={!!outcomeErrors.disposition}><InputLabel>Result *</InputLabel><Select label="Result *" value={outcome.disposition} onChange={event=>chooseResult(event.target.value)}>{dispositions.map(value=><MenuItem key={value} value={value}>{value}</MenuItem>)}</Select></FormControl><FormControl required error={!!outcomeErrors.newStatusId}><InputLabel>New status *</InputLabel><Select label="New status *" value={outcome.newStatusId} onChange={event=>setOutcome({...outcome,newStatusId:event.target.value})}>{options.statuses.map(status=><MenuItem key={status.id} value={status.id}><Chip size="small" label={status.name} sx={{bgcolor:status.color,color:'#fff'}}/></MenuItem>)}</Select></FormControl>{mappedStatus&&<Typography variant="caption">{mappedStatus.name} selected automatically.</Typography>}<TextField type="datetime-local" label="Next follow-up" InputLabelProps={{shrink:true}} value={outcome.nextFollowUpAt} error={!!outcomeErrors.nextFollowUpAt} helperText={outcomeErrors.nextFollowUpAt} onChange={event=>setOutcome({...outcome,nextFollowUpAt:event.target.value})}/><TextField multiline minRows={3} label="Reason / notes" value={outcome.notes} error={!!outcomeErrors.notes} helperText={outcomeErrors.notes} onChange={event=>setOutcome({...outcome,notes:event.target.value})}/></Stack></DialogContent><DialogActions><Button disabled={busy} onClick={()=>setOutcomeOpen(false)}>Cancel</Button><Button variant="contained" disabled={busy||mappedMissing} onClick={saveOutcome}>{busy?'Saving…':'Save Outcome'}</Button></DialogActions></Dialog>
  <Dialog open={!!chatChoices} onClose={()=>setChatChoices(null)} fullWidth><DialogTitle>Select WhatsApp conversation</DialogTitle><DialogContent><Stack spacing={1}>{chatChoices?.conversations.map(conversation=><Button key={conversation.id} variant="outlined" onClick={()=>goChat(conversation)}>{conversation.whatsappAccount?.name||`Account ${conversation.whatsappAccountId}`} · {conversation.status} · {conversation.lastMessageAt?new Date(conversation.lastMessageAt).toLocaleString():'No messages'}</Button>)}</Stack></DialogContent></Dialog>
 </Stack>;
}
export default function CallCenterPage(){
 const access=getAccessPayload(),supervisor=resolveCallCenterMode(access)==='supervisor',agent=access.permissions?.includes('call_center.agent_workspace');
 const[workspace,setWorkspace]=useState(false);
 if(supervisor&&!workspace)return <SupervisorDashboard showAgentWorkspace={agent} onAgentWorkspace={()=>setWorkspace(true)}/>;
 return <AgentWorkspace/>;
}
