import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Alert,Autocomplete,Box,Button,Card,CardContent,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,Grid,InputLabel,MenuItem,Paper,Select,Stack,TextField,Typography}from'@mui/material';
import{useSearchParams}from'react-router-dom';
import{completeCall,getActiveCall,getCallCenterDashboard,getCallCenterOptions,getCallQueue,logCall,startCall}from'../services/callCenter.service';

const dispositions=['Answered','No Answer','Busy','Switched Off','Call Rejected','Call Back Later','Interested','Not Interested','Registered','Wrong Number','Technical Failure'];
const statusMap={'No Answer':'no_answer','Busy':'busy','Switched Off':'switched_off','Call Back Later':'follow_up_required','Interested':'interested','Not Interested':'not_interested','Registered':'registered','Wrong Number':'wrong_number'};
const blank={disposition:'',newStatusId:'',notes:'',nextFollowUpAt:''};
const seconds=v=>`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`;

export default function CallCenterPage(){
 const[params]=useSearchParams(),routeLeadId=params.get('leadId'),routeAction=params.get('action'),[data,setData]=useState(null),[options,setOptions]=useState({leads:[],statuses:[]}),[queue,setQueue]=useState([]),[lead,setLead]=useState(null),[active,setActive]=useState(null),[outcome,setOutcome]=useState(blank),[open,setOpen]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[tick,setTick]=useState(Date.now()),[filters,setFilters]=useState({period:'today'});
 const reload=useCallback(()=>Promise.all([getCallCenterDashboard(filters),getCallCenterOptions(),getCallQueue(),getActiveCall()]).then(([d,o,q,a])=>{setData(d.data.data);setOptions(o.data.data);setQueue(q.data.data);setActive(a.data.data);}).catch(e=>setError(e.response?.data?.message||'Unable to load Call Center data.')),[filters]);
 useEffect(()=>{reload();},[reload]);
 useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(routeLeadId&&options.leads.length){const selected=options.leads.find(x=>String(x.id)===routeLeadId);if(selected){setLead(selected);if(routeAction==='log')setOpen(true);}}},[options.leads,routeAction,routeLeadId]);
 const allowed=useMemo(()=>{if(!lead?.status?.allowedNextStatusIds?.length)return options.statuses;return options.statuses.filter(s=>lead.status.allowedNextStatusIds.map(String).includes(String(s.id)));},[lead,options.statuses]);
 const chooseResult=value=>{const suggested=options.statuses.find(s=>s.code===statusMap[value]);setOutcome(current=>({...current,disposition:value,newStatusId:suggested?.id||current.newStatusId}));};
 const begin=selected=>{setError('');setSaving(true);startCall({leadId:selected.id,idempotencyKey:crypto.randomUUID()}).then(r=>{setActive({...r.data.data,lead:selected});window.location.href=`tel:${String(selected.phone||'').replace(/[^\d+]/g,'')}`;}).catch(e=>setError(e.response?.data?.message||'Unable to start call.')).finally(()=>setSaving(false));};
 const finish=()=>setOpen(true);
 const save=()=>{const selectedStatus=options.statuses.find(s=>String(s.id)===String(outcome.newStatusId)),needsFollow=outcome.disposition==='Call Back Later'||selectedStatus?.followupRequired,needsReason=['Not Interested','Wrong Number','Call Rejected'].includes(outcome.disposition)||selectedStatus?.reasonRequired;if(!outcome.disposition||!outcome.newStatusId){setError('Call result and new status are required.');return;}if(needsFollow&&!outcome.nextFollowUpAt){setError('Next follow-up is required for this outcome.');return;}if(needsReason&&!outcome.notes.trim()){setError('A reason or note is required for this outcome.');return;}setSaving(true);const request=active?completeCall(active.id,{...outcome,reason:outcome.notes}):logCall({...outcome,reason:outcome.notes,leadId:lead.id,idempotencyKey:crypto.randomUUID()});request.then(()=>{setOpen(false);setActive(null);setOutcome(blank);reload();}).catch(e=>setError(e.response?.data?.message||'Unable to save call outcome.')).finally(()=>setSaving(false));};
 const elapsed=active?Math.max(0,Math.floor((tick-new Date(active.startedAt).getTime())/1000)):0;
 return <Stack spacing={3}><Box><Typography variant="h3" fontWeight={900}>Call Center</Typography><Typography color="text.secondary">Manual calls are clearly recorded as Agent reported.</Typography></Box>{error&&<Alert severity="error">{error}</Alert>}
 {active&&<Paper sx={{p:2,border:2,borderColor:'primary.main'}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems="center"><Box><Chip color="warning" label="Agent reported · In Call"/><Typography variant="h5" fontWeight={900}>{active.lead?.name||active.lead?.contact?.name||`Lead ${active.leadId}`}</Typography><Typography>{seconds(elapsed)}</Typography></Box><Button color="error" variant="contained" onClick={finish}>End Call</Button></Stack></Paper>}
 <Paper variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} spacing={2}><FormControl sx={{minWidth:180}}><InputLabel>Period</InputLabel><Select label="Period" value={filters.period} onChange={e=>setFilters({...filters,period:e.target.value})}>{['today','yesterday','week','month','custom'].map(x=><MenuItem key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</MenuItem>)}</Select></FormControl><Button variant="contained" onClick={reload}>Apply filters</Button></Stack></Paper>
 <Paper variant="outlined" sx={{p:2}}><Typography variant="h6" fontWeight={800}>Start or log a call</Typography><Autocomplete sx={{mt:2}} options={options.leads} value={lead} onChange={(_,v)=>setLead(v)} getOptionLabel={x=>`${x.name||'Unnamed'} · ${x.phone||'No phone'} · ${x.status?.name||'No status'}`} renderOption={(p,x)=><li {...p}><Box><Typography fontWeight={800}>{x.name}</Typography><Typography variant="caption">{x.phone} · {x.course||'No course'} · {x.assignedAgent?.firstName||''} {x.assignedAgent?.lastName||''}</Typography></Box></li>} renderInput={p=><TextField {...p} required label="Search assigned lead *" placeholder="Name, phone or email"/>}/><Stack direction="row" spacing={1} sx={{mt:2}}><Button variant="contained" disabled={!lead||!!active||saving} onClick={()=>begin(lead)}>Start Call</Button><Button variant="outlined" disabled={!lead||!!active} onClick={()=>setOpen(true)}>Log Call</Button></Stack></Paper>
 <Typography variant="h5" fontWeight={900}>My Call Queue</Typography><Grid container spacing={2}>{queue.slice(0,12).map(x=><Grid item xs={12} md={6} key={x.id}><Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Typography fontWeight={900}>{x.name}</Typography><Chip size="small" label={x.status?.name||'No status'} sx={{bgcolor:x.status?.color}}/></Stack><Typography variant="body2">{x.phone} · {x.course||'No course'}</Typography><Typography variant="caption">Last: {x.lastCallResult||'Never'} · Attempts: {x.callAttemptCount} · Follow-up: {x.nextFollowupAt?new Date(x.nextFollowupAt).toLocaleString():'None'}</Typography><Button size="small" sx={{mt:1}} disabled={!!active} onClick={()=>{setLead(options.leads.find(l=>String(l.id)===String(x.id))||x);begin(x);}}>Start Call</Button></CardContent></Card></Grid>)}</Grid>
 <Grid container spacing={2}>{[['Calls today','callAttempts'],['Unique leads','uniqueLeadsContacted'],['Answered','answeredCalls'],['Conversions','conversions']].map(([l,k])=><Grid item xs={6} md={3} key={k}><Card><CardContent><Typography color="text.secondary">{l}</Typography><Typography variant="h4">{data?.totals?.[k]||0}</Typography></CardContent></Card></Grid>)}</Grid>
 <Dialog open={open} onClose={saving?undefined:()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>After-call outcome · Agent reported</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><FormControl required><InputLabel>Result *</InputLabel><Select label="Result *" value={outcome.disposition} onChange={e=>chooseResult(e.target.value)}>{dispositions.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><FormControl required><InputLabel>New status *</InputLabel><Select label="New status *" value={outcome.newStatusId} onChange={e=>setOutcome({...outcome,newStatusId:e.target.value})}>{allowed.map(s=><MenuItem key={s.id} value={s.id}><Chip size="small" label={s.name} sx={{bgcolor:s.color,color:'#fff'}}/></MenuItem>)}</Select></FormControl><TextField type="datetime-local" label="Next follow-up" InputLabelProps={{shrink:true}} value={outcome.nextFollowUpAt} onChange={e=>setOutcome({...outcome,nextFollowUpAt:e.target.value})}/><TextField multiline minRows={3} label="Reason / notes" value={outcome.notes} onChange={e=>setOutcome({...outcome,notes:e.target.value})}/></Stack></DialogContent><DialogActions><Button disabled={saving} onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" disabled={saving} onClick={save}>{saving?<CircularProgress size={20}/>:'Save outcome'}</Button></DialogActions></Dialog></Stack>;
}
