import React,{useCallback,useEffect,useState}from'react';
import{Alert,Box,Button,Checkbox,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,MenuItem,Paper,Skeleton,Stack,Tab,Tabs,TextField,Typography}from'@mui/material';
import{bulkCommissionApproval,commissionAction,commissionDashboard,commissionProfitability,commissionReconciliation,commissionReport,createPayout,exportCommissionReport,listCommissionRules,listCommissions,listLecturerAgreements,listPayouts,payoutAction,previewCommissionRule,saveCommissionRule,saveLecturerAgreement}from'../services/commission.service';
import{searchBatches,searchCourses}from'../services/education.service';
import{getUsers}from'../services/userManagement.service';
import AsyncSearchSelect from'../components/AsyncSearchSelect';
import{hasPermission}from'../utils/access';

const TABS=['Dashboard','Ledger / Transactions','Rules','Lecturer Agreements','Approvals','Payouts','Profitability','Reports','Settings'];
const money=value=>new Intl.NumberFormat('en-LK',{style:'currency',currency:'LKR'}).format(Number(value||0));
const unwrap=response=>response?.data?.data;
const allowed=(...codes)=>codes.some(hasPermission);
const Empty=({children})=><Paper variant="outlined" sx={{p:4,textAlign:'center',color:'text.secondary'}}>{children}</Paper>;
const ErrorBox=({error})=>error?<Alert severity="error">{error}</Alert>:null;
const Loading=()=> <Stack spacing={1}>{[1,2,3].map(id=><Skeleton key={id} height={64}/>)}</Stack>;
const searchResult=response=>response.data.data;
const loadCourses=async(q,page,limit)=>searchResult(await searchCourses(q,page,limit));
const loadBatches=async(q,page,limit,filters)=>searchResult(await searchBatches(q,page,limit,filters));
const loadUsers=async(q,page,limit,filters)=>{const rows=searchResult(await getUsers()).filter(user=>{const text=`${user.firstName||''} ${user.lastName||''} ${user.email||''}`.toLowerCase();const roles=(user.roles||[]).map(role=>String(role.name).toLowerCase());return text.includes(q.toLowerCase())&&(!filters?.role||roles.includes(filters.role));});const start=(page-1)*limit;return{items:rows.slice(start,start+limit),hasMore:start+limit<rows.length};};
const userLabel=user=>`${user?.firstName||''} ${user?.lastName||''}`.trim()||user?.email||'';

export default function CommissionPage(){
 const[tab,setTab]=useState(0),[filters,setFilters]=useState({page:1,limit:25,search:'',status:'',from:'',to:''});
 const[state,setState]=useState({dashboard:null,ledger:null,rules:null,agreements:null,payouts:null,profitability:null,reports:null,reconciliation:null});
 const[loading,setLoading]=useState({}),[errors,setErrors]=useState({}),[dialog,setDialog]=useState(null),[busy,setBusy]=useState(false);
 const setResult=(key,value)=>setState(old=>({...old,[key]:value}));
 const load=useCallback(async(key,request)=>{setLoading(old=>({...old,[key]:true}));setErrors(old=>({...old,[key]:''}));try{setResult(key,unwrap(await request()));}catch(error){setErrors(old=>({...old,[key]:error.response?.data?.message||`Unable to load ${key}.`}));}finally{setLoading(old=>({...old,[key]:false}));}},[]);
 useEffect(()=>{load('dashboard',()=>commissionDashboard(filters));},[filters.from,filters.to,load]);
 useEffect(()=>{if(tab===1||tab===4)load('ledger',()=>listCommissions(filters));if(tab===2)load('rules',()=>listCommissionRules());if(tab===3)load('agreements',()=>listLecturerAgreements());if(tab===5)load('payouts',()=>listPayouts(filters));if(tab===6)load('profitability',()=>commissionProfitability(filters));if(tab===7)load('reports',()=>commissionReport('summary',filters));if(tab===8)load('reconciliation',commissionReconciliation);},[tab,filters,load]);
 const action=async work=>{setBusy(true);try{await work();setDialog(null);if(tab===1||tab===4)await load('ledger',()=>listCommissions(filters));if(tab===2)await load('rules',()=>listCommissionRules());if(tab===3)await load('agreements',()=>listLecturerAgreements());if(tab===5)await load('payouts',()=>listPayouts(filters));}catch(error){setErrors(old=>({...old,action:error.response?.data?.message||error.message}));}finally{setBusy(false);}};
 const rows=state.ledger?.rows||[];
 return <Stack spacing={2.5}>
  <Box><Typography variant="h4" fontWeight={900}>Commission Management</Typography><Typography color="text.secondary">Agent + lecturer earnings, margin, approvals and payouts · Asia/Colombo</Typography></Box>
  <ErrorBox error={errors.action}/>
  <Tabs value={tab} onChange={(_,value)=>setTab(value)} variant="scrollable" scrollButtons="auto">{TABS.map(label=><Tab key={label} label={label}/>)}</Tabs>
  {(tab===0||[1,4,5,6,7].includes(tab))&&<DateFilters value={filters} onChange={setFilters}/>}
  {tab===0&&<Dashboard data={state.dashboard} loading={loading.dashboard} error={errors.dashboard}/>}
  {tab===1&&<Ledger data={state.ledger} loading={loading.ledger} error={errors.ledger} filters={filters} onFilters={setFilters} onView={row=>setDialog({type:'detail',row})}/>}
  {tab===2&&<Rules rows={state.rules||[]} loading={loading.rules} error={errors.rules} onEdit={row=>setDialog({type:'rule',row})} onPreview={()=>setDialog({type:'preview'})}/>}
  {tab===3&&<Agreements rows={state.agreements||[]} loading={loading.agreements} error={errors.agreements} onEdit={row=>setDialog({type:'agreement',row})}/>}
  {tab===4&&<Approvals rows={rows.filter(row=>['pending','under_review','held'].includes(row.status))} loading={loading.ledger} error={errors.ledger} onAct={(row,type)=>setDialog({type:'approval',row,action:type})} onBulk={selected=>setDialog({type:'bulk',ids:selected.map(row=>row.id),rows:selected})}/>}
  {tab===5&&<Payouts data={state.payouts} loading={loading.payouts} error={errors.payouts} onCreate={()=>setDialog({type:'payout'})} onAct={(row,type)=>setDialog({type:'payoutAction',row,action:type})}/>}
  {tab===6&&<Profitability rows={state.profitability||[]} loading={loading.profitability} error={errors.profitability}/>}
  {tab===7&&<Reports data={state.reports} loading={loading.reports} error={errors.reports} filters={filters}/>}
  {tab===8&&<Settings rows={state.reconciliation||[]} loading={loading.reconciliation} error={errors.reconciliation}/>}
  <FinancialDialog dialog={dialog} busy={busy} onClose={()=>setDialog(null)} onSubmit={(kind,payload)=>action(()=>({rule:()=>saveCommissionRule(dialog.row?.id,payload),agreement:()=>saveLecturerAgreement(dialog.row?.id,payload),preview:async()=>setDialog({type:'previewResult',data:unwrap(await previewCommissionRule(payload))}),approval:()=>commissionAction(dialog.row.id,dialog.action,payload),bulk:()=>bulkCommissionApproval({ids:dialog.ids,action:'approve',...payload}),payout:()=>createPayout(payload),payoutAction:()=>payoutAction(dialog.row.id,dialog.action,payload)})[kind]())}/>
 </Stack>;
}

function DateFilters({value,onChange}){return <Paper variant="outlined" sx={{p:1.5}}><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField size="small" type="date" label="From" InputLabelProps={{shrink:true}} value={value.from} onChange={e=>onChange({...value,from:e.target.value,page:1})}/><TextField size="small" type="date" label="To" InputLabelProps={{shrink:true}} value={value.to} onChange={e=>onChange({...value,to:e.target.value,page:1})}/></Stack></Paper>}
function Dashboard({data,loading,error}){if(loading)return <Loading/>;if(error)return <ErrorBox error={error}/>;if(!data)return <Empty>No confirmed-payment commission data yet.</Empty>;return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',md:'repeat(4,1fr)'},gap:2}}>{Object.entries(data).map(([key,value])=><Paper key={key} sx={{p:2}}><Typography variant="caption" color="text.secondary">{key.replaceAll('_',' ')}</Typography><Typography variant="h6" fontWeight={900}>{key.includes('approvals')?value:money(value)}</Typography></Paper>)}</Box>}
function Ledger({data,loading,error,filters,onFilters,onView}){return <Stack spacing={1.5}><TextField size="small" label="Search student, registration, receipt, beneficiary" value={filters.search} onChange={e=>onFilters({...filters,search:e.target.value,page:1})}/><ErrorBox error={error}/>{loading?<Loading/>:!data?.rows?.length?<Empty>No ledger entries match these filters. Only confirmed payments generate entries.</Empty>:data.rows.map(row=><Paper key={row.id} sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={800}>{row.beneficiary?.firstName||row.beneficiary?.email} · {row.earningType?.replaceAll('_',' ')}</Typography><Typography variant="body2" color="text.secondary">{row.student?.name||'Student'} · {row.course?.name||'Course'} · payment #{row.sourcePaymentId}</Typography></Box><Stack direction="row" spacing={1} alignItems="center"><Typography fontWeight={800}>{money(row.amount)}</Typography><Chip size="small" label={row.status}/><Button onClick={()=>onView(row)}>Details</Button></Stack></Stack></Paper>)}{data?.pages>1&&<Stack direction="row" justifyContent="center" spacing={1}><Button disabled={data.page<=1} onClick={()=>onFilters({...filters,page:data.page-1})}>Previous</Button><Typography sx={{pt:1}}>Page {data.page} / {data.pages}</Typography><Button disabled={data.page>=data.pages} onClick={()=>onFilters({...filters,page:data.page+1})}>Next</Button></Stack>}</Stack>}
function Rules({rows,loading,error,onEdit,onPreview}){return <Stack spacing={1.5}><Stack direction="row" spacing={1}>{allowed('commission.rule_manage','commission.manage_rules')&&<Button variant="contained" onClick={()=>onEdit(null)}>New rule</Button>}<Button onClick={onPreview}>Preview / Test</Button></Stack><ErrorBox error={error}/>{loading?<Loading/>:!rows.length?<Empty>No rules exist. Create a draft, validate it, then activate it.</Empty>:rows.map(row=><Paper key={row.id} sx={{p:2}} onClick={()=>onEdit(row)}><Typography fontWeight={800}>{row.name}</Typography><Typography color="text.secondary">{row.earningType} · {row.scopeType} · {row.calculationType} · {row.status}</Typography></Paper>)}</Stack>}
function Agreements({rows,loading,error,onEdit}){return <Stack spacing={1.5}>{allowed('commission.lecturer_agreement_manage')&&<Button variant="contained" sx={{alignSelf:'start'}} onClick={()=>onEdit(null)}>New lecturer agreement</Button>}<ErrorBox error={error}/>{loading?<Loading/>:!rows.length?<Empty>No lecturer agreements configured.</Empty>:rows.map(row=><Paper key={row.id} sx={{p:2}} onClick={()=>onEdit(row)}><Typography fontWeight={800}>{row.lecturer?.firstName||row.lecturer?.email} · {row.course?.name}</Typography><Typography color="text.secondary">{row.calculationType} · {row.percentageRate?`${row.percentageRate}%`:money(row.fixedAmount)} · {row.status}</Typography></Paper>)}</Stack>}
function Approvals({rows,loading,error,onAct,onBulk}){const[selected,setSelected]=useState([]);if(loading)return <Loading/>;const selectedRows=rows.filter(row=>selected.includes(row.id));return <Stack spacing={1}><ErrorBox error={error}/>{selected.length>0&&<Alert severity="warning" action={<Button onClick={()=>onBulk(selectedRows)}>Review bulk approval</Button>}>{selected.length} entries · {money(selectedRows.reduce((sum,row)=>sum+Number(row.amount),0))} total · verify beneficiaries before approving.</Alert>}{!rows.length?<Empty>No ledger entries are waiting for approval.</Empty>:rows.map(row=><Paper key={row.id} sx={{p:2}}><Stack direction="row" justifyContent="space-between" alignItems="center"><Stack direction="row" alignItems="center"><Checkbox checked={selected.includes(row.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,row.id]:old.filter(id=>id!==row.id))}/><Typography>{row.beneficiary?.email} · {money(row.amount)}</Typography></Stack>{allowed('commission.approve')&&<Stack direction="row"><Button onClick={()=>onAct(row,'approve')}>Approve</Button><Button color="warning" onClick={()=>onAct(row,'hold')}>Hold</Button><Button color="error" onClick={()=>onAct(row,'reject')}>Reject</Button></Stack>}</Stack></Paper>)}</Stack>}
function Payouts({data,loading,error,onCreate,onAct}){return <Stack spacing={1.5}>{allowed('commission.payout_create','commission.create_payout')&&<Button variant="contained" sx={{alignSelf:'start'}} onClick={onCreate}>Create payout</Button>}<ErrorBox error={error}/>{loading?<Loading/>:!data?.rows?.length?<Empty>No payouts created.</Empty>:data.rows.map(row=><Paper key={row.id} sx={{p:2}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between"><Box><Typography fontWeight={800}>{row.payoutNumber}</Typography><Typography>{row.beneficiaryType} #{row.beneficiaryId} · {money(row.actualPaid)} / {money(row.netPayable)}</Typography></Box><Stack direction="row"><Chip label={row.status}/>{row.status==='draft'&&<Button onClick={()=>onAct(row,'approve')}>Approve</Button>}{['approved','partially_paid'].includes(row.status)&&<Button onClick={()=>onAct(row,'pay')}>Record payment</Button>}</Stack></Stack></Paper>)}</Stack>}
function Profitability({rows,loading,error}){if(loading)return <Loading/>;return <Stack spacing={1}><ErrorBox error={error}/>{!rows.length?<Empty>No profitability data is available.</Empty>:rows.map((row,index)=><Paper key={`${row.course_id}-${row.batch_id}-${index}`} sx={{p:2}}><Typography fontWeight={800}>Course #{row.course_id} {row.batch_id&&`· Batch #${row.batch_id}`}</Typography><Typography>Revenue {money(row.gross_revenue)} · commissions {money(row.commissions)} · contribution {money(row.contribution_margin)} · net margin {money(row.net_margin)}</Typography></Paper>)}</Stack>}
function Reports({data,loading,error,filters}){const download=async name=>{const response=await exportCommissionReport(name,filters);const url=URL.createObjectURL(response.data);const link=document.createElement('a');link.href=url;link.download=`${name}.csv`;link.click();URL.revokeObjectURL(url);};if(loading)return <Loading/>;return <Stack spacing={1}><ErrorBox error={error}/><Typography color="text.secondary">Commission summary, agent/lecturer earnings, payout register, reversals and reconciliation are exported from permission-scoped backend data.</Typography>{allowed('commission.export')&&<Stack direction="row" flexWrap="wrap" gap={1}>{['summary','agent-earnings','lecturer-earnings','payout-register','reversals','reconciliation'].map(name=><Button variant="outlined" key={name} onClick={()=>download(name)}>{name.replaceAll('-',' ')}</Button>)}</Stack>}{!data?.rows?.length?<Empty>No report rows match the selected dates.</Empty>:<Typography>{data.total} report rows</Typography>}</Stack>}
function Settings({rows,loading,error}){if(loading)return <Loading/>;return <Stack><ErrorBox error={error}/><Typography variant="h6">Accounting synchronization</Typography>{!rows.length?<Alert severity="success">No payout/accounting mismatches detected.</Alert>:rows.map(row=><Alert severity="warning" key={row.id}>{row.payout_number}: expected {money(row.actual_paid)}, accounting {money(row.accounting_amount)}</Alert>)}</Stack>}

function FinancialDialog({dialog,busy,onClose,onSubmit}){const[form,setForm]=useState({});useEffect(()=>setForm(dialog?.row||{}),[dialog]);if(!dialog)return null;if(dialog.type==='detail'||dialog.type==='previewResult')return <Dialog open maxWidth="md" fullWidth onClose={onClose}><DialogTitle>Calculation breakdown</DialogTitle><DialogContent><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(dialog.row||dialog.data,null,2)}</pre></DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>;
 const field=(name,label,type='text')=><TextField fullWidth margin="dense" name={name} label={label} type={type} InputLabelProps={type==='date'?{shrink:true}:undefined} value={form[name]??''} onChange={e=>setForm(old=>({...old,[name]:e.target.value}))}/>;
 let title='Confirm financial action',kind=dialog.type,content=<>{field('comment','Comment / reason')}</>;
 if(dialog.type==='rule'){title=dialog.row?'Edit rule':'New rule';content=<>{field('name','Rule name')}{field('earningType','Earning type')}{field('scopeType','Scope type')}{field('scopeId','Scope ID')}{field('calculationType','Calculation type')}{field('percentageRate','Percentage rate')}{field('fixedAmount','Fixed amount')}{field('effectiveFrom','Effective from','date')}<TextField select fullWidth margin="dense" label="Status" value={form.status||'draft'} onChange={e=>setForm({...form,status:e.target.value})}><MenuItem value="draft">Draft</MenuItem><MenuItem value="active">Active</MenuItem><MenuItem value="paused">Paused</MenuItem></TextField></>}
 if(dialog.type==='agreement'){title=dialog.row?'Edit agreement':'New lecturer agreement';content=<Stack spacing={1.5} sx={{pt:1}}><AsyncSearchSelect label="Lecturer" value={form.lecturerUserId} selectedOption={dialog.row?.lecturer} filters={{role:'lecturer'}} loadOptions={loadUsers} getOptionLabel={userLabel} onChange={option=>setForm({...form,lecturerUserId:option?.id||''})}/><AsyncSearchSelect label="Course" value={form.courseId} selectedOption={dialog.row?.course} loadOptions={loadCourses} getOptionLabel={option=>option?.name||option?.label||''} onChange={option=>setForm({...form,courseId:option?.id||'',batchId:''})}/><AsyncSearchSelect label="Batch (optional)" value={form.batchId} selectedOption={dialog.row?.batch} filters={{courseId:form.courseId}} loadOptions={loadBatches} getOptionLabel={option=>option?.name||option?.label||''} onChange={option=>setForm({...form,batchId:option?.id||''})}/>{field('startDate','Start date','date')}{field('calculationType','Calculation type')}{field('percentageRate','Percentage rate')}{field('fixedAmount','Fixed amount')}{field('allocationPercentage','Allocation %')}</Stack>}
 if(dialog.type==='preview'){title='Preview / Test rule';content=<>{field('sourcePaymentId','Confirmed payment / installment ID')}</>}
 if(dialog.type==='payout'){title='Create payout';content=<Stack spacing={1.5} sx={{pt:1}}><TextField select label="Beneficiary type" value={form.beneficiaryType||'agent'} onChange={e=>setForm({...form,beneficiaryType:e.target.value,beneficiaryId:''})}><MenuItem value="agent">Agent</MenuItem><MenuItem value="lecturer">Lecturer</MenuItem></TextField><AsyncSearchSelect label={form.beneficiaryType==='lecturer'?'Lecturer':'Agent'} value={form.beneficiaryId} filters={{role:form.beneficiaryType||'agent'}} loadOptions={loadUsers} getOptionLabel={userLabel} onChange={option=>setForm({...form,beneficiaryId:option?.id||''})}/>{field('periodStart','Period start','date')}{field('periodEnd','Period end','date')}{field('adjustments','Adjustments')}{field('deductions','Deductions')}</Stack>}
 if(dialog.type==='payoutAction'){title=dialog.action==='approve'?'Approve payout':'Record payout payment';content=dialog.action==='approve'?<Typography>Confirm approval for {dialog.row.payoutNumber}. You cannot approve your own payout.</Typography>:<>{field('amount','Amount paid')}{field('paymentMethod','Payment method')}{field('bankReference','Bank reference')}</>}
 if(dialog.type==='bulk'){title='Confirm bulk approval';content=<Stack spacing={1}><Alert severity="warning">This approves {dialog.rows.length} immutable ledger entries totaling {money(dialog.rows.reduce((sum,row)=>sum+Number(row.amount),0))}.</Alert><Typography>Beneficiaries: {[...new Set(dialog.rows.map(row=>row.beneficiary?.email||`${row.beneficiaryType} #${row.beneficiaryId}`))].join(', ')}</Typography>{field('comment','Approval comment')}</Stack>}
 return <Dialog open maxWidth="sm" fullWidth onClose={busy?undefined:onClose}><DialogTitle>{title}</DialogTitle><DialogContent>{content}</DialogContent><DialogActions><Button disabled={busy} onClick={onClose}>Cancel</Button><Button variant="contained" disabled={busy} onClick={()=>onSubmit(kind,form)}>{busy?<CircularProgress size={20}/>:dialog.type==='preview'?'Run without saving':'Confirm'}</Button></DialogActions></Dialog>}
