import React from'react';
import{Alert,Box,Button,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControlLabel,Grid,MenuItem,Stack,Switch,TextField,Typography}from'@mui/material';
import{createLeadStatus,deleteLeadStatus,disableLeadStatus,listLeadStatuses,updateLeadStatus}from'../services/leadStatusAdmin.service';
import{hasPermission}from'../utils/access';
const blank={name:'',code:'',color:'#2196f3',category:'open',displayOrder:0,active:true,countsAsConversion:false,terminal:false,reasonRequired:false,followupRequired:false,successfulContact:false,allowedNextStatusIds:[]};
const slug=value=>String(value||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');
export default function LeadStatusSettingsPage(){
 const[rows,setRows]=React.useState([]),[edit,setEdit]=React.useState(null),[errors,setErrors]=React.useState({}),[message,setMessage]=React.useState(null),[saving,setSaving]=React.useState(false);
 const load=React.useCallback(()=>listLeadStatuses().then(({data})=>setRows(data.data)).catch(error=>setMessage({severity:'error',text:error.response?.data?.message||error.message})),[]);
 React.useEffect(()=>{load();},[load]);
 const open=row=>{setErrors({});setEdit(row?{...row}:{...blank,displayOrder:rows.length+1});};
 const changeName=value=>setEdit(current=>({...current,name:value,...(!current.id?{code:slug(value)}:{})}));
 const save=async()=>{const invalid={};if(!edit.name.trim())invalid.name='Display name is required.';if(!edit.code.trim())invalid.code='Canonical key is required.';if(!/^#[0-9a-f]{6}$/i.test(edit.color))invalid.color='Enter a six-digit hex color.';if(!edit.category.trim())invalid.category='Category is required.';setErrors(invalid);if(Object.keys(invalid).length)return;setSaving(true);try{await(edit.id?updateLeadStatus(edit.id,edit):createLeadStatus(edit));setEdit(null);setMessage({severity:'success',text:'Lead status saved.'});await load();}catch(error){setErrors(error.response?.data?.errors||{});setMessage({severity:'error',text:error.response?.data?.message||error.message});}finally{setSaving(false);}};
 const disable=async row=>{await disableLeadStatus(row.id);await load();};
 const remove=async row=>{if(!window.confirm(`Delete unused status "${row.name}"?`))return;try{await deleteLeadStatus(row.id);await load();}catch(error){setMessage({severity:'error',text:error.response?.data?.message||error.message});}};
 return <Stack spacing={2}><Box><Typography variant="h4" fontWeight={900}>Lead Statuses</Typography><Typography color="text.secondary">Configure canonical pipeline and Call Center statuses. Used canonical keys are protected.</Typography></Box>{message&&<Alert severity={message.severity}>{message.text}</Alert>}{hasPermission('lead_statuses.create')&&<Button variant="contained" sx={{alignSelf:'flex-start'}} onClick={()=>open()}>Add status</Button>}
 {rows.map(row=><Stack key={row.id} direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'center'}} spacing={1} sx={{p:2,border:'1px solid',borderColor:'divider',borderRadius:2}}><Stack direction="row" spacing={1} alignItems="center"><Chip label={row.name} sx={{bgcolor:row.color,color:'#fff'}}/><Typography variant="body2">{row.code} · {row.category} · order {row.displayOrder} · {row.usage?.total||0} references</Typography>{!row.active&&<Chip label="Disabled"/>}</Stack><Stack direction="row"><Button disabled={!hasPermission('lead_statuses.update')} onClick={()=>open(row)}>Edit</Button>{row.active&&<Button disabled={!hasPermission('lead_statuses.disable')} onClick={()=>disable(row)}>Disable</Button>}<Button color="error" disabled={!hasPermission('lead_statuses.delete')||row.usage?.total>0} onClick={()=>remove(row)}>Delete</Button></Stack></Stack>)}
 <Dialog open={!!edit} onClose={()=>!saving&&setEdit(null)} fullWidth maxWidth="md"><DialogTitle>{edit?.id?'Edit':'Add'} lead status</DialogTitle><DialogContent><Grid container spacing={2} sx={{pt:1}}><Grid item xs={12} md={6}><TextField fullWidth required label="Display name *" value={edit?.name||''} error={!!errors.name} helperText={errors.name} onChange={e=>changeName(e.target.value)}/></Grid><Grid item xs={12} md={6}><TextField fullWidth required label="Canonical key *" value={edit?.code||''} disabled={!!edit?.id&&edit?.usage?.total>0} error={!!errors.code} helperText={errors.code} onChange={e=>setEdit({...edit,code:slug(e.target.value)})}/></Grid><Grid item xs={12} md={4}><TextField fullWidth required label="Color *" type="color" value={edit?.color||'#2196f3'} error={!!errors.color} helperText={errors.color} onChange={e=>setEdit({...edit,color:e.target.value})}/></Grid><Grid item xs={12} md={4}><TextField fullWidth required label="Category *" value={edit?.category||''} error={!!errors.category} helperText={errors.category} onChange={e=>setEdit({...edit,category:e.target.value})}/></Grid><Grid item xs={12} md={4}><TextField fullWidth type="number" label="Sort order" value={edit?.displayOrder||0} onChange={e=>setEdit({...edit,displayOrder:Number(e.target.value)})}/></Grid><Grid item xs={12}><TextField select fullWidth SelectProps={{multiple:true}} label="Allowed next statuses" value={edit?.allowedNextStatusIds||[]} onChange={e=>setEdit({...edit,allowedNextStatusIds:e.target.value})}>{rows.filter(row=>row.active&&row.id!==edit?.id).map(row=><MenuItem key={row.id} value={row.id}>{row.name}</MenuItem>)}</TextField></Grid>{[['active','Active'],['countsAsConversion','Conversion'],['terminal','Terminal'],['reasonRequired','Reason required'],['followupRequired','Follow-up required'],['successfulContact','Successful contact']].map(([key,label])=><Grid item xs={6} md={4} key={key}><FormControlLabel control={<Switch checked={!!edit?.[key]} onChange={e=>setEdit({...edit,[key]:e.target.checked})}/>} label={label}/></Grid>)}</Grid></DialogContent><DialogActions><Button disabled={saving} onClick={()=>setEdit(null)}>Cancel</Button><Button variant="contained" disabled={saving} onClick={save}>{saving?'Saving…':'Save'}</Button></DialogActions></Dialog></Stack>;
}
