import React, { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import {
  Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Chip, Dialog, DialogActions,
  DialogContent, DialogTitle, Divider, FormControlLabel, Grid, IconButton, MenuItem, Paper, Stack, Switch, Tab, Tabs,
  TextField, Typography
} from '@mui/material';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import AddIcon from '@mui/icons-material/Add';
import ArchiveOutlinedIcon from '@mui/icons-material/ArchiveOutlined';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import DragIndicatorIcon from '@mui/icons-material/DragIndicator';
import EditIcon from '@mui/icons-material/Edit';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import {
  archiveBuilderLesson, archiveLmsCourse, archiveLmsTopic, createBuilderLesson, createLmsCourse,
  createLmsTopic, duplicateBuilderLesson, duplicateLmsCourse, duplicateLmsTopic, getLmsCourse,
  getBuilderLesson, getLmsCurriculum, listLmsCourses, moveBuilderLesson, reorderBuilderLessons, reorderLmsTopics, updateBuilderLesson,
  updateLmsCourse, updateLmsTopic
} from '../services/lms.service';

const courseDefaults = { name: '', code: '', category: '', shortDescription: '', description: '', thumbnailUrl: '', introVideoUrl: '', difficultyLevel: 'beginner', durationMinutes: '', lmsStatus: 'draft', visibility: 'enrolled', dripEnabled: false, defaultDripType: 'immediate', certificateEnabled: false, completionPercentageRequired: 100, allowLessonDownloads: false, allowComments: true };
const lessonDefaults = { title: '', summary: '', lessonType: 'video', status: 'draft', durationMinutes: '', contentHtml: '', recordingUrl: '', bunnyVideoId: '', bunnyEmbedUrl: '', externalUrl: '', externalButtonLabel: 'Open resource', documentUrl: '', liveClassAt: '', zoomLink: '', zoomMeetingId: '', zoomPassword: '', dripType: 'immediate', dripValue: '', dripReleaseAt: '', downloadAllowed: false };
const unwrap = (response) => response.data?.data;

export function LmsCoursesPage() {
  const [courses, setCourses] = useState([]);
  const [form, setForm] = useState(null);
  const [error, setError] = useState('');
  const load = useCallback(async () => { try { setCourses(unwrap(await listLmsCourses()) || []); } catch (e) { setError(e.response?.data?.message || 'Unable to load courses.'); } }, []);
  useEffect(() => { load(); }, [load]);
  const mutate = async (action) => { try { setError(''); await action(); await load(); } catch (e) { setError(e.response?.data?.message || 'Course action failed.'); } };
  return <Stack spacing={3}>
    <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2}><Box><Typography variant="h4" fontWeight={900}>LMS Courses</Typography><Typography color="text.secondary">Build topics, lessons, live classes, recordings and resources in one place.</Typography></Box><Button startIcon={<AddIcon />} variant="contained" onClick={() => setForm(courseDefaults)}>New course</Button></Stack>
    {error && <Alert severity="error">{error}</Alert>}
    <Grid container spacing={2}>{courses.map((course) => <Grid item xs={12} md={6} xl={4} key={course.id}><Paper variant="outlined" sx={{ p: 2.5, height: '100%' }}><Stack spacing={1.5}>
      <Stack direction="row" justifyContent="space-between"><Box><Typography variant="h6" fontWeight={850}>{course.name}</Typography><Typography variant="body2" color="text.secondary">{course.category || course.code || 'Uncategorised'}</Typography></Box><Chip size="small" label={course.lmsStatus || 'draft'} color={course.lmsStatus === 'published' ? 'success' : 'default'} /></Stack>
      <Typography variant="body2">{course.totalTopics || 0} topics · {course.totalLessons || 0} lessons · {course.batches?.length || 0} batches</Typography>
      <Stack direction="row" flexWrap="wrap" gap={1}><Button component={Link} to={`/lms/courses/${course.id}/builder`} variant="contained" size="small">Open builder</Button><Button component={Link} to={`/lms/courses/${course.id}/builder`} startIcon={<EditIcon />} size="small">Edit</Button><IconButton title="Duplicate" onClick={() => mutate(() => duplicateLmsCourse(course.id))}><ContentCopyIcon /></IconButton><IconButton title="Archive" onClick={() => window.confirm('Archive this course?') && mutate(() => archiveLmsCourse(course.id))}><ArchiveOutlinedIcon /></IconButton></Stack>
    </Stack></Paper></Grid>)}</Grid>
    {!courses.length && !error && <Paper variant="outlined" sx={{ p: 6, textAlign: 'center' }}>No LMS courses yet.</Paper>}
    <CourseDialog form={form} onClose={() => setForm(null)} onSave={(payload) => mutate(async () => { await createLmsCourse(payload); setForm(null); })} />
  </Stack>;
}

function CourseDialog({ form, onClose, onSave }) {
  const [value, setValue] = useState(form);
  useEffect(() => setValue(form), [form]);
  if (!value) return null;
  return <Dialog open fullWidth maxWidth="md" onClose={onClose}><DialogTitle>Create LMS course</DialogTitle><DialogContent><Grid container spacing={2} sx={{ mt: .25 }}>
    <Grid item xs={12} sm={8}><TextField fullWidth required label="Course title" value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} /></Grid><Grid item xs={12} sm={4}><TextField fullWidth label="Code" value={value.code} onChange={(e) => setValue({ ...value, code: e.target.value })} /></Grid>
    <Grid item xs={12}><TextField fullWidth multiline minRows={3} label="Description" value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} /></Grid>
  </Grid></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!value.name.trim()} onClick={() => onSave(value)}>Create</Button></DialogActions></Dialog>;
}

export default function LmsCourseBuilderPage() {
  const { courseId } = useParams();
  const navigate = useNavigate();
  const [course, setCourse] = useState(courseDefaults);
  const [topics, setTopics] = useState([]);
  const [tab, setTab] = useState(0);
  const [dirty, setDirty] = useState(false);
  const [topicForm, setTopicForm] = useState(null);
  const [lessonForm, setLessonForm] = useState(null);
  const [dragged, setDragged] = useState(null);
  const [error, setError] = useState('');
  const load = useCallback(async () => { try { const [courseResponse, curriculumResponse] = await Promise.all([getLmsCourse(courseId), getLmsCurriculum(courseId)]); setCourse({ ...courseDefaults, ...unwrap(courseResponse) }); setTopics(unwrap(curriculumResponse) || []); setDirty(false); } catch (e) { setError(e.response?.data?.message || 'Unable to load course builder.'); } }, [courseId]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const warn = (event) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  const mutate = async (action) => { try { setError(''); await action(); await load(); } catch (e) { setError(e.response?.data?.message || 'Unable to save changes.'); } };
  const saveCourse = () => mutate(() => updateLmsCourse(courseId, course));
  const reorderTopic = (index, delta) => { const next = [...topics]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setTopics(next); mutate(() => reorderLmsTopics(next.map((item, sortOrder) => ({ id: item.id, sortOrder })))); };
  const dropTopic = (targetIndex) => { if (dragged?.kind !== 'topic') return; const next = [...topics]; const [item] = next.splice(dragged.index, 1); next.splice(targetIndex, 0, item); setDragged(null); setTopics(next); mutate(() => reorderLmsTopics(next.map((topic, sortOrder) => ({ id: topic.id, sortOrder })))); };
  const reorderLesson = (topic, index, delta) => { const lessons = [...topic.lessons]; const target = index + delta; if (target < 0 || target >= lessons.length) return; [lessons[index], lessons[target]] = [lessons[target], lessons[index]]; mutate(() => reorderBuilderLessons(lessons.map((item, sortOrder) => ({ id: item.id, topicId: topic.id, sortOrder })))); };
  return <Stack spacing={2.5}>
    <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={2}><Box><Button onClick={() => navigate('/lms/courses')}>← Courses</Button><Typography variant="h4" fontWeight={900}>{course.name || 'Course builder'}</Typography><Typography color="text.secondary">Course → Topic → Lesson curriculum</Typography></Box><Stack direction="row" alignItems="center" spacing={1}><Chip label={course.lmsStatus || 'draft'} color={course.lmsStatus === 'published' ? 'success' : 'default'} /><Button variant="contained" onClick={saveCourse}>Save course</Button></Stack></Stack>
    {error && <Alert severity="error">{error}</Alert>}
    <Paper variant="outlined"><Tabs value={tab} onChange={(_, value) => setTab(value)}><Tab label="Basics" /><Tab label="Curriculum" /><Tab label="Settings" /></Tabs><Divider />
      {tab === 0 && <CourseFields course={course} setCourse={(next) => { setCourse(next); setDirty(true); }} />}
      {tab === 1 && <Box sx={{ p: { xs: 1.5, md: 3 } }}><Stack direction="row" justifyContent="space-between" sx={{ mb: 2 }}><Typography variant="h6" fontWeight={850}>Curriculum</Typography><Button startIcon={<AddIcon />} onClick={() => setTopicForm({ title: '', summary: '', status: 'published' })}>Add topic</Button></Stack>
        {topics.map((topic, topicIndex) => <Accordion key={topic.id} defaultExpanded draggable onDragStart={() => setDragged({ kind: 'topic', index: topicIndex })} onDragOver={(e) => e.preventDefault()} onDrop={() => dropTopic(topicIndex)}><AccordionSummary expandIcon={<ExpandMoreIcon />}><DragIndicatorIcon color="disabled" sx={{ mr: 1 }} /><Box sx={{ flex: 1 }}><Typography fontWeight={850}>{topic.title}</Typography><Typography variant="caption">{topic.lessons?.length || 0} lessons</Typography></Box><Button size="small" onClick={(e) => { e.stopPropagation(); reorderTopic(topicIndex, -1); }}>↑</Button><Button size="small" onClick={(e) => { e.stopPropagation(); reorderTopic(topicIndex, 1); }}>↓</Button></AccordionSummary><AccordionDetails onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.stopPropagation(); if (dragged?.kind === 'lesson' && String(dragged.topicId) !== String(topic.id)) mutate(() => moveBuilderLesson(dragged.id, topic.id, topic.lessons?.length || 0)); setDragged(null); }}><Stack spacing={1}>
          {(topic.lessons || []).map((lesson, lessonIndex) => <Paper variant="outlined" key={lesson.id} draggable onDragStart={(e) => { e.stopPropagation(); setDragged({ kind: 'lesson', id: lesson.id, topicId: topic.id }); }} sx={{ p: 1.25 }}><Stack direction={{ xs: 'column', sm: 'row' }} alignItems={{ sm: 'center' }} gap={1}><DragIndicatorIcon color="disabled" /><Box sx={{ flex: 1 }}><Typography fontWeight={700}>{lesson.title}</Typography><Stack direction="row" spacing={.75}><Chip size="small" label={lesson.lessonType || 'video'} /><Chip size="small" label={lesson.status || 'draft'} color={lesson.status === 'published' ? 'success' : 'default'} /></Stack></Box><Button size="small" onClick={() => reorderLesson(topic, lessonIndex, -1)}>↑</Button><Button size="small" onClick={() => reorderLesson(topic, lessonIndex, 1)}>↓</Button><IconButton onClick={async () => { try { const full = unwrap(await getBuilderLesson(lesson.id)); setLessonForm({ originalTopicId: topic.id, topicId: topic.id, ...lessonDefaults, ...full }); } catch (e) { setError(e.response?.data?.message || 'Unable to open lesson.'); } }}><EditIcon /></IconButton><IconButton onClick={() => mutate(() => duplicateBuilderLesson(lesson.id))}><ContentCopyIcon /></IconButton><IconButton onClick={() => window.confirm('Archive this lesson?') && mutate(() => archiveBuilderLesson(lesson.id))}><ArchiveOutlinedIcon /></IconButton></Stack></Paper>)}
          <Stack direction="row" gap={1}><Button startIcon={<AddIcon />} onClick={() => setLessonForm({ topicId: topic.id, ...lessonDefaults })}>Add lesson</Button><Button onClick={() => setTopicForm(topic)}>Edit topic</Button><Button onClick={() => mutate(() => duplicateLmsTopic(topic.id))}>Duplicate topic</Button><Button color="error" onClick={() => window.confirm('Archive this topic and hide its lessons?') && mutate(() => archiveLmsTopic(topic.id))}>Archive</Button></Stack>
        </Stack></AccordionDetails></Accordion>)}
      </Box>}
      {tab === 2 && <SettingsFields course={course} setCourse={(next) => { setCourse(next); setDirty(true); }} />}
    </Paper>
    <TopicDialog value={topicForm} onClose={() => setTopicForm(null)} onSave={(payload) => mutate(async () => { if (payload.id) await updateLmsTopic(payload.id, payload); else await createLmsTopic(courseId, payload); setTopicForm(null); })} />
    <LessonDialog value={lessonForm} topics={topics} batches={course.batches || []} onClose={() => setLessonForm(null)} onSave={(payload) => mutate(async () => { const safePayload = { ...payload }; if (safePayload.id && !safePayload.zoomPassword) delete safePayload.zoomPassword; safePayload.batchOverrides = (safePayload.batchOverrides || []).map((item) => { const next = { ...item }; if (!next.zoomPassword) delete next.zoomPassword; return next; }); if (safePayload.id) { await updateBuilderLesson(safePayload.id, safePayload); if (String(safePayload.topicId) !== String(safePayload.originalTopicId)) await moveBuilderLesson(safePayload.id, safePayload.topicId); } else await createBuilderLesson(safePayload.topicId, safePayload); setLessonForm(null); })} />
  </Stack>;
}

function CourseFields({ course, setCourse }) { return <Grid container spacing={2} sx={{ p: 3 }}><Grid item xs={12} md={8}><TextField fullWidth label="Course title" value={course.name || ''} onChange={(e) => setCourse({ ...course, name: e.target.value })} /></Grid><Grid item xs={12} md={4}><TextField fullWidth label="Code" value={course.code || ''} onChange={(e) => setCourse({ ...course, code: e.target.value })} /></Grid><Grid item xs={12}><TextField fullWidth label="Short description" value={course.shortDescription || ''} onChange={(e) => setCourse({ ...course, shortDescription: e.target.value })} /></Grid><Grid item xs={12} md={6}><TextField fullWidth label="Category" value={course.category || ''} onChange={(e) => setCourse({ ...course, category: e.target.value })} /></Grid><Grid item xs={12} md={6}><TextField select fullWidth label="Difficulty" value={course.difficultyLevel || 'beginner'} onChange={(e) => setCourse({ ...course, difficultyLevel: e.target.value })}>{['beginner', 'intermediate', 'advanced'].map((v) => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField></Grid><Grid item xs={12}><TextField fullWidth multiline minRows={4} label="Full description" value={course.description || ''} onChange={(e) => setCourse({ ...course, description: e.target.value })} /></Grid><Grid item xs={12} md={6}><TextField fullWidth label="Thumbnail URL" value={course.thumbnailUrl || ''} onChange={(e) => setCourse({ ...course, thumbnailUrl: e.target.value })} /></Grid><Grid item xs={12} md={6}><TextField fullWidth label="Intro video URL" value={course.introVideoUrl || ''} onChange={(e) => setCourse({ ...course, introVideoUrl: e.target.value })} /></Grid><Grid item xs={6} md={3}><TextField fullWidth type="number" label="Duration (minutes)" value={course.durationMinutes || ''} onChange={(e) => setCourse({ ...course, durationMinutes: e.target.value })} /></Grid><Grid item xs={6} md={3}><TextField fullWidth type="number" label="Course fee" value={course.feeAmount || ''} onChange={(e) => setCourse({ ...course, feeAmount: e.target.value })} /></Grid><Grid item xs={6} md={3}><TextField fullWidth type="number" label="Instructor user ID" value={course.instructorId || ''} onChange={(e) => setCourse({ ...course, instructorId: e.target.value })} /></Grid><Grid item xs={6} md={3}><TextField fullWidth type="number" label="Course order" value={course.courseOrder || 0} onChange={(e) => setCourse({ ...course, courseOrder: e.target.value })} /></Grid><Grid item xs={12}><Typography variant="body2" color="text.secondary">Assigned batches: {course.batches?.map((batch) => batch.name).join(', ') || 'None. Assign batches from the existing Batches module.'}</Typography></Grid></Grid>; }
function SettingsFields({ course, setCourse }) { const toggle = (name) => (_, checked) => setCourse({ ...course, [name]: checked }); return <Grid container spacing={2} sx={{ p: 3 }}><Grid item xs={12} md={4}><TextField select fullWidth label="Status" value={course.lmsStatus || 'draft'} onChange={(e) => setCourse({ ...course, lmsStatus: e.target.value })}>{['draft', 'published', 'archived'].map((v) => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField></Grid><Grid item xs={12} md={4}><TextField select fullWidth label="Visibility" value={course.visibility || 'enrolled'} onChange={(e) => setCourse({ ...course, visibility: e.target.value })}>{[['public', 'Public'], ['enrolled', 'Enrolled students only'], ['selected_batches', 'Selected batches only']].map(([v, label]) => <MenuItem key={v} value={v}>{label}</MenuItem>)}</TextField></Grid><Grid item xs={12} md={4}><TextField fullWidth type="number" label="Completion required %" value={course.completionPercentageRequired || 100} onChange={(e) => setCourse({ ...course, completionPercentageRequired: e.target.value })} /></Grid><Grid item xs={12} md={4}><TextField fullWidth type="datetime-local" InputLabelProps={{ shrink: true }} label="Enrollment starts" value={course.enrollmentStartAt?.slice?.(0, 16) || ''} onChange={(e) => setCourse({ ...course, enrollmentStartAt: e.target.value })} /></Grid><Grid item xs={12} md={4}><TextField fullWidth type="datetime-local" InputLabelProps={{ shrink: true }} label="Enrollment ends" value={course.enrollmentEndAt?.slice?.(0, 16) || ''} onChange={(e) => setCourse({ ...course, enrollmentEndAt: e.target.value })} /></Grid><Grid item xs={12} md={4}><TextField fullWidth type="number" disabled={course.lifetimeAccess} label="Expires after days" value={course.expiresAfterDays || ''} onChange={(e) => setCourse({ ...course, expiresAfterDays: e.target.value })} /></Grid><Grid item xs={12}><Stack direction={{ xs: 'column', md: 'row' }}><FormControlLabel control={<Switch checked={Boolean(course.lifetimeAccess)} onChange={toggle('lifetimeAccess')} />} label="Lifetime access" /><FormControlLabel control={<Switch checked={Boolean(course.dripEnabled)} onChange={toggle('dripEnabled')} />} label="Drip content" /><FormControlLabel control={<Switch checked={Boolean(course.certificateEnabled)} onChange={toggle('certificateEnabled')} />} label="Certificate" /><FormControlLabel control={<Switch checked={Boolean(course.allowLessonDownloads)} onChange={toggle('allowLessonDownloads')} />} label="Downloads" /><FormControlLabel control={<Switch checked={Boolean(course.allowComments)} onChange={toggle('allowComments')} />} label="Comments / questions" /></Stack></Grid><Grid item xs={12}><Alert severity="info">Enrollment, payment and batch checks still apply in the student portal. Live URLs are released only by the secure join endpoint.</Alert></Grid></Grid>; }

function TopicDialog({ value, onClose, onSave }) { const [form, setForm] = useState(value); useEffect(() => setForm(value), [value]); if (!form) return null; return <Dialog open fullWidth onClose={onClose}><DialogTitle>{form.id ? 'Edit topic' : 'Add topic'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label="Title" value={form.title || ''} onChange={(e) => setForm({ ...form, title: e.target.value })} /><TextField multiline minRows={3} label="Summary" value={form.summary || ''} onChange={(e) => setForm({ ...form, summary: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={() => onSave(form)}>Save</Button></DialogActions></Dialog>; }

function LessonDialog({ value, topics, batches, onClose, onSave }) {
  const theme = useTheme();
  const fullScreen = useMediaQuery(theme.breakpoints.down('sm'));
  const [form, setForm] = useState(value);
  const [tab, setTab] = useState(0);
  useEffect(() => { setForm(value); setTab(0); }, [value]);
  if (!form) return null;
  const field = (name, label, props = {}) => <TextField fullWidth label={label} value={form[name] || ''} onChange={(e) => setForm({ ...form, [name]: e.target.value })} {...props} />;
  const overrideFor = (batchId) => (form.batchOverrides || []).find((item) => String(item.batchId) === String(batchId)) || { batchId, status: 'published' };
  const setOverride = (batchId, name, nextValue) => {
    const current = form.batchOverrides || [];
    const next = current.filter((item) => String(item.batchId) !== String(batchId));
    next.push({ ...overrideFor(batchId), [name]: nextValue });
    setForm({ ...form, batchOverrides: next });
  };
  return <Dialog open fullWidth maxWidth="md" fullScreen={fullScreen} onClose={onClose}><DialogTitle>{form.id ? 'Edit lesson' : 'Add lesson'}</DialogTitle><DialogContent>
    <Tabs value={tab} onChange={(_, next) => setTab(next)} variant="scrollable"><Tab label="General" /><Tab label="Content" /><Tab label="Access & Drip" /></Tabs>
    <Stack spacing={2} sx={{ mt: 2 }}>
      {tab === 0 && <>{field('title', 'Lesson title')}<TextField select fullWidth label="Topic" value={form.topicId} onChange={(e) => setForm({ ...form, topicId: e.target.value })}>{topics.map((topic) => <MenuItem key={topic.id} value={topic.id}>{topic.title}</MenuItem>)}</TextField><TextField select fullWidth label="Lesson type" value={form.lessonType} onChange={(e) => setForm({ ...form, lessonType: e.target.value })}>{['video', 'live', 'text', 'document', 'external', 'assignment', 'quiz'].map((type) => <MenuItem key={type} value={type}>{type}</MenuItem>)}</TextField>{field('summary', 'Summary', { multiline: true, minRows: 2 })}{field('description', 'Description', { multiline: true, minRows: 3 })}{field('lecturerId', 'Lecturer user ID', { type: 'number' })}{field('durationMinutes', 'Duration (minutes)', { type: 'number' })}</>}
      {tab === 1 && <>{['text', 'assignment', 'quiz'].includes(form.lessonType) && field('contentHtml', 'Lesson content', { multiline: true, minRows: 7 })}{form.lessonType === 'video' && <>{field('recordingUrl', 'Recording URL')}{field('bunnyVideoId', 'Bunny video ID')}{field('bunnyEmbedUrl', 'Bunny embed URL')}{field('embedCode', 'Bunny embed code', { multiline: true, minRows: 3 })}{field('thumbnailUrl', 'Thumbnail URL')}</>}{form.lessonType === 'live' && <>{field('liveClassAt', 'Class time', { type: 'datetime-local', InputLabelProps: { shrink: true } })}{field('zoomLink', 'Zoom join URL')}{field('zoomMeetingId', 'Meeting ID')}{field('zoomPassword', 'Password', { type: 'password' })}{field('joinButtonLabel', 'Join button label')}{field('allowJoinBeforeMinutes', 'Allow join before minutes', { type: 'number' })}{field('allowJoinAfterMinutes', 'Allow join after minutes', { type: 'number' })}{field('recordingUrl', 'Optional recording URL')}</>}{form.lessonType === 'external' && <>{field('externalUrl', 'External URL')}{field('externalButtonLabel', 'Button label')}</>}{form.lessonType === 'document' && field('documentUrl', 'Document URL')}</>}
      {tab === 2 && <><TextField select fullWidth label="Status" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{['draft', 'published'].map((status) => <MenuItem key={status} value={status}>{status}</MenuItem>)}</TextField><TextField select fullWidth label="Drip rule" value={form.dripType} onChange={(e) => setForm({ ...form, dripType: e.target.value })}>{['immediate', 'specific_date', 'days_after_enrollment', 'days_after_previous_completion', 'manual'].map((rule) => <MenuItem key={rule} value={rule}>{rule.replaceAll('_', ' ')}</MenuItem>)}</TextField>{form.dripType === 'specific_date' && field('dripReleaseAt', 'Release at', { type: 'datetime-local', InputLabelProps: { shrink: true } })}{['days_after_enrollment', 'days_after_previous_completion'].includes(form.dripType) && field('dripValue', 'Days', { type: 'number' })}<FormControlLabel control={<Switch checked={Boolean(form.downloadAllowed)} onChange={(_, checked) => setForm({ ...form, downloadAllowed: checked })} />} label="Allow download" />{batches.length > 0 && <><Divider /><Typography fontWeight={850}>Optional batch overrides</Typography>{batches.map((batch) => { const item = overrideFor(batch.id); return <Paper variant="outlined" sx={{ p: 2 }} key={batch.id}><Typography fontWeight={750} sx={{ mb: 1.5 }}>{batch.name}</Typography><Grid container spacing={1.5}><Grid item xs={12} md={4}><TextField fullWidth type="datetime-local" InputLabelProps={{ shrink: true }} label="Live date/time" value={item.liveClassAt?.slice?.(0, 16) || ''} onChange={(e) => setOverride(batch.id, 'liveClassAt', e.target.value)} /></Grid><Grid item xs={12} md={4}><TextField fullWidth label="Zoom link" value={item.zoomLink || ''} onChange={(e) => setOverride(batch.id, 'zoomLink', e.target.value)} /></Grid><Grid item xs={12} md={4}><TextField fullWidth type="datetime-local" InputLabelProps={{ shrink: true }} label="Drip date" value={item.dripReleaseAt?.slice?.(0, 16) || ''} onChange={(e) => setOverride(batch.id, 'dripReleaseAt', e.target.value)} /></Grid><Grid item xs={12} md={4}><TextField select fullWidth label="Batch status" value={item.status || 'published'} onChange={(e) => setOverride(batch.id, 'status', e.target.value)}><MenuItem value="published">Published</MenuItem><MenuItem value="hidden">Hidden</MenuItem></TextField></Grid></Grid></Paper>; })}</>}</>}
    </Stack>
  </DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!form.title?.trim()} onClick={() => onSave(form)}>Save lesson</Button></DialogActions></Dialog>;
}
