import React from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, MenuItem, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { Add, ArrowDownward, ArrowUpward, ContentCopy, Delete } from '@mui/icons-material';
import * as service from '../services/reminderSequence.service';
import WhatsAppAccountSelect from '../components/WhatsAppAccountSelect';

const blankStep=()=>({delayValue:1,delayUnit:'hours',messageMode:'automatic',sessionMessageType:'text',body:'',footer:'',mediaConfig:{},interactiveConfig:{buttons:[]},templateId:'',templateLanguage:'en_US',fallbackVariableMapping:{},enabled:true});
const invalidFields=(form,activation=false)=>{const errors={};if(!form?.name?.trim())errors.name='Sequence name is required.';if(!form?.steps?.length)errors.steps='Add at least one reminder step.';(form?.steps||[]).forEach((step,index)=>{const key=`steps.${index}`;if(!Number.isInteger(Number(step.delayValue))||Number(step.delayValue)<(activation?1:0))errors[`${key}.delayValue`]=activation?'Send after must be a positive whole number.':'Send after must be zero or more.';if(!['minutes','hours','days'].includes(step.delayUnit))errors[`${key}.delayUnit`]='Choose a valid unit.';if(step.enabled!==false&&!step.body?.trim())errors[`${key}.body`]='Message body/caption is required.';if(['image','image_buttons'].includes(step.sessionMessageType)&&!step.mediaConfig?.mediaId)errors[`${key}.mediaConfig`]='Select or upload an image for this WhatsApp account.';const buttons=step.interactiveConfig?.buttons||[];if(['buttons','image_buttons'].includes(step.sessionMessageType)&&!buttons.length)errors[`${key}.buttons`]='Add at least one quick-reply button.';if(buttons.length>3)errors[`${key}.buttons`]='WhatsApp supports at most 3 reply buttons.';const ids=buttons.map(b=>b.buttonId),titles=buttons.map(b=>b.title);if(new Set(ids).size!==ids.length)errors[`${key}.buttons`]='Button IDs must be unique.';if(new Set(titles).size!==titles.length)errors[`${key}.buttons`]='Button titles must be unique.';buttons.forEach((b,i)=>{if(!b.title?.trim()||b.title.length>20)errors[`${key}.buttons.${i}.title`]='Button title must contain 1 to 20 characters.';if(!b.buttonId?.trim()||/\\s/.test(b.buttonId))errors[`${key}.buttons.${i}.buttonId`]='Stable button ID is required and cannot contain spaces.';if(b.behavior==='trigger_keyword'&&!b.triggerKeyword?.trim())errors[`${key}.buttons.${i}.triggerKeyword`]='Trigger keyword is required.'});});return errors};

export default function ReminderSequencesPage(){
 const[tab,setTab]=React.useState(0),[rows,setRows]=React.useState([]),[stats,setStats]=React.useState({}),[edit,setEdit]=React.useState(null),[error,setError]=React.useState(''),[notice,setNotice]=React.useState(''),[errors,setErrors]=React.useState({}),[busy,setBusy]=React.useState(false);
 const load=React.useCallback(async()=>{try{const[a,b]=await Promise.all([service.listSequences(),service.getReminderDashboard()]);setRows(a.data.data.rows);setStats(b.data.data)}catch(e){setError(e.response?.data?.message||e.message)}},[]);
 React.useEffect(()=>{load()},[load]);
 const failure=e=>{const fields=e.response?.data?.errors||{};setErrors(fields);setError(Object.values(fields)[0]||e.response?.data?.message||e.message)};
 const save=async activate=>{if(busy)return;const invalid=invalidFields(edit,activate);setErrors(invalid);if(Object.keys(invalid).length){requestAnimationFrame(()=>document.querySelector('[aria-invalid="true"]')?.focus());return}setBusy(true);setError('');setNotice('');try{const saved=(await service.saveSequence(edit.id,edit)).data.data;if(activate){const result=(await service.changeSequenceStatus(saved.id,'active')).data.data;setNotice(result.warnings?.[0]?.message||'Reminder sequence activated and is now available in Flow Builder.')}else setNotice('Reminder sequence saved.');setEdit(null);await load()}catch(e){failure(e)}finally{setBusy(false)}};
 const changeStatus=async(row,status)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const result=(await service.changeSequenceStatus(row.id,status)).data.data;setNotice(result.warnings?.[0]?.message||`Sequence ${status}.`);await load()}catch(e){failure(e)}finally{setBusy(false)}};
 const duplicate=async row=>{if(busy)return;setBusy(true);try{await service.duplicateSequence(row.id);setNotice('Draft copy created.');await load()}catch(e){failure(e)}finally{setBusy(false)}};
 const move=(i,d)=>setEdit(current=>{const steps=[...current.steps],target=i+d;if(target<0||target>=steps.length)return current;[steps[i],steps[target]]=[steps[target],steps[i]];return{...current,steps}});
 const patchStep=(index,values)=>setEdit(current=>({...current,steps:current.steps.map((step,i)=>i===index?{...step,...values}:step)}));
 return <Box><Typography variant="h4" gutterBottom>Reminder Sequences</Typography>{error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}{notice&&<Alert severity="success" onClose={()=>setNotice('')}>{notice}</Alert>}
 <Grid container spacing={2} sx={{mb:2}}>{[['Active sequences','activeSequences'],['Active subscriptions','activeSubscriptions'],['Due next hour','dueNextHour'],['Sent today','sentToday'],['Failed today','failedToday'],['Stopped by reply','stoppedByReply']].map(([label,key])=><Grid item xs={6} md={2} key={key}><Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4">{stats[key]||0}</Typography></CardContent></Card></Grid>)}</Grid>
 <Tabs value={tab} onChange={(_,value)=>setTab(value)}><Tab label="Sequences"/><Tab label="Subscriptions"/><Tab label="Scheduled reminders"/><Tab label="Execution history"/><Tab label="Settings"/></Tabs>
 {tab===0&&<Stack spacing={1} sx={{mt:2}}><Button variant="contained" startIcon={<Add/>} onClick={()=>{setErrors({});setEdit({name:'',description:'',status:'draft',timezone:'Asia/Colombo',stopOnCustomerReply:true,steps:[blankStep()]})}}>Create sequence</Button>{rows.map(row=><Card key={row.id}><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={1}><Box><Typography variant="h6">{row.name}</Typography><Typography color="text.secondary">{row.description||'No description'} · {row.steps.length} steps</Typography></Box><Stack direction="row" spacing={1} flexWrap="wrap"><Chip label={row.status} color={row.status==='active'?'success':row.status==='paused'?'warning':'default'}/><Button size="small" onClick={()=>{setErrors({});setEdit({...row,steps:row.steps||[]})}}>Edit</Button><Button size="small" disabled={busy} onClick={()=>duplicate(row)}>Duplicate</Button>{row.status==='draft'&&<Button size="small" variant="contained" disabled={busy} onClick={()=>changeStatus(row,'active')}>Activate</Button>}{row.status==='active'&&<Button size="small" disabled={busy} onClick={()=>changeStatus(row,'paused')}>Pause</Button>}{row.status==='paused'&&<Button size="small" variant="contained" disabled={busy} onClick={()=>changeStatus(row,'active')}>Resume</Button>}{row.status!=='archived'&&<Button size="small" color="error" disabled={busy} onClick={()=>changeStatus(row,'archived')}>Archive</Button>}</Stack></Stack></CardContent></Card>)}</Stack>}
 {tab>0&&<Alert severity="info" sx={{mt:2}}>Use the filters and paginated API data for this view. Records remain tied to their original conversation and WhatsApp number.</Alert>}
 <Dialog open={Boolean(edit)} onClose={()=>!busy&&setEdit(null)} maxWidth="md" fullWidth><DialogTitle>{edit?.id?'Edit':'Create'} reminder sequence</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><Typography variant="caption" color="error">* Required fields</Typography><TextField required aria-required="true" label="Sequence name" value={edit?.name||''} error={Boolean(errors.name)} helperText={errors.name} onChange={e=>setEdit({...edit,name:e.target.value})}/><WhatsAppAccountSelect required fullWidth value={edit?.whatsappAccountId||''} onChange={whatsappAccountId=>setEdit({...edit,whatsappAccountId})}/><TextField label="Description" multiline value={edit?.description||''} onChange={e=>setEdit({...edit,description:e.target.value})}/>
 {edit?.steps?.map((step,index)=><Card variant="outlined" key={step.id||index}><CardContent><Stack direction="row" alignItems="center"><Typography sx={{flex:1}}>Reminder {index+1}</Typography><IconButton onClick={()=>move(index,-1)}><ArrowUpward/></IconButton><IconButton onClick={()=>move(index,1)}><ArrowDownward/></IconButton><IconButton onClick={()=>setEdit({...edit,steps:[...edit.steps,{...step,id:undefined,mediaConfig:{...(step.mediaConfig||{})},interactiveConfig:{buttons:(step.interactiveConfig?.buttons||[]).map(button=>({...button}))}}]})}><ContentCopy/></IconButton><IconButton onClick={()=>setEdit({...edit,steps:edit.steps.filter((_,item)=>item!==index)})}><Delete/></IconButton></Stack><Stack direction={{xs:'column',md:'row'}} spacing={1}><TextField required type="number" inputProps={{min:0,step:1}} label="Send after" value={step.delayValue} error={Boolean(errors[`steps.${index}.delayValue`])} helperText={errors[`steps.${index}.delayValue`]} onChange={e=>patchStep(index,{delayValue:e.target.value})}/><TextField required select label="Unit" value={step.delayUnit} onChange={e=>patchStep(index,{delayUnit:e.target.value})}>{['minutes','hours','days'].map(unit=><MenuItem key={unit} value={unit}>{unit}</MenuItem>)}</TextField><TextField required select label="Message type" value={step.sessionMessageType||'text'} onChange={e=>patchStep(index,{sessionMessageType:e.target.value})}>{[['text','Text'],['image','Image + caption'],['buttons','Interactive buttons'],['image_buttons','Image + buttons']].map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField></Stack>
 <TextField required fullWidth multiline label={step.sessionMessageType==='text'?'Message body *':'Message body/caption *'} value={step.body||''} sx={{mt:1}} error={Boolean(errors[`steps.${index}.body`])} helperText={errors[`steps.${index}.body`]} onChange={e=>patchStep(index,{body:e.target.value})}/>
 {['image','image_buttons'].includes(step.sessionMessageType)&&<Stack spacing={1} sx={{mt:1}}><TextField required label="Meta media ID *" value={step.mediaConfig?.mediaId||''} error={Boolean(errors[`steps.${index}.mediaConfig`])} helperText={errors[`steps.${index}.mediaConfig`]||'Use an image uploaded through the CRM secure media pipeline.'} onChange={e=>patchStep(index,{mediaConfig:{...(step.mediaConfig||{}),mediaId:e.target.value,whatsappAccountId:edit.whatsappAccountId,mimeType:'image/jpeg',mediaType:'image',uploadStatus:'ready'}})}/><TextField label="Original filename" value={step.mediaConfig?.fileName||''} onChange={e=>patchStep(index,{mediaConfig:{...(step.mediaConfig||{}),fileName:e.target.value}})}/></Stack>}
 {['buttons','image_buttons'].includes(step.sessionMessageType)&&<Stack spacing={1} sx={{mt:1}}><TextField label="Footer" value={step.footer||''} onChange={e=>patchStep(index,{footer:e.target.value})}/>{(step.interactiveConfig?.buttons||[]).map((button,bi)=><Card variant="outlined" key={bi}><CardContent><Stack spacing={1}><TextField required label="Button title *" value={button.title||''} inputProps={{maxLength:20}} onChange={e=>{const buttons=[...(step.interactiveConfig?.buttons||[])];buttons[bi]={...button,title:e.target.value};patchStep(index,{interactiveConfig:{buttons}})}}/><TextField required label="Stable button ID *" value={button.buttonId||''} onChange={e=>{const buttons=[...(step.interactiveConfig?.buttons||[])];buttons[bi]={...button,buttonId:e.target.value};patchStep(index,{interactiveConfig:{buttons}})}}/><TextField select label="Trigger behavior" value={button.behavior||'none'} onChange={e=>{const buttons=[...(step.interactiveConfig?.buttons||[])];buttons[bi]={...button,behavior:e.target.value};patchStep(index,{interactiveConfig:{buttons}})}}>{[['trigger_keyword','Trigger Flow keyword'],['start_flow','Start selected flow directly'],['crm_action','CRM action only'],['none','No automation']].map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField>{button.behavior==='trigger_keyword'&&<TextField required label="Trigger keyword *" value={button.triggerKeyword||''} helperText="Uses Flow Builder Unicode, case and whitespace normalization." onChange={e=>{const buttons=[...(step.interactiveConfig?.buttons||[])];buttons[bi]={...button,triggerKeyword:e.target.value};patchStep(index,{interactiveConfig:{buttons}})}}/>}<TextField select label="After click" value={button.sequenceBehavior||'flow_decides'} onChange={e=>{const buttons=[...(step.interactiveConfig?.buttons||[])];buttons[bi]={...button,sequenceBehavior:e.target.value};patchStep(index,{interactiveConfig:{buttons}})}}>{[['flow_decides','Let triggered flow decide'],['continue','Continue sequence'],['pause','Pause sequence'],['stop','Stop sequence'],['complete','Complete sequence']].map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><Button color="error" onClick={()=>patchStep(index,{interactiveConfig:{buttons:(step.interactiveConfig?.buttons||[]).filter((_,i)=>i!==bi)}})}>Remove button</Button></Stack></CardContent></Card>)}<Button disabled={(step.interactiveConfig?.buttons||[]).length>=3} onClick={()=>patchStep(index,{interactiveConfig:{buttons:[...(step.interactiveConfig?.buttons||[]),{title:'',buttonId:'',behavior:'none',sequenceBehavior:'flow_decides'}]}})}>Add quick reply</Button>{errors[`steps.${index}.buttons`]&&<Typography color="error">{errors[`steps.${index}.buttons`]}</Typography>}</Stack>}
 <Card sx={{mt:2,bgcolor:'#e5ddd5'}}><CardContent><Typography variant="caption">Inside 24 hours preview</Typography>{['image','image_buttons'].includes(step.sessionMessageType)&&<Box sx={{height:90,bgcolor:'grey.300',my:1,display:'grid',placeItems:'center'}}>Image: {step.mediaConfig?.fileName||'not selected'}</Box>}<Typography>{step.body||'Message preview'}</Typography>{step.footer&&<Typography variant="caption">{step.footer}</Typography>}<Stack direction="row" spacing={1} sx={{mt:1}}>{(step.interactiveConfig?.buttons||[]).map(b=><Button key={b.buttonId||b.title} size="small" variant="outlined">{b.title||'Button'}</Button>)}</Stack></CardContent></Card>
 <Stack direction={{xs:'column',md:'row'}} spacing={1} sx={{mt:2}}><TextField label="Outside-24-hour approved template ID" value={step.templateId||''} helperText="Only an approved template belonging to the selected WhatsApp account is accepted." onChange={e=>patchStep(index,{templateId:e.target.value})}/><TextField label="Template language" value={step.templateLanguage||'en_US'} onChange={e=>patchStep(index,{templateLanguage:e.target.value})}/></Stack>
 {!step.templateId&&<Alert severity="warning" sx={{mt:1}}>Outside 24 hours: select an approved fallback template or execution will be blocked.</Alert>}</CardContent></Card>)}
 <Button onClick={()=>setEdit({...edit,steps:[...edit.steps,blankStep()]})}>Add reminder step</Button>{errors.steps&&<Typography color="error" variant="caption">{errors.steps}</Typography>}</Stack></DialogContent><DialogActions><Button disabled={busy} onClick={()=>setEdit(null)}>Cancel</Button><Button disabled={busy||Object.keys(invalidFields(edit,false)).length>0} onClick={()=>save(false)}>{busy?'Saving…':'Save Draft'}</Button>{(!edit?.id||['draft','paused'].includes(edit?.status))&&<Button variant="contained" disabled={busy||Object.keys(invalidFields(edit,true)).length>0} onClick={()=>save(true)}>{edit?.status==='paused'?'Save & Resume':'Save & Activate'}</Button>}</DialogActions></Dialog></Box>
}
