import React from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, MenuItem, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { Add, ArrowDownward, ArrowUpward, ContentCopy, Delete } from '@mui/icons-material';
import * as service from '../services/reminderSequence.service';
const blankStep=()=>({delayValue:1,delayUnit:'hours',messageMode:'automatic',sessionMessageType:'text',body:'',templateId:'',templateLanguage:'en',enabled:true});
export default function ReminderSequencesPage(){
 const [tab,setTab]=React.useState(0),[rows,setRows]=React.useState([]),[stats,setStats]=React.useState({}),[edit,setEdit]=React.useState(null),[error,setError]=React.useState(''),[errors,setErrors]=React.useState({}),[busy,setBusy]=React.useState(false);
 const load=React.useCallback(async()=>{try{const [a,b]=await Promise.all([service.listSequences(),service.getReminderDashboard()]);setRows(a.data.data.rows);setStats(b.data.data)}catch(e){setError(e.response?.data?.message||e.message)}},[]);
 React.useEffect(()=>{load()},[load]);
 const validate=()=>{const next={};if(!edit?.name?.trim())next.name='Sequence name is required.';if(!edit?.steps?.length)next.steps='Add at least one reminder step.';(edit?.steps||[]).forEach((s,i)=>{if(!Number.isInteger(Number(s.delayValue))||Number(s.delayValue)<0)next[`steps.${i}.delayValue`]='Send after must be a whole number of zero or more.';if(!['minutes','hours','days'].includes(s.delayUnit))next[`steps.${i}.delayUnit`]='Choose a valid unit.';if(s.enabled!==false&&s.sessionMessageType==='text'&&!s.body?.trim())next[`steps.${i}.body`]='Message is required.'});setErrors(next);return next};
 const save=async()=>{if(busy)return;const invalid=validate();if(Object.keys(invalid).length){requestAnimationFrame(()=>document.querySelector('[aria-invalid="true"]')?.focus());return}setBusy(true);setError('');try{await service.saveSequence(edit.id,edit);setEdit(null);await load()}catch(e){const fieldErrors=e.response?.data?.errors||{};setErrors(fieldErrors);setError(Object.values(fieldErrors)[0]||e.response?.data?.message||e.message)}finally{setBusy(false)}};
 const move=(i,d)=>setEdit(x=>{const steps=[...x.steps],j=i+d;if(j<0||j>=steps.length)return x;[steps[i],steps[j]]=[steps[j],steps[i]];return{...x,steps}});
 return <Box><Typography variant="h4" gutterBottom>Reminder Sequences</Typography>{error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}
 <Grid container spacing={2} sx={{mb:2}}>{[['Active sequences','activeSequences'],['Active subscriptions','activeSubscriptions'],['Due next hour','dueNextHour'],['Sent today','sentToday'],['Failed today','failedToday'],['Stopped by reply','stoppedByReply']].map(([l,k])=><Grid item xs={6} md={2} key={k}><Card><CardContent><Typography color="text.secondary">{l}</Typography><Typography variant="h4">{stats[k]||0}</Typography></CardContent></Card></Grid>)}</Grid>
 <Tabs value={tab} onChange={(_,v)=>setTab(v)}><Tab label="Sequences"/><Tab label="Subscriptions"/><Tab label="Scheduled reminders"/><Tab label="Execution history"/><Tab label="Settings"/></Tabs>
 {tab===0&&<Stack spacing={1} sx={{mt:2}}><Button variant="contained" startIcon={<Add/>} onClick={()=>setEdit({name:'',description:'',status:'draft',timezone:'Asia/Colombo',stopOnCustomerReply:true,steps:[blankStep()]})}>Create sequence</Button>{rows.map(r=><Card key={r.id} onClick={()=>setEdit({...r,steps:r.steps||[]})} sx={{cursor:'pointer'}}><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h6">{r.name}</Typography><Typography color="text.secondary">{r.description||'No description'} · {r.steps.length} steps</Typography></Box><Chip label={r.status}/></Stack></CardContent></Card>)}</Stack>}
 {tab>0&&<Alert severity="info" sx={{mt:2}}>Use the filters and paginated API data for this view. Records remain tied to their original conversation and WhatsApp number.</Alert>}
 <Dialog open={Boolean(edit)} onClose={()=>!busy&&setEdit(null)} maxWidth="md" fullWidth><DialogTitle>{edit?.id?'Edit':'Create'} reminder sequence</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><Typography variant="caption" color="error">* Required fields</Typography><TextField required aria-required="true" label="Sequence name" value={edit?.name||''} error={Boolean(errors.name)} helperText={errors.name} onChange={e=>setEdit({...edit,name:e.target.value})}/><TextField label="Description" multiline value={edit?.description||''} onChange={e=>setEdit({...edit,description:e.target.value})}/>
 {edit?.steps?.map((s,i)=><Card variant="outlined" key={s.id||i}><CardContent><Stack direction="row" alignItems="center"><Typography sx={{flex:1}}>Reminder {i+1}</Typography><IconButton onClick={()=>move(i,-1)}><ArrowUpward/></IconButton><IconButton onClick={()=>move(i,1)}><ArrowDownward/></IconButton><IconButton onClick={()=>setEdit({...edit,steps:[...edit.steps,{...s,id:undefined}]})}><ContentCopy/></IconButton><IconButton onClick={()=>setEdit({...edit,steps:edit.steps.filter((_,x)=>x!==i)})}><Delete/></IconButton></Stack><Stack direction={{xs:'column',md:'row'}} spacing={1}><TextField required aria-required="true" type="number" inputProps={{min:0,step:1}} label="Send after" value={s.delayValue} error={Boolean(errors[`steps.${i}.delayValue`])} helperText={errors[`steps.${i}.delayValue`]} onChange={e=>{const steps=[...edit.steps];steps[i]={...s,delayValue:e.target.value};setEdit({...edit,steps})}}/><TextField required aria-required="true" select label="Unit" value={s.delayUnit} error={Boolean(errors[`steps.${i}.delayUnit`])} helperText={errors[`steps.${i}.delayUnit`]} onChange={e=>{const steps=[...edit.steps];steps[i]={...s,delayUnit:e.target.value};setEdit({...edit,steps})}}>{['minutes','hours','days'].map(unit=><MenuItem key={unit} value={unit}>{unit}</MenuItem>)}</TextField></Stack><TextField required aria-required="true" fullWidth multiline label="Inside 24 hours: normal message" value={s.body||''} sx={{mt:1}} error={Boolean(errors[`steps.${i}.body`])} helperText={errors[`steps.${i}.body`]} onChange={e=>{const steps=[...edit.steps];steps[i]={...s,body:e.target.value};setEdit({...edit,steps})}}/>{!s.templateId&&<Alert severity="warning" sx={{mt:1}}>Outside-24-hour fallback template is optional. This step will be blocked outside the service window.</Alert>}</CardContent></Card>)}
 <Button onClick={()=>setEdit({...edit,steps:[...edit.steps,blankStep()]})}>Add reminder step</Button>{errors.steps&&<Typography color="error" variant="caption">{errors.steps}</Typography>}</Stack></DialogContent><DialogActions><Button disabled={busy} onClick={()=>setEdit(null)}>Cancel</Button><Button variant="contained" disabled={busy||!edit?.name?.trim()||!(edit?.steps?.length)||edit.steps.some(s=>!s.body?.trim()||!['minutes','hours','days'].includes(s.delayUnit)||!Number.isInteger(Number(s.delayValue))||Number(s.delayValue)<0)} onClick={save}>{busy?'Saving…':'Save'}</Button></DialogActions></Dialog></Box>
}
